In [1]:
import pandas as pd
import os
import re

def load_table(file, separator=None):
    df = ''
    if str(file).split('.')[-1] == 'tsv':
        separator = '\t' if separator is None else separator
        df = pd.read_csv(file, encoding='latin-1', sep=separator, dtype='str')
    elif str(file).split('.')[-1] == 'csv':
        separator = ',' if separator is None else separator
        df = pd.read_csv(file, encoding='latin-1', sep=separator, dtype='str')
    elif str(file).split('.')[-1] in ['xls', 'xlsx']:
        df = pd.read_excel(file, index_col=None, header=0, sheet_name=0, dtype='str')
        df.fillna('', inplace=True)
    else:
        print('Wrong file format. Compatible file formats: TSV, CSV, XLS, XLSX')
        exit()
    return df

In [ ]:
df_sabin_covid['DataAtendimentoF1'] = df_sabin_covid['DataAtendimento'].apply(convert_date)
df_sabin_covid.query("DataAtendimentoF1.str.contains('12/2023')")['DataAtendimentoF1']

### Teste Read CSV

In [3]:
df_sabin_covid = pd.read_csv(
    './../data/SABIN/_out_csv/20230823_SABIN_Covid_2023ateSE33.xlsx - 2023.csv'
)

df_sabin_paincovi = pd.read_csv(
    './../data/SABIN/_out_csv/20230823_SABIN_Painel respiratorio 2023ateSE33.xlsx - PAINCOVI.csv'
)

df_sabin_respira = pd.read_csv(
    './../data/SABIN/_out_csv/20230823_SABIN_Painel respiratorio 2023ateSE33.xlsx - RESPIRA.csv'
)

df_sabin_pcrespsl = pd.read_csv(
    './../data/SABIN/_out_csv/20230823_SABIN_Painel respiratorio 2023ateSE33.xlsx - PCRESPSL.csv'
)

df_sabin_pcrvresp = pd.read_csv(
    './../data/SABIN/_out_csv/20230823_SABIN_Painel respiratorio 2023ateSE33.xlsx - PCRVRESP.csv'
)

In [4]:
df_full = pd.concat([
    df_sabin_covid,
    df_sabin_paincovi,
    df_sabin_respira,
    df_sabin_pcrespsl,
    df_sabin_pcrvresp
])

In [5]:
df_full['DataAtendimento'].replace( re.compile("[0-9]"), "x" ).unique()

array(['xx/xx/xxxx', 'x/x/xxxx', 'x/xx/xxxx', 'xx/x/xxxx'], dtype=object)

In [9]:
df_full['DataAtendimento']
df_full['DataAtendimentoF2'] = (
    pd.to_datetime(df_full['DataAtendimento'], format='%d/%m/%Y', dayfirst=True)
)

df_full['DataNascimentoF2'] = (
    pd.to_datetime(df_full['DataNascimento'], format='%d/%m/%Y', dayfirst=True, errors='coerce')
)

df_full['DataAssinaturaF2'] = (
    pd.to_datetime(df_full['DataAssinatura'], format='%d/%m/%Y', dayfirst=True)
)

In [11]:
df_full["DataNascimentoF2"].isnull().sum()
df_full[ df_full["DataNascimentoF2"].isnull() ]
# Seis registros que provavelmente tem haver com a mesma pessoa - DataNascimento = 12/31/1899

6

In [16]:
df_full['Código Posto'].unique()

array([ 321,  525,  324,  891,  407,  768, 1409, 1359,  649,  834,   32,
       1505,  781,  960,  783,  772,  199,  103,  491, 1565,  151,  221,
         54,  242,   86,  830,  885,  848,  397,  559,  763,   50,  561,
        174,  122,   36,  939,   44,  584,  770,  562,  575,  797,  237,
        901,  977, 1572, 1562,  150,  340,   74,   24,  743,  577,   53,
        616,  436,   45,   25,  142,   26,  651,   27,  145,  463,  493,
         47,    1,  102,  833, 1417,  742,  223, 1576,  936,  589,  585,
        586,  844, 1858,  944, 1269, 1610,  946, 1270,  755, 1612,   48,
        785, 1066,  942,  119, 1285,  430,  972,  954,   22,  200, 1469,
        449,  206, 1609,   43,   49,  932,  570,  847,  565,  681,  653,
        531,  959, 1374,  941,  918, 1647,  887,  948,  749,   83,   31,
        970, 1360,  180,  371, 1656, 1314,  975,  991,  566,  466,  124,
       1598, 1041, 1564,  998,  989,  121,  529,  572, 1408,  350,  527,
        413, 1473,  175,  806,  120,  650,  953,  526,  386, 1560,  107,
         17, 1545,  228,  126, 1939,  118,  396, 1239, 1256,  140,   30,
        117,  170,  177,  590,  235, 1415, 1364,  138, 1611,   13,  108,
         34,  344,  913,   51,  788,  136,   37,  546, 1043,  963, 1004,
        863, 1276, 1274,  935,  523,  858,  857,  329,  358,  360,  354,
       1574, 1139,  874,  492,  867,  204,  927,  338,  766,  165,  888,
         35,    9,  654, 1588, 1605, 1495,  923, 1215,   18,  201, 1556,
       1403,   81,   52, 1606,    4,  476,  408,  443,  747,  555, 1414,
       1375,  842,  931,  446, 1643, 1129, 1619,  767,  687,  524,  872,
       1854, 1602, 1953,  381,  448,  373,  415,  907, 1077,  655,  843,
        178,  774,  392, 1472, 1592,  179, 1946,  372,  550,  465,   33,
        225, 1603,  557, 1087,  335, 1343, 1659,  428,  771,  827,  961,
        988,  943, 1851,  587,  539, 1022,  909, 1320,  760,  804,  950,
       1608, 1064,  588, 1412, 1559,  792,  327,  262, 1613,  845,  343,
        773, 1411, 1370, 1601,  648,  952, 1275,  470,  482,  495,  779,
       1366,  666,  530, 1440, 1258,  417, 1554, 1398, 1607, 1369,  775,
        955,  791,  937,  974, 1190, 1161,  240,  660,  835,  875, 1027,
       1372,  877, 1020,  169,  865,  896, 1005,  920,  361, 1594,  440,
        976, 1467,  911, 1068,  906,  698,  981, 1170,  573,  794, 1358,
       1061, 1568,  882,   72, 1217, 1368,  477,   20,  899,  744,  244,
        224,  498, 1163,  825, 1558,  657,  731, 1134,  917, 1618,  720,
       1257,  592,  897, 1238,  579,  945,  689,  735,  796, 1571,  983,
       1850, 1093,  345,  356, 1831, 1536, 1289,  979,  411, 1367,  239,
       1104,  661, 1511,  292, 1863,  786,  659,  569, 1586, 1557,  591,
       1214,  947, 1135,  746,  647,  157,  973,  554,  978,  614, 1233,
        832,  984, 1038,  603,  904, 1232,  992, 1959,  458, 1252, 1734,
        999,  473, 1853, 1491, 1977, 1255, 1236, 1291,  940, 1113,  173,
        688,  807,  474, 1159,  748, 1140, 1271, 1982,  467, 1169, 1147,
       1024,  487, 1218, 1985,  831,  238,  401,  542,  241, 1247,  176,
       1219,  611,  163, 1401, 1940,  552, 1011,  159,  668, 1970, 1457,
        990, 1960, 1001,  966, 1075, 1056, 1047, 1645, 1573, 1978, 1593,
        696,  652, 1496, 1413,  667, 1823,  444, 1596, 1346, 1052,  388,
        949, 1981, 1153, 1279, 1148, 1240, 1990,  472, 1620,  838, 1307,
        841, 1999, 1569,  890, 1141,  541,  347,  210,  409,  410,  412,
        414,  416,  418,  419,  420,  421,  422,  423,  424,  425,  426,
        427,  429,  431,  432,  433,  434,  435,  437,  438,  439,  441,
        442,  445,  447,  450,  451,  452,  453,  454,  455,  456,  457,
        459,  460,  461,  462,  464,  468,  469,  471,  475,  478,  479,
        480,  481,  483,  484,  485,  486,  488,  489,  490,  494,  496,
        497,  499,  500,  501,  502,  503,  504,  505,  506,  507,  508,
        509,  510,  511,  512,  513,  514,  515,  516,  517,  518,  519,
        520,  521,  522,  528,  532, 1731, 1220])

In [18]:
df_full.query("`Código Posto` in [427]")

,OS,Código Posto,Estado,Municipio,DataAtendimento,DataNascimento,Sexo,Descricao,Parametro,Resultado,DataAssinatura,DataAtendimentoF2,DataNNascimentoF2,DataAssinaturaF2,DataNascimentoF2
3918,689-66647-8710,427,GOIAS,CRISTALINA,22/06/2023,27/05/1969,Feminino,PAINEL MOLECULAR PARA INFECÇÕES RESPIRATÓRIAS,RSVA,0,27/06/2023,2023-06-22,1969-05-27,2023-06-27,1969-05-27

In [19]:
df_full.query("DataAtendimento.str.contains('/7/')")

,OS,Código Posto,Estado,Municipio,DataAtendimento,DataNascimento,Sexo,Descricao,Parametro,Resultado,DataAssinatura,DataAtendimentoF2,DataNNascimentoF2,DataAssinaturaF2,DataNascimentoF2
70824,589-66656-61,589,MINAS GERAIS,UBERLANDIA,1/7/2023,15/01/1987,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,1/7/2023,2023-07-01,1987-01-15,2023-07-01,1987-01-15
70825,589-66656-140,589,MINAS GERAIS,UBERLANDIA,1/7/2023,18/01/2018,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,1/7/2023,2023-07-01,2018-01-18,2023-07-01,2018-01-18
70826,1359-66656-951,1359,MATO GROSSO,CUIABA,1/7/2023,17/05/1957,Feminino,DETECCAO QUALITATIVA DE ANTIGENOS DE SARS-CoV-2,COVIDECO,NÃO DETECTADO,1/7/2023,2023-07-01,1957-05-17,2023-07-01,1957-05-17
70827,937-66656-5102,937,MINAS GERAIS,UBERLANDIA,1/7/2023,19/03/1982,Masculino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,DETECTADO (Presença de RNA específico de SARS-...,1/7/2023,2023-07-01,1982-03-19,2023-07-01,1982-03-19
70828,586-66656-5579,586,MINAS GERAIS,UBERLANDIA,1/7/2023,23/01/1978,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,1/7/2023,2023-07-01,1978-01-23,2023-07-01,1978-01-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10582,262-66667-17786,262,MINAS GERAIS,UBERABA,12/7/2023,25/10/1952,Feminino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",PCRVRESPBM4,NÃO DETECTADO (Ausência de RNA viral específico),15/07/2023,2023-07-12,1952-10-25,2023-07-15,1952-10-25
10583,262-66667-17786,262,MINAS GERAIS,UBERABA,12/7/2023,25/10/1952,Feminino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",PCRVRESP,NÃO DETECTADO (Ausência de RNA viral específico),15/07/2023,2023-07-12,1952-10-25,2023-07-15,1952-10-25
10584,262-66667-17786,262,MINAS GERAIS,UBERABA,12/7/2023,25/10/1952,Feminino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",GENES,NÃO DETECTADO,15/07/2023,2023-07-12,1952-10-25,2023-07-15,1952-10-25
10585,262-66667-17786,262,MINAS GERAIS,UBERABA,12/7/2023,25/10/1952,Feminino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",GENERDRP,NÃO DETECTADO,15/07/2023,2023-07-12,1952-10-25,2023-07-15,1952-10-25
10586,262-66667-17786,262,MINAS GERAIS,UBERABA,12/7/2023,25/10/1952,Feminino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",GENEN,NÃO DETECTADO,15/07/2023,2023-07-12,1952-10-25,2023-07-15,1952-10-25

In [ ]:
df_full.query("DataAtendimento.str.contains('/2022')")[['DataAtendimento', 'DataAtendimentoF2']]

   DataAtendimento DataAtendimentoF2
0       21/12/2022        2022-12-21
1       29/12/2022        2022-12-29
2       29/12/2022        2022-12-29
3       29/12/2022        2022-12-29
4       29/12/2022        2022-12-29
..             ...               ...
3       31/12/2022        2022-12-31
4       31/12/2022        2022-12-31
5       31/12/2022        2022-12-31
6       31/12/2022        2022-12-31
7       31/12/2022        2022-12-31

[234 rows x 2 columns]