python scripts/reformat_hlagyn.py --datadir data --rename data/rename_columns.xlsx --correction data/fix_values.xlsx --output combined_hlagyn.tsv

In [4]:
import pandas as pd
import os

def load_table(file, separator=None):
    df = ''
    if str(file).split('.')[-1] == 'tsv':
        separator = '\t' if separator is None else separator
        df = pd.read_csv(file, encoding='latin-1', sep=separator, dtype='str')
    elif str(file).split('.')[-1] == 'csv':
        separator = ',' if separator is None else separator
        df = pd.read_csv(file, encoding='latin-1', sep=separator, dtype='str')
    elif str(file).split('.')[-1] in ['xls', 'xlsx']:
        df = pd.read_excel(file, index_col=None, header=0, sheet_name=0, dtype='str')
        df.fillna('', inplace=True)
    else:
        print('Wrong file format. Compatible file formats: TSV, CSV, XLS, XLSX')
        exit()
    return df

In [5]:
df_combined = pd.read_csv('../combined_hlagyn.tsv', sep='\t')

In [3]:
BASE_PATH = '../data/HLAGyn/'
dfs = []

dfs_para_influ = []
dfs_ph4 = []
dfs_covid = []
dfts_ctn = []

for file in os.listdir(BASE_PATH):
    if file.endswith(('.xls', '.xlsx')):
        print(file)
        df = load_table(BASE_PATH + file).assign(filename=file)
        dfs.append(df)

        columns = ''.join(df.columns.tolist())
        h1n1_column = 'H1N1' in columns or 'Influenza' in columns
        ctn_column = 'CT_N' in columns

        if h1n1_column:
            if 'Parainfluenza' in columns:
                dfs_para_influ.append(df)
            elif 'PH4' in columns:
                dfs_ph4.append(df)
            elif 'SARS-CoV-2' in columns:
                dfs_covid.append(df)
        elif ctn_column:
            dfts_ctn.append(df)
        else:
            print('Unknown type')

20220329_Painel Viral 24_Segunda quinzena de Março de 2022.xlsx
20220912_PR24_SE36.xlsx
20230130_COVID_SE04.xlsx
20221121_PR24_SE46.xlsx
20230320_PR4_SE11.xlsx
20230102_PR4_SE52.xlsx
20230116_PR4_SE02.xlsx
20221210_COVID_SE49.xlsx
20220926_PR4_SE38.xlsx
20230605_PR24_SE22.xlsx
20230808_PR24_SE31.xlsx
20220614_PR4_se23.xlsx
20220627_PR4_SE25.xlsx
20220912_Covid_SE36.xlsx
20230320_COVID_SE11.xlsx
20230130_PR4_SE04.xlsx
20230731_PR24_SE30.xlsx
20220823_PR4_SE33.xlsx
20230626_PR4_SE25.xlsx
20220601_PR4_se21.xlsx
20220808_PR24_SE31.xlsx
20220510_PR24_se18.xlsx
20230313_PR4_SE10.xlsx
20230403_PR4_SE13.xlsx
20230130_PR24_SE04.xlsx
20220912_PR4_SE36.xlsx
20230208_PR24_SE05.xlsx
20230717_PR4_SE28.xlsx
20220504_Painel Viral 24_SE 17_2022.xlsx
20230102_COVID_SE52.xlsx
20230529_PR24_SE21.xlsx
20230701_PR24_SE26.xlsx
20230213_PR4_SE06.xlsx
20230307_PR24_SE09.2023.xlsx
20230307_PR4_SE09.2023.xlsx
20220823_PR24_SE33.xlsx
20221121_COVID_SE46.xlsx
20220704_PR4_SE26.xlsx
20220919_PR24_SE37.xlsx
20221205_PR24_SE48.xlsx
20230701_Covid_SE26.xlsx
20220713_Covid_SE27.xlsx
20221115_PR4_SE45.xlsx
20230417_Covid_SE15.xlsx
20220427_Painel Viral 24_SE 16_2022.xlsx
20220906_PR24_SE35.xlsx
20230522_Covid_SE20.xlsx
20220504_Painel Viral 4_SE 17_2022.xlsx
20220329_Painel Viral 4_Segunda quinzena de Março de 2022.xlsx
20220405_Painel Viral 4.xlsx
20220601_PR24_se19_HLAGYN.xlsx
20230329_PR4_SE12.xlsx
20230612_PR24_SE23.xlsx
20230417_PR4_SE15.xlsx
20220727_Covid_SE29.xlsx
20230424_PR24_SE16.xlsx
20220314_Painel viral 24_FEV.MAR.2022.xlsx
20221024_PR4_SE42.xlsx
20230724_Covid_SE29.xlsx
20220816_Covid_SE32.xlsx
20220926_PR24_SE38.xlsx
20230508_PR24_SE18.xlsx
20230329_Covid_SE12.xlsx
20230424_PR4_SE16.xlsx
20221003_PR4_SE39.xlsx
20230710_PR4_SE27.xlsx
20220621_PR4_SE24.xlsx
20230626_PR24_SE25.xlsx
20221210_PR4_SE49.xlsx
20230502_PR4_SE17.xlsx
20221219_PR4_SE50.xlsx
20230313_COVID_SE10.xlsx
20221205_COVID_SE48.xlsx
20220510_PR4_se18.xlsx
20230213_PR24_SE06.xlsx
20230731_PR4_SE30.xlsx
20230424_Covid_SE16.xlsx
20230724_PR4_SE29.xlsx
20230116_PR24_SE02.xlsx
20230124_PR4_SE03.xlsx
20220713_PR24_se27.xlsx
20220614_PR24_se23.xlsx
20230619_PR4_SE24.xlsx
20230221_PR4_SE07.xlsx
20230329_PR24_SE12.xlsx
20221031_PR24_SE43.xlsx
20230502_Covid_SE17.xlsx
20221024_PR24_SE42.xlsx
20230529_Covid_SE21.xlsx
20221226_PR4_SE51.xlsx
20220517_PR24_se19_HLAGYN.xlsx
20221121_PR4_SE46.xlsx
20221107_PR24_SE44.xlsx
20221019_PR4_SE40.xlsx
20221210_PR24_SE49.xlsx
20220906_COVID_SE35.xlsx
20220713_PR4_SE27.xlsx
20221219_COVID_SE50.xlsx
20230619_Covid_SE24.xlsx
20230110_Covid_SE01.xlsx
20230710_PR24_SE27.xlsx
20221019_PR24_SE40.xlsx
20230410_Covid_SE14.xlsx
20220926_COVID_SE38.xlsx
20230208_PR4_SE05.xlsx
20230124_COVID_SE03.xlsx
20230227_PR24_SE08.xlsx
20221031_COVID_SE43.xlsx
20220314_Painel viral 4_JAN a MAR.2022.xlsx
20220601_PR4_se19_HLAGYN.xlsx
20220517_PR4_se19_HLAGYN.xlsx
20230515_PR4_SE19.xlsx
20220627_PR24_se25.xlsx
20221115_COVID_SE45.xlsx
20230502_PR24_SE17.xlsx
20230731_Covid_SE30.xlsx
20220829_PR24_SE34.xlsx
20221115_PR24_SE45.xlsx
20230710_Covid_SE27.xlsx
20220816_PR4_SE32.xlsx
20221128_PR24_SE47.xlsx
20230116_COVID_SE02.xlsx
20230403_PR24_SE13.xlsx
20230410_PR4_SE14.xlsx
20220727_PR24_SE29.xlsx
20220808_Covid_SE31.xlsx
20230307_Covid_SE09.2023.xlsx
20230313_PR24_SE10.xlsx
20220829_Covid_SE34.xlsx
20220405_Painel Viral 24.xlsx
20220808_PR4_SE31.xlsx
20230417_PR24_SE15.xlsx
20230522_PR4_SE20.xlsx
20220727_PR4_SE28.xlsx
20221128_PR4_SE47.xlsx
20230717_PR24_SE28.xlsx
20221226_PR24_SE51.xlsx
20230612_Covid_SE23.xlsx
20220614_PR24_se22.xlsx
20230403_Covid_SE13.xlsx
20220829_PR4_SE34.xlsx
20221003_COVID_SE39.xlsx
20230612_PR4_SE23.xlsx
20230808_Covid_SE31.xlsx
20220621_PR24_SE24.xlsx
20230208_COVID_SE05.xlsx
20221019_COVID_SE41.xlsx
20221019_COVID_SE40.xlsx
20220727_Covid_SE28.xlsx
20230227_PR4_SE08.xlsx
20220816_PR24_SE32.xlsx
20230529_PR4_SE21.xlsx
20220727_PR24_SE28.xlsx
20230508_Covid_SE18.xlsx
20230227_Covid_SE08.xlsx
20220727_PR4_SE29.xlsx
20230221_PR24_SE07.xlsx
20230626_Covid_SE25.xlsx
20221019_PR24_SE41.xlsx
20230717_Covid_SE28.xlsx
20230110_PR4_SE01.xlsx
20230605_Covid_SE22.xlsx
20221107_PR4_SE44.xlsx
20221031_PR4_SE43.xlsx
20221019_PR4_SE41.xlsx
20220919_COVID_SE37.xlsx
20230724_PR24_SE29.xlsx
20221107_COVID_SE44.xlsx
20221128_COVID_SE47.xlsx
20220803_Covid_SE30.xlsx
20220803_PR24_SE30.xlsx
20220427_Painel Viral 4_SE 16_2022.xlsx
20230110_PR24_SE01.xlsx
20230508_PR4_SE18.xlsx
20230619_PR24_SE24.xlsx
20221024_Covid_SE42.xlsx
20220704_Covid_SE26.xlsx
20230320_PR24_SE11.xlsx
20230102_PR24_SE52.xlsx
20220906_PR4_SE35.xlsx
20221205_PR4_SE48.xlsx
20221003_PR24_SE39.xlsx
20230515_Covid_SE19.xlsx
20230808_PR4_SE31.xlsx
20230515_PR24_SE19.xlsx
20221219_PR24_SE50.xlsx
20221226_COVID_SE51.xlsx
20230124_PR24_SE03.xlsx
20230605_PR4_SE22.xlsx
20230410_PR24_SE14.xlsx
20220225_Painel_Viral_Fev.2022.xlsx
20230221_Covid_SE07.xlsx
20220823_Covid_SE33.xlsx
20220803_PR4_SE30.xlsx
20220919_PR4_SE37.xlsx
20220614_PR4_se22.xlsx
20220131_Painel viral_JAN.2022.xlsx
20220207_Painel Viral_HLAGYN_Fev.xlsx
20230701_PR4_SE26.xlsx
20230522_PR24_SE20.xlsx
20220704_PR24_SE26.xlsx
20230213_COVID_SE06.xlsx

In [4]:
df_hla_flu = pd.concat(dfs_para_influ)
df_hla_ph4 = pd.concat(dfs_ph4)
df_hla_covid = pd.concat(dfs_covid)
df_hla_ctn = pd.concat(dfts_ctn)

## Duplicatas

In [6]:
df_duplicates = (
    df_combined
    .assign( one=1 )
    .groupby(['sample_id'])
    .agg(num_duplicates=('one', 'sum'))
    .query("num_duplicates > 1")
    .assign(num_duplicates=lambda x: x['num_duplicates']-1)
)


print( df_duplicates['num_duplicates'].sum(), df_duplicates['num_duplicates'].max(), df_duplicates['num_duplicates'].min() )
df_duplicates.sort_values('num_duplicates', ascending=False).head(10)

0 nan nan

Empty DataFrame
Columns: [num_duplicates]
Index: []

In [8]:
df_duplicates = (
    df_combined
    # .query("test_kit == 'unknown'")
    .assign( one=1 )
    .groupby(['test_id'])
    .agg(num_duplicates=('one', 'sum'))
    .query("num_duplicates > 1")
    .assign(num_duplicates=lambda x: x['num_duplicates']-1)
)


print( df_duplicates['num_duplicates'].sum(), df_duplicates['num_duplicates'].max(), df_duplicates['num_duplicates'].min() )
df_duplicates.sort_values('num_duplicates', ascending=False).head(10)

6 1 1

         num_duplicates
test_id
2199883               1
2199884               1
2199885               1
2199886               1
2200182               1
2200778               1

In [9]:
df_os_multiple_tests = (
    df_combined
    .groupby('test_id')
    .agg(kits=('test_kit',lambda x: ','.join(x.tolist())))
    .query("kits.str.contains(',')", engine='python') 
)

In [10]:
df_os_multiple_tests.head(10)

                    kits
test_id
2199883    test_4,test_4
2199884    test_4,test_4
2199885    test_4,test_4
2199886    test_4,test_4
2200182    test_4,test_4
2200778  test_24,test_24

In [11]:
df_combined.columns

Index(['lab_id', 'test_id', 'test_kit', 'patient_id', 'sample_id', 'state',
       'location', 'date_testing', 'epiweek', 'age', 'sex', 'FLUA_test_result',
       'Ct_FluA', 'FLUB_test_result', 'Ct_FluB', 'VSR_test_result', 'Ct_VSR',
       'SC2_test_result', 'Ct_geneE', 'Ct_geneN', 'Ct_geneS', 'Ct_ORF1ab',
       'Ct_RDRP', 'geneS_detection', 'META_test_result', 'RINO_test_result',
       'PARA_test_result', 'ADENO_test_result', 'BOCA_test_result',
       'COVS_test_result', 'ENTERO_test_result', 'BAC_test_result'],
      dtype='object')

## Uniqueness

In [12]:
if 'unknown' in df_combined['test_kit'].unique():
    print('WARNING! unknown test kits found')

df_combined['test_kit'].unique()

array(['test_24', 'test_4', 'covid_pcr'], dtype=object)

In [13]:
df_combined['state'].unique()

array(['Goiás', 'Bahia', nan, 'Distrito Federal'], dtype=object)

In [14]:
df_combined['location'].unique()

array(['GOIANIA', 'APARECIDA DE GOIANIA', 'RIO VERDE', 'NIQUELANDIA',
       'PALMEIRAS DE GOIAS', 'CACHOEIRA ALTA', 'ANAPOLIS', 'ITUMBIARA',
       'SANTA HELENA DE GOIAS', nan, 'NOVA VENEZA', 'CRIXAS', 'INHUMAS',
       'MINEIROS', 'CATALAO', 'PIRES DO RIO', 'BELA VISTA DE GOIAS',
       'ACREUNA', 'SENADOR CANEDO', 'CERES', 'IPAMERI', 'UIBAI', 'JATAI',
       'GOIANESIA', 'BRASILIA'], dtype=object)

In [15]:
df_combined['date_testing'].max(), df_combined['date_testing'].min()

('2023-08-19', '2002-01-01')

In [17]:
df_combined['age'].unique(), df_combined['age'].min(), df_combined['age'].max()

(array([ 59,  92,  49,  73,  28,   9,  39,  25,   0,  80,  32,  12,  43,
         46,  20,  35,  62,   3,  13,  82,  19,  54,  57,  21,  78,  77,
         83,  96,  40,  36,  85,   1,  64,  55,  31,  14,  44,  29,  72,
         27,  53,  18,  69,  58,   8,  56,  51,  41,  75,  37,  76,  61,
         48,  11,  22,  70,  26,  42,  38,  45,  79,  67,  47,   2,  90,
         63,  30,  34,  60,  24,  86,  33,  74,  17,  50,  23,   4,   5,
          7,  66,   6,  10,  94,  52,  15,  81,  68,  84,  88,  65,  16,
         87,  89,  71,  97,  91,  98,  93,  -1, 101,  95,  99, 106, 104,
        107, 100, 112, 103, 111, 102, 113, 105]),
 -1,
 113)

In [18]:
df_combined['sex'].unique()

array(['M', 'F', 'I'], dtype=object)

In [19]:
for column in df_combined.columns:
    if column.endswith('_result'):
        print(column, df_combined[column].unique())

FLUA_test_result ['Pos' 'Neg' 'NT']
FLUB_test_result ['Neg' 'Pos' 'NT']
VSR_test_result ['Neg' 'Pos' 'NT']
SC2_test_result ['Neg' 'Pos']
META_test_result ['Neg' 'NT' 'Pos']
RINO_test_result ['Pos' 'Neg' 'NT']
PARA_test_result ['Neg' 'Pos' 'NT']
ADENO_test_result ['Neg' 'Pos' 'NT']
BOCA_test_result ['Neg' 'Pos' 'NT']
COVS_test_result ['Neg' 'Pos' 'NT']
ENTERO_test_result ['Neg' 'Pos' 'NT']
BAC_test_result ['Neg' 'NT' 'Pos']

In [20]:
for col in df_combined.columns:
    if col.endswith('_result'):
        print(col)

FLUA_test_result
FLUB_test_result
VSR_test_result
SC2_test_result
META_test_result
RINO_test_result
PARA_test_result
ADENO_test_result
BOCA_test_result
COVS_test_result
ENTERO_test_result
BAC_test_result

## Inconsistencies

In [18]:
df_combined.columns

Index(['lab_id', 'test_id', 'test_kit', 'patient_id', 'sample_id', 'state',
       'location', 'date_testing', 'epiweek', 'age', 'sex', 'FLUA_test_result',
       'Ct_FluA', 'FLUB_test_result', 'Ct_FluB', 'VSR_test_result', 'Ct_VSR',
       'SC2_test_result', 'Ct_geneE', 'Ct_geneN', 'Ct_geneS', 'Ct_ORF1ab',
       'Ct_RDRP', 'geneS_detection', 'META_test_result', 'RINO_test_result',
       'PARA_test_result', 'ADENO_test_result', 'BOCA_test_result',
       'COVS_test_result', 'ENTERO_test_result', 'BAC_test_result'],
      dtype='object')

Verificando se um mesmo test_id + test_kit apresentam mais de um resultado para um mesmo patógeno

In [19]:
agg_test_rules = {
    col+'_kit': (col, lambda x: ','.join(x.tolist()))
    for col in df_combined.columns
    if col.endswith('_result')
}

df_os_non_contraditory_test_results = (
    df_combined
    .groupby(['test_id', 'test_kit'])
    .agg(**agg_test_rules)
)

In [20]:
for col in df_os_non_contraditory_test_results.columns:
    if col.endswith('_kit'):
        print(col, df_os_non_contraditory_test_results[col].unique())
        # Devem ser apenas ['NT' 'Neg' 'Pos']

FLUA_test_result_kit ['Pos' 'Neg' 'Neg,Neg' 'NT']
FLUB_test_result_kit ['Neg' 'Pos' 'Neg,Neg' 'NT']
VSR_test_result_kit ['Neg' 'Pos' 'Neg,Neg' 'Pos,Pos' 'NT']
SC2_test_result_kit ['Neg' 'Pos' 'Neg,Neg']
META_test_result_kit ['Neg' 'NT' 'Pos' 'NT,NT' 'Neg,Neg']
RINO_test_result_kit ['Pos' 'Neg' 'NT' 'NT,NT' 'Neg,Neg']
PARA_test_result_kit ['Neg' 'Pos' 'NT' 'NT,NT' 'Neg,Neg']
ADENO_test_result_kit ['Neg' 'Pos' 'NT' 'NT,NT' 'Neg,Neg']
BOCA_test_result_kit ['Neg' 'Pos' 'NT' 'NT,NT' 'Neg,Neg']
COVS_test_result_kit ['Neg' 'Pos' 'NT' 'NT,NT' 'Neg,Neg']
ENTERO_test_result_kit ['Neg' 'Pos' 'NT' 'NT,NT' 'Neg,Neg']
BAC_test_result_kit ['Neg' 'NT' 'NT,NT' 'Neg,Neg' 'Pos']

In [21]:
df_os_non_contraditory_test_results.query("SC2_test_result_kit == 'Neg,Neg'")

,,FLUA_test_result_kit,FLUB_test_result_kit,VSR_test_result_kit,SC2_test_result_kit,META_test_result_kit,RINO_test_result_kit,PARA_test_result_kit,ADENO_test_result_kit,BOCA_test_result_kit,COVS_test_result_kit,ENTERO_test_result_kit,BAC_test_result_kit
test_id,test_kit,,,,,,,,,,,,
2199883,test_4,"Neg,Neg","Neg,Neg","Neg,Neg","Neg,Neg","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT"
2199884,test_4,"Neg,Neg","Neg,Neg","Pos,Pos","Neg,Neg","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT"
2199885,test_4,"Neg,Neg","Neg,Neg","Pos,Pos","Neg,Neg","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT"
2199886,test_4,"Neg,Neg","Neg,Neg","Pos,Pos","Neg,Neg","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT"
2200182,test_4,"Neg,Neg","Neg,Neg","Pos,Pos","Neg,Neg","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT","NT,NT"
2200778,test_24,"Neg,Neg","Neg,Neg","Neg,Neg","Neg,Neg","Neg,Neg","Neg,Neg","Neg,Neg","Neg,Neg","Neg,Neg","Neg,Neg","Neg,Neg","Neg,Neg"

In [29]:
df_combined.query("test_id == 2200778")

,lab_id,test_id,test_kit,patient_id,sample_id,state,location,date_testing,epiweek,age,...,Ct_RDRP,geneS_detection,META_test_result,RINO_test_result,PARA_test_result,ADENO_test_result,BOCA_test_result,COVS_test_result,ENTERO_test_result,BAC_test_result
1681,HLAGyn,2200778,test_24,NaN,dee693bd80bacec9,Goiás,GOIANIA,2022-03-28,2022-04-02,5,...,NaN,NaN,Neg,Neg,Neg,Neg,Neg,Neg,Neg,Neg
1682,HLAGyn,2200778,test_24,NaN,b897be7483e76e1f,Goiás,APARECIDA DE GOIANIA,2022-03-28,2022-04-02,5,...,NaN,NaN,Neg,Neg,Neg,Neg,Neg,Neg,Neg,Neg

### Ids

Verificando se todos os Ids originais etão presentes no arquivo final

In [ ]:
set_test_ids_final_df = set(df_combined['test_id'])
set_test_ids_raw_data = set(df_full_raw['CODIGO REQUISICAO'])

In [ ]:
# Testar se todos os test_ids da planilha original estão na planilha final
# deve retornar um set vazio
set_test_ids_raw_data.difference(set_test_ids_final_df)

{'1200085178_100',
 '1410231927_100',
 '1421499943_100',
 '1421512238_100',
 '1421512252_100',
 '1421524508_100',
 '1421542791_100',
 '1421567484_600',
 '1421573025_900',
 '1421574120_100',
 '1421580321_100',
 '1421580345_100',
 '1421580359_600',
 '1421580372_100',
 '1421580414_700',
 '1421590360_100',
 '1421608991_700',
 '1421618661_100',
 '1421623648_100',
 '1421627267_100',
 '1421641149_200',
 '1421661054_100',
 '1421747497_400',
 '1450064023_100',
 '1450064862_100',
 '1600683873_100',
 '1600708233_100',
 '1600709104_100',
 '1600712587_100',
 '1650441468_100',
 '1650447361_100',
 '1650451652_100',
 '1660378198_100',
 '1720397744_100',
 '1860281386_100',
 '1870163611_100',
 '2230148082_100',
 '2240159856_100',
 '2240169073_100',
 '2240170521_100',
 '2240193197_100',
 '2240197205_100',
 '2310036024_100',
 '2320523931_100',
 '2320536507_100',
 '2320542723_100',
 '2320550391_100',
 '2320551123_100',
 '2320551273_100',
 '2320562210_100',
 '2320582241_100',
 '2350037816_100',
 '2350041791_100',
 '2350042472_100',
 '2350042486_100',
 '2370310135_100',
 '2370310765_100',
 '2430081777_100',
 '2430088155_100',
 '2430102133_100',
 '2430120877_100',
 '2430123544_100',
 '2430124239_100',
 '2760242375_200',
 '2830609707_100',
 '2851154630_100',
 '2851166392_100',
 '2851220324_100',
 '2851224888_100',
 '2851236445_100',
 '2890312083_100',
 '2890315981_3600',
 '2890319311_200',
 '2890327807_100',
 '2900309937_100',
 '2900311009_100',
 '2900323810_100',
 '2930619195_100',
 '2930625551_100',
 '2930629278_100',
 '2930647860_600',
 '2930654008_100',
 '3020633514_100',
 '3020634205_100',
 '3020635555_100',
 '3020639228_100',
 '3020642206_100',
 '3020648144_100',
 '3020652178_100',
 '3020657759_100',
 '3020713657_100',
 '3020730850_100',
 '3020735048_100',
 '3020744911_100',
 '3020751012_100',
 '3020892203_100',
 '3120234796_100',
 '3120236393_300',
 '3120249271_100',
 '3120249294_100',
 '3120253404_100',
 '3120262999_100',
 '3120267497_100',
 '3120269571_100',
 '3120269718_100',
 '3120275446_100',
 '3120287553_100',
 '3120305921_100',
 '3120306242_100',
 '3120309006_100',
 '3120312221_100',
 '3120324261_100',
 '3120330342_100',
 '3120333296_100',
 '3120333870_100',
 '3120353982_100',
 '3140122724_100',
 '3420239077_100',
 '3420239451_100',
 '3450927609_100',
 '3450927682_100',
 '3450927746_100',
 '3450927814_100',
 '3450928008_100',
 '3450928018_100',
 '3450928040_100',
 '3450928045_100',
 '3450928060_100',
 '3450928067_100',
 '3450938440_100',
 '3450965169_100',
 '3450966391_100',
 '3451016291_100',
 '3451055816_100',
 '3551666203_100',
 '3551666391_100',
 '3551669439_100',
 '3551669755_100',
 '3551669781_100',
 '3551669806_100',
 '3551672137_100',
 '3551675124_100',
 '3551675628_100',
 '3551677558_100',
 '3551678828_200',
 '3551684415_100',
 '3551724743_100',
 '3551734902_100',
 '3551744927_100',
 '3551757812_100',
 '3551764654_100',
 '3551766367_100',
 '3551770794_100',
 '3551783953_100',
 '3560743860_100',
 '3560746668_100',
 '3560747808_200',
 '3560747881_200',
 '3560763576_100',
 '3560764783_100',
 '3560767732_100',
 '3560768845_100',
 '3560768905_100',
 '3560778283_100',
 '3560781278_100',
 '3560794148_100',
 '3560796365_100',
 '3560799508_100',
 '3560799609_100',
 '3560799622_600',
 '3560800603_100',
 '3560800789_100',
 '3560800998_100',
 '3560801669_100',
 '3560801698_100',
 '3560802417_100',
 '3560804028_100',
 '3560809850_100',
 '3560812869_100',
 '3560819778_1900',
 '3560821774_100',
 '3560838327_100',
 '3560838343_100',
 '3560838350_100',
 '3560838360_100',
 '3560838380_500',
 '3560845384_100',
 '3560846056_200',
 '3560853275_200',
 '3610226750_100',
 '3640278826_100',
 '3710302696_100',
 '3710302731_100',
 '3760101391_100',
 '3760136464_100',
 '3760152069_500',
 '3760182265_1300',
 '3801215969_100',
 '3801223729_300',
 '3801232880_100',
 '3801234463_100',
 '3801242480_100',
 '3801284805_1400',
 '3801292059_100',
 '3900169658_100',
 '3900226965_100',
 '3940060240_100',
 '3950015922_100',
 '3950015924_100',
 '3950017675_100',
 '3950018650_100',
 '3950018971_100',
 '3950020636_100',
 '3950021073_100',
 '3950023089_100',
 '4230003993_100',
 '4280000503_100',
 '4290009208_100',
 '4312728300_100',
 '4312731983_100',
 '4312734566_900',
 '4312743981_100',
 '4312746400_200',
 '4312761939_100',
 '4312764248_100',
 '4312773516_100',
 '4312793501_100',
 '4312798630_100',
 '4312817705_100',
 '4312820154_100',
 '4312828565_100',
 '4312830531_300',
 '4312831456_1000',
 '4312837452_100',
 '4312838457_100',
 '4312838929_100',
 '4312839006_300',
 '4312839607_1200',
 '4312841490_400',
 '4312841910_100',
 '4312842368_100',
 '4312847406_100',
 '4312848884_100',
 '4312850940_200',
 '4312855289_200',
 '4312855947_800',
 '4312875699_100',
 '4312906214_1000',
 '4312921358_600',
 '4312921600_100',
 '4322777578_100',
 '4332151713_100',
 '4332153159_200',
 '4332171032_100',
 '4332171115_1600',
 '4332213052_100',
 '4341047718_100',
 '4341091393_200',
 '4341092835_100',
 '4341097638_100',
 '4341099666_100',
 '4341107994_100',
 '4341110510_100',
 '4350469861_100',
 '4350504191_100',
 '4350505613_100',
 '4350510877_100',
 '4350537500_100',
 '4350542763_800',
 '4350542822_100',
 '4350543705_1600',
 '4350545285_100',
 '4350553385_200',
 '4350553989_100',
 '4350556119_100',
 '4350561616_100',
 '4350564374_100',
 '4350586975_400',
 '4350587033_100',
 '4350587058_100',
 '4350587088_200',
 '4350587108_100',
 '4350588252_100',
 '4370432105_200',
 '4370475578_300',
 '4370476775_100',
 '4370476975_1600',
 '4370491587_700',
 '4370524806_100',
 '4370530639_100',
 '4370530849_100',
 '4370544506_100',
 '4370552007_100',
 '4370552882_600',
 '4370557029_100',
 '4370560396_100',
 '4390119905_200',
 '4403479036_100',
 '4403489465_100',
 '4403492858_100',
 '4403494393_100',
 '4403538324_100',
 '4403543904_100',
 '4403582380_100',
 '4403588332_100',
 '4403631706_100',
 '4403650211_100',
 '4403650327_100',
 '4403702551_100',
 '4403747113_100',
 '4409842350_200',
 '4409846153_100',
 '4430175336_100',
 '4430178676_100',
 '4430198486_100',
 '4430198491_100',
 '4430198507_100',
 '4430198513_100',
 '4430219012_100',
 '4430219102_100',
 '4430219557_2400',
 '4451933194_100',
 '4451933543_100',
 '4451933817_100',
 '4451934497_100',
 '4451955873_100',
 '4451962911_100',
 '4451962980_300',
 '4451972520_100',
 '4451972650_100',
 '4451972740_100',
 '4451986562_100',
 '4451992862_300',
 '4452022047_400',
 '4452024088_100',
 '4452024972_100',
 '4452027340_100',
 '4452027446_100',
 '4452029098_100',
 '4452030716_100',
 '4452031246_100',
 '4452034498_900',
 '4452034550_100',
 '4452034555_100',
 '4452035426_200',
 '4452060122_100',
 '4452094724_100',
 '4452095127_900',
 '4452095202_500',
 '4452095237_500',
 '4452095251_1800',
 '4452095291_300',
 '4452095297_100',
 '4452095301_200',
 '4452095350_100',
 '4452102784_200',
 '4452145333_100',
 '4452193918_100',
 '4460063977_300',
 '4460065323_100',
 '4460077857_100',
 '4470022669_100',
 '4470027241_100',
 '4470029203_100',
 '4480015210_100',
 '4540680705_800',
 '4540680804_2300',
 '4540681869_100',
 '4540682501_1200',
 '4540683780_200',
 '4540684922_100',
 '4540685116_100',
 '4540685923_200',
 '4540685924_100',
 '4540685933_200',
 '4540687601_200',
 '4540691294_400',
 '4540691756_200',
 '4540695930_100',
 '4540707539_100',
 '4540735562_100',
 '4540741755_100',
 '4540833811_100',
 '4540834096_300',
 '4540837101_100',
 '4540839431_100',
 '4540842677_200',
 '4540854622_100',
 '4540858550_100',
 '4550542977_100',
 '4550544946_100',
 '4550546157_100',
 '4550556634_1000',
 '4550558678_100',
 '4550561940_200',
 '4550563090_1000',
 '4550563495_300',
 '4550569485_100',
 '4550570747_100',
 '4550570785_100',
 '4550573604_100',
 '4550584059_200',
 '4550591493_500',
 '4550611507_100',
 '4550616334_600',
 '4550618368_100',
 '4550619525_100',
 '4550620920_100',
 '4550621683_1100',
 '4550624617_100',
 '4550625498_100',
 '4550635975_100',
 '4550637070_100',
 '4550642655_100',
 '4550645857_1300',
 '4550655321_2600',
 '4550661576_200',
 '4550673391_500',
 '4550673399_100',
 '4550676919_600',
 '4550677341_900',
 '4550690124_100',
 '4550703397_100',
 '4550708641_100',
 '4561698147_100',
 '4561700682_100',
 '4561702220_100',
 '4561721569_100',
 '4561751549_100',
 '4561808484_100',
 '4561843731_100',
 '4561983084_100',
 '4562002169_100',
 '4562015340_100',
 '4562042158_100',
 '4562060114_300',
 '4562082241_100',
 '4562086585_100',
 '4562116375_100',
 '4562133698_700',
 '4562138006_500',
 '4562165233_100',
 '4562166308_100',
 '4562186942_100',
 '4562200739_100',
 '4562230339_100',
 '4562230436_100',
 '4562233683_100',
 '4562242096_100',
 '4570467427_100',
 '4570472223_100',
 '4570473856_100',
 '4570475094_100',
 '4570519006_100',
 '4570550474_100',
 '4570575284_100',
 '4580310873_100',
 '4580360525_100',
 '4580371950_500',
 '4602124751_100',
 '4650159640_100',
 '4780054693_100',
 '4780065327_100',
 '4780069950_200',
 '4790285529_100',
 '4790311248_100',
 '4790312869_100',
 '4790314252_100',
 '4790324558_100',
 '4830102580_100',
 '4830103697_100',
 '4830104251_100',
 '4830113556_100',
 '5100132471_100',
 '5100139203_100',
 '5310079266_100',
 '5350045507_100',
 '5400311452_100',
 '5400311800_400',
 '5400313402_100',
 '5400316985_100',
 '5420274780_100',
 '5620056458_100',
 '5670138346_100',
 '5670141540_100',
 '5690066259_100',
 '5730069645_200',
 '6140293992_100',
 '6200019815_100',
 '6300606727_100',
 '6320156296_100',
 '6350492375_100',
 '6350492404_100',
 '6350492504_100',
 '6350511676_100',
 '6550391412_100',
 '6550419044_100',
 '6550419383_100',
 '6580095664_100',
 '6600838756_100',
 '6670695785_100',
 '6670728320_100',
 '7000705595_100',
 '7000709012_100',
 '7000712576_100',
 '7000713062_100',
 '7040087590_100',
 '7060009863_100',
 '7090058512_100',
 '7101031250_100',
 '7140012397_100',
 '7170021821_100',
 '7170028066_100',
 '7180050112_100',
 '7200683512_100',
 '7240012997_100',
 '7250031293_100',
 '7270005578_100',
 '7270005583_100',
 '7270005589_100',
 '7400868173_100',
 '7400869083_100',
 '7400877601_100',
 '7600173238_100',
 '7600190134_100',
 '7770978786_100',
 '7801594351_100',
 '7801612108_100',
 '7900180714_100',
 '8020387770_100',
 '8020393763_400',
 '8050552414_100',
 '8060124422_100',
 '8120091572_700',
 '8200258696_100',
 '8705004072_100',
 '8705004156_200',
 '8705005379_100',
 '8705005551_100',
 '8705038182_100',
 '8705155067_100',
 '8705373262_100',
 '8709853151_1100',
 '8750150094_1200',
 '8750152667_100',
 '8750168177_100',
 '8750173631_100',
 '8830022805_100',
 '8860020564_100',
 '8860020608_100',
 '8860020894_100',
 '8860021917_100',
 '8860027893_100',
 '8900398703_100',
 '8900420302_100',
 '8920001987_100',
 '9010080155_100',
 '9010086149_100',
 '9240044835_100',
 '9240045022_100',
 '9240045240_100',
 '9240067830_100',
 '9240072525_100',
 'Total de resultados: 103477',
 'Total de resultados: 117368',
 'Total de resultados: 147991',
 'Total de resultados: 22007',
 'Total de resultados: 270279',
 'Total de resultados: 27655',
 'Total de resultados: 2817',
 'Total de resultados: 2841',
 'Total de resultados: 30036',
 'Total de resultados: 3022',
 'Total de resultados: 3255',
 'Total de resultados: 3704',
 'Total de resultados: 40644',
 'Total de resultados: 45536',
 'Total de resultados: 47795',
 'Total de resultados: 50386',
 'Total de resultados: 5131',
 'Total de resultados: 5147',
 'Total de resultados: 5418',
 'Total de resultados: 5680',
 'Total de resultados: 6153',
 'Total de resultados: 6493',
 'Total de resultados: 6613',
 'Total de resultados: 67177',
 'Total de resultados: 69844',
 'Total de resultados: 70798',
 'Total de resultados: 7146',
 'Total de resultados: 71849',
 'Total de resultados: 7787'}

In [ ]:
# Verificar se há test_ids na planilha final que não estão na planilha original
# deve retornar um set vazio
set_test_ids_final_df.difference(set_test_ids_raw_data)

set()

Verificando se todos os patógenos de um test_kit estão sendo testados para todos os test_id

In [32]:
PATHOGENS_TESTS = {
    'panel_21':{
        # PAINCOVI
        'FLUA_test_result',
        'FLUB_test_result',
        'VSR_test_result',
        'SC2_test_result',
        'META_test_result',
        'RINO_test_result',
        'PARA_test_result',
        'ADENO_test_result',
        'COVS_test_result',
        'BAC_test_result',
    },

    'panel_24':{
        # RESPIRA
        'FLUA_test_result',
        'FLUB_test_result',
        'VSR_test_result',
        'META_test_result',
        'RINO_test_result',
        'PARA_test_result',
        'ADENO_test_result',
        'BOCA_test_result',
        'COVS_test_result',
        'ENTERO_test_result',
        'BAC_test_result',
    },

    'flu_antigen':{
        'FLUA_test_result',
        'FLUB_test_result',
    },

    'covid_antigen':{
        'SC2_test_result',
    },

    'covid_pcr':{
        'SC2_test_result',
    },
}

In [33]:
# Mapeando Pos e Neg para Tes
df_combined_test_pathogen_non_nt_on_kit = (
    df_combined
    .replace(('Pos', 'Neg'),  'Tes')
)

In [34]:
for pathogen, test_columns in PATHOGENS_TESTS.items():
    print(pathogen)
    print(
        df_combined_test_pathogen_non_nt_on_kit
        .query("test_kit == @pathogen")
        [list(test_columns)]
        .drop_duplicates().T
        # Deve resultar em apenas uma linha completa por 'Tes'
    )

    print('\n\n')

panel_21
Empty DataFrame
Columns: []
Index: [FLUB_test_result, PARA_test_result, BAC_test_result, COVS_test_result, META_test_result, VSR_test_result, ADENO_test_result, RINO_test_result, FLUA_test_result, SC2_test_result]



panel_24
Empty DataFrame
Columns: []
Index: [FLUB_test_result, PARA_test_result, ENTERO_test_result, BAC_test_result, COVS_test_result, META_test_result, VSR_test_result, ADENO_test_result, BOCA_test_result, RINO_test_result, FLUA_test_result]



flu_antigen
Empty DataFrame
Columns: []
Index: [FLUB_test_result, FLUA_test_result]



covid_antigen
Empty DataFrame
Columns: []
Index: [SC2_test_result]



covid_pcr
                1929
SC2_test_result  Tes

Verificando resultados de alguns testes

In [35]:
import numpy as np

In [51]:
np.random.seed(214)

ids = np.random.choice(df_combined['test_id'], 100)
test_columns = [col for col in df_combined.columns if col.endswith('_result')]

In [52]:
current_id=50

In [78]:
current_id = current_id+1
id = ids[current_id]
print( df_combined.query("test_id == @id")[['test_id', 'test_kit'] + test_columns].T )
print( df_hla_covid.query(f"Pedido == '{id}'") [['Pedido'] + [col for col in df_hla_covid.columns if col.startswith('Vírus')]].T )
print( df_hla_ctn.query(f"Pedido == '{id}'") [['Pedido', 'Resultado']].T )
print( df_hla_flu.query(f"Pedido == '{id}'") [['Pedido']+ [col for col in df_hla_flu.columns if col.startswith('VIRUS') or col.startswith('BAC')]].T )
print( df_hla_ph4.query(f"Pedido == '{id}'") [['Pedido']+ [col for col in df_hla_ph4.columns if col.startswith('VIRUS') or col.startswith('BAC')]].T )

                         7665
test_id               2262865
test_kit            covid_pcr
FLUA_test_result           NT
FLUB_test_result           NT
VSR_test_result            NT
SC2_test_result           Neg
META_test_result           NT
RINO_test_result           NT
PARA_test_result           NT
ADENO_test_result          NT
BOCA_test_result           NT
COVS_test_result           NT
ENTERO_test_result         NT
BAC_test_result            NT
Empty DataFrame
Columns: []
Index: [Pedido, Vírus Influenza A, Vírus Influenza B, Vírus Sincicial Respiratório A/B]
                   1912
Pedido          2262865
Resultado  Inconclusivo
Empty DataFrame
Columns: []
Index: [Pedido, VIRUS_Influenza A, VIRUS_Influenza H1N1, VIRUS_Influenza H3, VIRUS_Influenza B, VIRUS_Metapneumovírus, VIRUS_Sincicial A, VIRUS_Sincicial B, VIRUS_Rinovírus, VIRUS_Parainfluenza 1, VIRUS_Parainfluenza 2, VIRUS_Parainfluenza 3, VIRUS_Parainfluenza 4, VIRUS_Adenovirus, VIRUS_Bocavirus, VIRUS_CoV-229E, VIRUS_CoV-HKU, VIRUS_CoV-NL63, VIRUS_CoV-OC43, VIRUS_SARS_Like, VIRUS_SARS-CoV-2, VIRUS_Enterovírus, BACTE_Bordetella pertussis, BACTE_Bordetella parapertussis, BACTE_Mycoplasma pneumoniae]
Empty DataFrame
Columns: []
Index: [Pedido, VIRUS_IA, VIRUS_H1N1, VIRUS_AH3, VIRUS_B, VIRUS_MH, VIRUS_SA, VIRUS_SB, VIRUS_RH, VIRUS_PH, VIRUS_PH2, VIRUS_PH3, VIRUS_PH4, VIRUS_ADE, VIRUS_BOC, VIRUS_229E, VIRUS_HKU, VIRUS_NL63, VIRUS_OC43, VIRUS_SARS, VIRUS_COV2, VIRUS_EV, BACTE_BP, BACTE_BPAR, BACTE_MP]

Verificando resultados de alguns testes - Fltrando por test_kit

In [84]:
np.random.seed(214)

ids = np.random.choice(df_combined.query("test_kit not in ('covid_pcr', 'covid_antigen')")['test_id'], 100)
test_columns = [col for col in df_combined.columns if col.endswith('_result')]

In [85]:
current_id=50

In [107]:
current_id = current_id+1
id = ids[current_id]
print( df_combined.query("test_id == @id")[['test_id', 'test_kit'] + test_columns].T )
print( df_hla_covid.query(f"Pedido == '{id}'") [['Pedido'] + [col for col in df_hla_covid.columns if col.startswith(('Vírus', 'Coron'))]].T )
print( df_hla_flu.query(f"Pedido == '{id}'") [['Pedido']+ [col for col in df_hla_flu.columns if col.startswith('VIRUS') or col.startswith('BAC')]].T )
print( df_hla_ph4.query(f"Pedido == '{id}'") [['Pedido']+ [col for col in df_hla_ph4.columns if col.startswith('VIRUS') or col.startswith('BAC')]].T )

                      50943
test_id             2354190
test_kit             test_4
FLUA_test_result        Neg
FLUB_test_result        Neg
VSR_test_result         Pos
SC2_test_result         Neg
META_test_result         NT
RINO_test_result         NT
PARA_test_result         NT
ADENO_test_result        NT
BOCA_test_result         NT
COVS_test_result         NT
ENTERO_test_result       NT
BAC_test_result          NT
                                             18
Pedido                                  2354190
Vírus Influenza A                 Não Detectado
Vírus Influenza B                 Não Detectado
Vírus Sincicial Respiratório A/B      Detectado
Coronavírus SARS-CoV-2            Não Detectado
Empty DataFrame
Columns: []
Index: [Pedido, VIRUS_Influenza A, VIRUS_Influenza H1N1, VIRUS_Influenza H3, VIRUS_Influenza B, VIRUS_Metapneumovírus, VIRUS_Sincicial A, VIRUS_Sincicial B, VIRUS_Rinovírus, VIRUS_Parainfluenza 1, VIRUS_Parainfluenza 2, VIRUS_Parainfluenza 3, VIRUS_Parainfluenza 4, VIRUS_Adenovirus, VIRUS_Bocavirus, VIRUS_CoV-229E, VIRUS_CoV-HKU, VIRUS_CoV-NL63, VIRUS_CoV-OC43, VIRUS_SARS_Like, VIRUS_SARS-CoV-2, VIRUS_Enterovírus, BACTE_Bordetella pertussis, BACTE_Bordetella parapertussis, BACTE_Mycoplasma pneumoniae]
Empty DataFrame
Columns: []
Index: [Pedido, VIRUS_IA, VIRUS_H1N1, VIRUS_AH3, VIRUS_B, VIRUS_MH, VIRUS_SA, VIRUS_SB, VIRUS_RH, VIRUS_PH, VIRUS_PH2, VIRUS_PH3, VIRUS_PH4, VIRUS_ADE, VIRUS_BOC, VIRUS_229E, VIRUS_HKU, VIRUS_NL63, VIRUS_OC43, VIRUS_SARS, VIRUS_COV2, VIRUS_EV, BACTE_BP, BACTE_BPAR, BACTE_MP]