python scripts/reformat_einstein.py --datadir data --rename data/rename_columns.xlsx --correction data/fix_values.xlsx --output combined_test_einstein.tsv

In [1]:
import pandas as pd

In [2]:
df_combined = pd.read_csv('../combined_test_einstein.tsv', sep='\t')

In [3]:
df_combined['state'].unique()

array(['São Paulo', 'RIO DE JANEIRO', 'Goiás'], dtype=object)

In [4]:
df_combined['test_kit'].unique()

array(['covid_pcr', 'covid_antigen', 'test_3', 'test_2', 'test_4',
       'vsr_antigen'], dtype=object)

In [5]:
df_dict = pd.read_excel(
    './../data/EINSTEIN/20230814_Dados_Epidemiologicos_Semanais_ITpS_SE32.xlsx', 
    index_col=None, header=0, 
    sheet_name=None, 
    dtype='str'
)

dfs_paineis = []
for sheet in df_dict.keys():
    if sheet.startswith('EXAME'):
        # einstein
        continue    
    dfs_paineis.append(df_dict[sheet].assign(ExcelSheet=sheet))

df_paineis = pd.concat(dfs_paineis, ignore_index=True)

In [6]:
df_paineis['ACCESSION'] = df_paineis['ACCESSION'].astype(int)

## Duplicatas

Duplicates no sample_id

In [7]:
(
    df_combined[['sample_id']]
    .assign( duplicated = df_combined.duplicated(subset=['sample_id']))
    .query('duplicated == True')
)

Empty DataFrame
Columns: [sample_id, duplicated]
Index: []

Duplicates no test_id

In [8]:
df_duplicates = (
    df_combined
    # .query("test_kit == 'unknown'")
    .assign( one=1 )
    .groupby(['test_id'])
    .agg(num_duplicates=('one', 'sum'))
    .query("num_duplicates > 1")
    .assign(num_duplicates=lambda x: x['num_duplicates']-1)
)


print( df_duplicates['num_duplicates'].sum(), df_duplicates['num_duplicates'].max(), df_duplicates['num_duplicates'].min() )
df_duplicates.sort_values('num_duplicates', ascending=False).head(10)

241454 7 1

               num_duplicates
test_id
2022082011929               7
2022102013848               7
2022274007730               7
2022243009341               7
2022054009352               7
2022332004751               7
2022017006199               7
2022127002379               7
2022013011347               7
2023213007683               7

In [9]:
df_multiple_tests = (
    df_combined
    .groupby('test_id')
    .agg(kits=('test_kit',lambda x: ','.join(x.tolist())))
    .query("kits.str.contains(',')", engine='python') 
)

In [10]:
df_multiple_tests.head(10)

                               kits
test_id
2022001000793  test_3,test_3,test_3
2022001000846         test_2,test_2
2022001000861         test_2,test_2
2022001000869         test_2,test_2
2022001000901         test_2,test_2
2022001000930         test_2,test_2
2022001001221         test_2,test_2
2022001001238         test_2,test_2
2022001001264         test_2,test_2
2022001001298         test_2,test_2

In [11]:
df_multiple_tests['kits'].unique()

array(['test_3,test_3,test_3', 'test_2,test_2', 'covid_pcr,test_2,test_2',
       'test_2,test_2,covid_antigen', 'covid_pcr,covid_antigen',
       'covid_pcr,test_2,test_2,covid_antigen',
       'test_4,test_4,test_4,test_4,test_4', 'covid_pcr,covid_pcr',
       'covid_pcr,test_2', 'test_2,test_2,covid_pcr',
       'covid_pcr,covid_pcr,test_2,test_2',
       'covid_pcr,test_4,test_4,test_4,test_4,test_4',
       'test_4,test_4,test_4,test_4,test_4,covid_antigen',
       'covid_pcr,test_4,test_4,test_4,test_4,test_4,test_2,test_2',
       'test_4,test_4,test_4,test_4,test_4,test_2,test_2,covid_antigen',
       'test_4,test_4,test_4,test_4,test_4,covid_pcr',
       'test_4,test_4,test_4,test_4,test_4,test_2,test_2',
       'test_4,test_4,test_4,test_4,covid_pcr',
       'test_4,test_4,test_4,test_4', 'covid_pcr,vsr_antigen',
       'vsr_antigen,test_2,test_2',
       'covid_pcr,test_4,test_4,test_4,test_4',
       'test_3,test_3,test_3,test_4,test_4,test_4,test_4,test_4',
       'covid_antigen,covid_pcr',
       'test_4,test_4,test_4,test_4,test_4,vsr_antigen',
       'covid_pcr,vsr_antigen,test_2,test_2',
       'vsr_antigen,test_2,test_2,covid_antigen',
       'covid_pcr,covid_pcr,test_4,test_4,test_4,test_4,test_4',
       'covid_pcr,test_4,test_4,test_4,test_4,test_4,covid_antigen',
       'test_4,test_4', 'covid_pcr,covid_pcr,covid_antigen',
       'test_4,test_3,test_3,test_3', 'test_3,test_3,test_3,test_4',
       'test_4,test_4,test_4'], dtype=object)

In [12]:
df_combined.columns

Index(['lab_id', 'test_id', 'test_kit', 'patient_id', 'sample_id', 'state',
       'location', 'date_testing', 'epiweek', 'age', 'sex', 'FLUA_test_result',
       'Ct_FluA', 'FLUB_test_result', 'Ct_FluB', 'VSR_test_result', 'Ct_VSR',
       'SC2_test_result', 'Ct_geneE', 'Ct_geneN', 'Ct_geneS', 'Ct_ORF1ab',
       'Ct_RDRP', 'geneS_detection', 'META_test_result', 'RINO_test_result',
       'PARA_test_result', 'ADENO_test_result', 'BOCA_test_result',
       'COVS_test_result', 'ENTERO_test_result', 'BAC_test_result'],
      dtype='object')

## Uniqueness

In [13]:
if 'unknown' in df_combined['test_kit'].unique():
    print('WARNING! unknown test kits found')

df_combined['test_kit'].unique()

array(['covid_pcr', 'covid_antigen', 'test_3', 'test_2', 'test_4',
       'vsr_antigen'], dtype=object)

In [14]:
df_combined['state'].unique()

array(['São Paulo', 'RIO DE JANEIRO', 'Goiás'], dtype=object)

In [15]:
df_combined['location'].unique()

array(['GUARULHOS', 'SÃO PAULO', 'RIO DE JANEIRO', nan, 'SOROCABA',
       'GOIÂNIA'], dtype=object)

In [16]:
df_combined['date_testing'].max(), df_combined['date_testing'].min()

('2023-08-14', '2022-01-01')

In [17]:
df_combined['age'].unique(), df_combined['age'].min(), df_combined['age'].max()

(array([ 61,  53,  58,  49,  17,  56,  12,  16,  45,  26,  54,  14,  23,
         36,  48,  51,  50,  82,  59,  15,  55,  22,  35,  27,  60,  46,
          1,   3,  24,  37,  28,  42,  20,  41,  10,   8,  21,  40,   4,
         39,  34,  33,   6,  30,  87,  43,   7,  32,  38,  67,  74,  25,
         79,  65,  19,  31,  29,  11,   9,  62,  44,   2,  47,  57,  18,
         52,  84,  64,   5,  70,  75,  63,  71,  72,  77,  13,  86,  69,
         73,  68,  66,  93,  83,  80,  85,  76,  89,  94,  95,  81,  96,
         97,  88,  78,  91, 101, 100,  90,  92,  99,  98, 103, 102, 123,
        110, 104, 107, 108, 105,   0, 106, 112]),
 0,
 123)

In [18]:
df_combined['sex'].unique()

array(['M', 'F', 'I'], dtype=object)

In [19]:
for column in df_combined.columns:
    if column.endswith('_result'):
        print(column, df_combined[column].unique())

FLUA_test_result ['NT' 'Neg' 'Pos']
FLUB_test_result ['NT' 'Neg' 'Pos']
VSR_test_result ['NT' 'Neg' 'Pos']
SC2_test_result ['Neg' 'Pos' 'NT']
META_test_result ['NT']
RINO_test_result ['NT']
PARA_test_result ['NT']
ADENO_test_result ['NT']
BOCA_test_result ['NT']
COVS_test_result ['NT']
ENTERO_test_result ['NT']
BAC_test_result ['NT']

In [20]:
for col in df_combined.columns:
    if col.endswith('_result'):
        print(col)

FLUA_test_result
FLUB_test_result
VSR_test_result
SC2_test_result
META_test_result
RINO_test_result
PARA_test_result
ADENO_test_result
BOCA_test_result
COVS_test_result
ENTERO_test_result
BAC_test_result

## Inconsistencies

In [21]:
df_combined.columns

Index(['lab_id', 'test_id', 'test_kit', 'patient_id', 'sample_id', 'state',
       'location', 'date_testing', 'epiweek', 'age', 'sex', 'FLUA_test_result',
       'Ct_FluA', 'FLUB_test_result', 'Ct_FluB', 'VSR_test_result', 'Ct_VSR',
       'SC2_test_result', 'Ct_geneE', 'Ct_geneN', 'Ct_geneS', 'Ct_ORF1ab',
       'Ct_RDRP', 'geneS_detection', 'META_test_result', 'RINO_test_result',
       'PARA_test_result', 'ADENO_test_result', 'BOCA_test_result',
       'COVS_test_result', 'ENTERO_test_result', 'BAC_test_result'],
      dtype='object')

Verificando se um mesmo test_id + test_kit apresentam mais de um resultado para um mesmo patógeno

In [22]:
agg_test_rules = {
    col+'_kit': (col, lambda x: ','.join(x.tolist()))
    for col in df_combined.columns
    if col.endswith('_result')
}

df_os_non_contraditory_test_results = (
    df_combined
    .groupby(['test_id', 'test_kit'])
    .agg(**agg_test_rules)
)

In [23]:
for col in df_os_non_contraditory_test_results.columns:
    if col.endswith('_kit'):
        print(col, df_os_non_contraditory_test_results[col].unique())

# Devem ser apenas ['NT' 'Neg' 'Pos']

FLUA_test_result_kit ['NT' 'Neg,Neg,Neg' 'Pos,Pos' 'Neg,Neg' 'Pos,Pos,Pos'
 'Neg,Neg,Neg,Neg,Neg' 'NT,NT' 'Pos,Pos,Pos,Pos,Pos' 'Neg,Neg,Neg,Neg'
 'Neg']
FLUB_test_result_kit ['NT' 'Neg,Neg,Neg' 'Neg,Neg' 'Pos,Pos' 'Neg,Neg,Neg,Neg,Neg' 'NT,NT'
 'Neg' 'Neg,Neg,Neg,Neg' 'Pos,Pos,Pos' 'Pos,Pos,Pos,Pos,Pos' 'Pos'
 'NT,NT,NT']
VSR_test_result_kit ['NT' 'Neg,Neg,Neg' 'NT,NT' 'Pos,Pos,Pos' 'Neg,Neg,Neg,Neg,Neg'
 'Pos,Pos,Pos,Pos,Pos' 'Neg,Neg,Neg,Neg' 'Neg' 'Pos' 'Pos,Pos' 'NT,NT,NT']
SC2_test_result_kit ['Neg' 'Pos' 'NT,NT,NT' 'NT,NT' 'Pos,Pos,Pos,Pos,Pos' 'Pos,Pos'
 'Neg,Neg,Neg,Neg,Neg' 'NT' 'Neg,Neg' 'NT,NT,NT,NT' 'Neg,Neg,Neg,Neg'
 'Neg,Neg,Neg']
META_test_result_kit ['NT' 'NT,NT,NT' 'NT,NT' 'NT,NT,NT,NT,NT' 'NT,NT,NT,NT']
RINO_test_result_kit ['NT' 'NT,NT,NT' 'NT,NT' 'NT,NT,NT,NT,NT' 'NT,NT,NT,NT']
PARA_test_result_kit ['NT' 'NT,NT,NT' 'NT,NT' 'NT,NT,NT,NT,NT' 'NT,NT,NT,NT']
ADENO_test_result_kit ['NT' 'NT,NT,NT' 'NT,NT' 'NT,NT,NT,NT,NT' 'NT,NT,NT,NT']
BOCA_test_result_kit ['NT' 'NT,NT,NT' 'NT,NT' 'NT,NT,NT,NT,NT' 'NT,NT,NT,NT']
COVS_test_result_kit ['NT' 'NT,NT,NT' 'NT,NT' 'NT,NT,NT,NT,NT' 'NT,NT,NT,NT']
ENTERO_test_result_kit ['NT' 'NT,NT,NT' 'NT,NT' 'NT,NT,NT,NT,NT' 'NT,NT,NT,NT']
BAC_test_result_kit ['NT' 'NT,NT,NT' 'NT,NT' 'NT,NT,NT,NT,NT' 'NT,NT,NT,NT']

Verificando se todos os Ids originais etão presentes no arquivo final

In [24]:
set_test_ids_final_df = set(df_combined['test_id'])
set_test_ids_raw_data = set(df_paineis['ACCESSION'].astype(int))

In [25]:
# Testar se todos os test_ids da planilha original estão na planilha final
# PODE RETORNAR UM SET NÃO VAZIO DADO QUE OS DADOS DE DENGUE FORAM REMOVIDOS
set_test_ids_raw_data.difference(set_test_ids_final_df)

{2022297010179,
 2023122010119,
 2022197002248,
 2022197002252,
 2022090014733,
 2022133006356,
 2023182008341,
 2023186006040,
 2022129008666,
 2023124008987,
 2022108004379,
 2023134003227,
 2023132004382,
 2023153008670,
 2023087013920,
 2022326009901,
 2023122010157,
 2023072006192,
 2022357008433,
 2023006011453,
 2022320013376,
 2023087013955,
 2022330007620,
 2022206013508,
 2023134003269,
 2023097008205,
 2022042009678,
 2023167000655,
 2022150013007,
 2022266011729,
 2023097008209,
 2022073008211,
 2022127009873,
 2023033012309,
 2023031013458,
 2023159006626,
 2022351011929,
 2022133006425,
 2022106005594,
 2023178010717,
 2022150013022,
 2022032015455,
 2023097008223,
 2022365003873,
 2022206013542,
 2022085001322,
 2023136002156,
 2023093010541,
 2023199015024,
 2022181011569,
 2022355009650,
 2022179012722,
 2023037010033,
 2022146015346,
 2023134003318,
 2022069010551,
 2022363005047,
 2022264012921,
 2023058014330,
 2022162006137,
 2022146015356,
 2023184007296,
 2023087014018,
 2023126007939,
 2022243008644,
 2023143014530,
 2023116013699,
 2023116013700,
 2023116013705,
 2023091011724,
 2022112002191,
 2023172014226,
 2022127009939,
 2022137004185,
 2023182008475,
 2022096011420,
 2022077005981,
 2023018004638,
 2023058014366,
 2022293012640,
 2023190003874,
 2022191005858,
 2023118012579,
 2023031013544,
 2022038012072,
 2023078002858,
 2022191005871,
 2023091011760,
 2022067011761,
 2022278004918,
 2023039008953,
 2023058014394,
 2022131007675,
 2023174013119,
 2022071009476,
 2022195003588,
 2022197002439,
 2023091011787,
 2023134003404,
 2023014006993,
 2022208012504,
 2022320013531,
 2023126008028,
 2023035011294,
 2022005014751,
 2023145013474,
 2023186006242,
 2023066009828,
 2022208012517,
 2022013010149,
 2022123012329,
 2022135005418,
 2023091011817,
 2023097008364,
 2022063014127,
 2022365004016,
 2023076004081,
 2022245007602,
 2022079004916,
 2022278004982,
 2022063014136,
 2022073008380,
 2022067011837,
 2023149011198,
 2022293012732,
 2022007013632,
 2023184007428,
 2022034014469,
 2023041007879,
 2023151010056,
 2022210011399,
 2022243008779,
 2023010009356,
 2022131007757,
 2023199015188,
 2022069010709,
 2022272008470,
 2023205011740,
 2022125011229,
 2022152012062,
 2022127010078,
 2022125011231,
 2023010009377,
 2022241009954,
 2022075007267,
 2023207010597,
 2022135005478,
 2022011011370,
 2022216007979,
 2022129008940,
 2023035011375,
 2023087014195,
 2022299009333,
 2023020003640,
 2023095009592,
 2023149011258,
 2022154010940,
 2023145013565,
 2023207010623,
 2022098010431,
 2023093010755,
 2023010009415,
 2023151010122,
 2023122010444,
 2022003016014,
 2023039009103,
 2022102008144,
 2023172014417,
 2023087014227,
 2022067011925,
 2022210011478,
 2022353011031,
 2023126008154,
 2022195003740,
 2022349013342,
 2022266012001,
 2022235013473,
 2023022002531,
 2022152012135,
 2022320013674,
 2023062012269,
 2023180009838,
 2023058014575,
 2022127010162,
 2022241010037,
 2022210011510,
 2022154010999,
 2022262014328,
 2022081003896,
 2022208012665,
 2022322012543,
 2022191006081,
 2023031013761,
 2022011011457,
 2022235013508,
 2023134003589,
 2022071009673,
 2022071009676,
 2023022002576,
 2023035011472,
 2022135005588,
 2022241010068,
 2022046007702,
 2023201014169,
 2022127010205,
 2023118012830,
 2023174013343,
 2022106005920,
 2023014007201,
 2023143014824,
 2023093010858,
 2023209009579,
 2022090015148,
 2023207010733,
 2022131007919,
 2022152012211,
 2022094012852,
 2023217004982,
 2022210011574,
 2022338003383,
 2022114001337,
 2022189007289,
 2022264013243,
 2022264013246,
 2022237012415,
 2022094012866,
 2022003016130,
 2023190004165,
 2022098010568,
 2023041008074,
 2023076004298,
 2022131007949,
 2022021005773,
 2023022002639,
 2023118012882,
 2023172014551,
 2022179013080,
 2022131007963,
 2022361006558,
 2022266012131,
 2022005015013,
 2022129009126,
 2022040011240,
 2023149011433,
 2023116014059,
 2022365004268,
 2022046007789,
 2023089013230,
 2022096011758,
 2023116014061,
 2022046007794,
 2022189007352,
 2022320013817,
 2022067012092,
 2022075007489,
 2022208012804,
 2023145013766,
 2022050005512,
 2022007013897,
 2022332006923,
 2022152012299,
 2022079005195,
 2022208012813,
 2023219003920,
 2023219003923,
 2022299009558,
 2023060013592,
 2022067012121,
 2022328009242,
 2022328009243,
 2023060013595,
 2023097008667,
 2022098010661,
 2022293013030,
 2022179013160,
 2023035011633,
 2023041008178,
 2023089013301,
 2022243009079,
 2023116014138,
 2022330008131,
 2022146015813,
 2023157006918,
 2022139003465,
 2023105004105,
 2022125011531,
 2023134003788,
 2023089013329,
 2022353011281,
 2023039009365,
 2022071009881,
 2023151010396,
 2022168003165,
 2022264013406,
 2023066010210,
 2023087014499,
 2022079005283,
 2023143015015,
 2023182008944,
 2022023004786,
 2022208012916,
 2023128007286,
 2022357009015,
 2022179013242,
 2023132004988,
 2023128007295,
 2022210011782,
 2023116014215,
 2022181012104,
 2022363005577,
 2022017008275,
 2022079005331,
 2023172014743,
 2023190004381,
 2022189007518,
 2023172014751,
 2023159005855,
 2022071009958,
 2022146015911,
 2022208012970,
 2023126008495,
 2022067012271,
 2023037010612,
 2023097008822,
 2023180010168,
 2023101006527,
 2023178011328,
 2023153009345,
 2023205012161,
 2023128007363,
 2023116014274,
 2023087014607,
 2022210011857,
 2023093011154,
 2023022002900,
 2022353011416,
 2022299009753,
 2023066010330,
 2022133007066,
 2022309003996,
 2022129009372,
 2022046008031,
 2022007014112,
 2022293013221,
 2023153009391,
 2023178011376,
 2022334006008,
 2023101006585,
 2023205012218,
 2022123012863,
 2023031014144,
 2023149011714,
 2022141002503,
 2022042010377,
 2023122010891,
 2022094013197,
 2023068009234,
 2022187008786,
 2023035011863,
 2023143015193,
 2022154011420,
 2022154011421,
 2023093011229,
 2022266012451,
 2022027002660,
 2023093011237,
 2023126008616,
 2023070008105,
 2022135005994,
 2022326010669,
 2023205012269,
 2023010009902,
 2022363005744,
 2022125011761,
 2023060013874,
 2022094013236,
 2023041008437,
 2022264013622,
 2023045006147,
 2022363005763,
 2022299009862,
 2023010009926,
 2022071010121,
 2023031014219,
 2023143015248,
 2022320014162,
 2022079005526,
 2022102008665,
 2022181012314,
 2023012008797,
 2023213007711,
 2023134004065,
 2023107003236,
 2022187008871,
 2023045006184,
 2022158009192,
 2022123012971,
 2022123012972,
 2022135006065,
 2023095010161,
 2022135006082,
 2022067012486,
 2022123013002,
 2022069011339,
 2022069011341,
 2023022003086,
 2022326010767,
 2022264013712,
 2023172014993,
 2022075007890,
 2023122011027,
 2022042010520,
 2022135006107,
 2023118013341,
 2022272009118,
 2022133007264,
 2023215006625,
 2022266012579,
 2022218007459,
 2022282003365,
 2022146016163,
 2023087014823,
 2023145014188,
 2023087014829,
 2023116014509,
 2023062012848,
 2023093011379,
 2022139003829,
 2023037010869,
 2022079005623,
 2023143015355,
 2022129009600,
 2022243009473,
 2023037010888,
 2023014007753,
 2022272009161,
 2023159006155,
 2022127010766,
 2022160008144,
 2023159006160,
 2022293013461,
 2022330008534,
 2023172015064,
 2022276006875,
 2022127010780,
 2023078003681,
 2022125011941,
 2023060014054,
 2023039009768,
 2022079005672,
 2023134004201,
 2022096012268,
 2022179013616,
 2023182009331,
 2022357009397,
 2022021006326,
 2023078003704,
 2023116014587,
 2023041008645,
 2022127010821,
 2023010010119,
 2022071010313,
 2022094013450,
 2023010010123,
 2023033013262,
 2023180010510,
 2023151010834,
 2022299010067,
 2022326010900,
 2022208013333,
 2023172015128,
 2023178011673,
 2023180010524,
 2023105004574,
 2022344000543,
 2022322013216,
 2022083003422,
 2023118013471,
 2022162007075,
 2022131008548,
 2023207011375,
 2022127010863,
 2022320014390,
 2022328009784,
 2023190004795,
 2022021006396,
 2023087014973,
 2022073009216,
 2023010010177,
 2023037011014,
 2022237013063,
 2023078003783,
 2023169000521,
 2022330008650,
 2023172015179,
 2022185010252,
 2022162007120,
 2022243009619,
 2022125012051,
 2022185010268,
 2022251005027,
 2022328009830,
 2023136003175,
 2023116014696,
 2022135006321,
 2023006012530,
 2022131008628,
 2023172015222,
 2023093011575,
 2022075008120,
 2022096012409,
 2022237013112,
 2022042010746,
 2022322013310,
 2023196001408,
 2022322013316,
 2022102008964,
 2022154011789,
 2023190004878,
 2023062013071,
 2023037011087,
 2022069011605,
 2022011012250,
 2023118013595,
 2023076005021,
 2023143015582,
 2023205012637,
 2022003016864,
 2023153009825,
 2023041008800,
 2022266012838,
 2022127010988,
 2022264013997,
 2022150014126,
 2022085002419,
 2022361007285,
 2023128007865,
 2022067012794,
 2022154011835,
 2023174014140,
 2023134004413,
 2023078003905,
 2023095010499,
 2022123013317,
 2022197003463,
 2023006012620,
 2023041008846,
 2023066010831,
 2022301009104,
 2023184008400,
 2022322013394,
 2022185010385,
 2023145014484,
 2022005015764,
 2022133007576,
 2022081004761,
 2022241010907,
 2022127011038,
 2023136003296,
 2023095010534,
 2022106006764,
 2022104007916,
 2022129009903,
 2022158009584,
 2022361007344,
 2022274008304,
 2022127011059,
 2023033013493,
 2023095010551,
 2022330008825,
 2022162007290,
 2022135006462,
 2023039010048,
 2023151011074,
 2022125012229,
 2023033013520,
 2023070008592,
 2022079005970,
 2022125012248,
 2023128007966,
 2023078003999,
 2023014008096,
 2022007014690,
 2023087015204,
 2023105004837,
 2022106006820,
 2022106006823,
 2022158009642,
 2022214010154,
 2023095010603,
 2023089014061,
 2022129009966,
 2022079005995,
 2023143015728,
 2023209010486,
 2022017008951,
 2023049004350,
 2023124010304,
 2023184008512,
 2023060014406,
 2022330008904,
 2023153009996,
 2022226003277,
 2022179013966,
 2023078004050,
 2022305006932,
 2022322013525,
 2023116014934,
 2023182009687,
 2023207011672,
 2022338004312,
 2023221003606,
 2023178011993,
 2023089014108,
 2023207011677,
 2022129010014,
 2023109002591,
 2023095010652,
 2022129010021,
 2023145014630,
 2022264014183,
 2022023005543,
 2022129010024,
 2023078004069,
 2022214010219,
 2022007014765,
 2023134004591,
 2022282003826,
 2022309004660,
 2023049004408,
 2023074006396,
 2022274008449,
 2022077007234,
 2023066011011,
 2023132005764,
 2023062013315,
 2022305006979,
 2022131008900,
 2023145014660,
 2022228002184,
 2022264014221,
 2023014008206,
 2022073009551,
 2022322013581,
 2023072007572,
 2023080002965,
 2023010010521,
 2023180010911,
 2022334006688,
 2022282003872,
 2023078004128,
 2023194002851,
 2022075008420,
 2023089014180,
 2022023005604,
 2022172001701,
 2023194002856,
 2022266013096,
 2023126009258,
 2022129010089,
 2022129010101,
 2023126009270,
 2022284002743,
 2023128008123,
 2022179014080,
 2022114002369,
 2023190005188,
 2023012009414,
 2023124010443,
 2023143015883,
 2022150014414,
 2023174014416,
 2023018005971,
 2022075008469,
 2023128008150,
 2022096012758,
 2022301009368,
 2022106007007,
 2022179014113,
 2023101007329,
 2023149012452,
 2023209010661,
 2023062013415,
 2023205012974,
 2022096012787,
 2022067013113,
 2023134004729,
 2023078004219,
 2023022003711,
 2022249006591,
 2022069011970,
 2023153010180,
 2022135006725,
 2022305007109,
 2023072007686,
 2023093011973,
 2022282003977,
 2022123013636,
 2023130007051,
 2023180011022,
 2022197003793,
 2022096012820,
 2023089014298,
 2022264014363,
 2023053002274,
 2023180011048,
 2023180011049,
 2022034015784,
 2022170002990,
 2022297011765,
 2023089014328,
 2022135006777,
 2023126009400,
 2022154012219,
 2022129010235,
 2023186007613,
 2023062013502,
 2023159006780,
 2022135006784,
 2023072007745,
 2022096012866,
 2023134004794,
 2022307006020,
 2023060014661,
 2022123013703,
 2023039010377,
 2022114002507,
 2023145014866,
 2022125012565,
 2022338004565,
 2022154012251,
 2022071010908,
 2023122011744,
 2022181013089,
 2023124010595,
 2023205013092,
 2023014008429,
 2023095010927,
 2022071010929,
 2023128008312,
 2022266013308,
 2023157007999,
 2023089014400,
 2022131009152,
 2023078004352,
 2023207011969,
 2022106007170,
 2023107004040,
 2023151011465,
 2023145014924,
 2022361007761,
 2023128008338,
 2022129010324,
 2022322013854,
 2022135006883,
 2023078004388,
 2022123013796,
 2022301009574,
 2023066011303,
 2022071010985,
 2023113000622,
 2022069012151,
 2022019008184,
 2022322013882,
 2022152013501,
 2023149012671,
 2022185010879,
 2022172001986,
 2022282004168,
 2023053002443,
 2023039010508,
 2023089014478,
 2023062013647,
 2022322013907,
 2023089014487,
 2022299010779,
 2022017009374,
 2022127011551,
 2022131009248,
 2023128008417,
 2023041009378,
 2022129010401,
 2023184008928,
 2023014008551,
 2022338004712,
 2022129010415,
 2022150014704,
 2023111001842,
 2022046009074,
 2022237013748,
 2022129010418,
 2022326011641,
 2022137005818,
 2022017009404,
 2022313002752,
 2023124010753,
 2022023005958,
 2022189008647,
 2023124010763,
 2023095011086,
 2022017009424,
 2022071011090,
 2023068010263,
 2022162007831,
 2023014008606,
 2023045007141,
 2022322013990,
 2022264014632,
 2022363006762,
 2022193006379,
 2022106007341,
 2022241011504,
 2022015010609,
 2022272010038,
 2023213008697,
 2023066011450,
 2023022004026,
 2022301009723,
 2022322014011,
 2022181013312,
 2022282004288,
 2022029002562,
 2023051003717,
 2022322014024,
 2022305007436,
 2023095011149,
 2023217006417,
 2023060014931,
 2022301009753,
 2022123013981,
 2022096013151,
 2022154012513,
 2022071011171,
 2022135007077,
 2022185011049,
 2022135007083,
 2022135007085,
 2022102009713,
 2023151011701,
 2022353012600,
 2023190005626,
 2022152013690,
 2022125012858,
 2023051003772,
 2023078004610,
 2023022004103,
 2022353012615,
 2022131009415,
 2023060014983,
 2023020005259,
 2023124010888,
 2023174014861,
 2023124010889,
 2022280005512,
 2023095011210,
 2022272010120,
 2022034016138,
 2022199003027,
 2022152013720,
 2022073010080,
 2023205013409,
 2022361008034,
 2022127011747,
 2023124010917,
 2022214010789,
 2022266013607,
 2023041009576,
 2022187009957,
 2023213008809,
 2023174014895,
 2023126009775,
 2023126009783,
 2022096013240,
 2023039010744,
 2022363006904,
 2022073010107,
 2022133008316,
 2022129010625,
 2022166005697,
 2023089014723,
 2022355011528,
 2022013011914,
 2023132006348,
 2022162008015,
 2023124010963,
 2022220007382,
 2023060015062,
 2023074007000,
 2022313002969,
 2022023006172,
 2023122012125,
 2022170003422,
 2022326011875,
 2022249007083,
 2023095011311,
 2023093012470,
 2022185011191,
 2022214010873,
 2022282004474,
 2022069012475,
 2022152013821,
 2022073010177,
 2022218008577,
 2023190005764,
 2022355011593,
 2023039010829,
 2023020005390,
 2022185011215,
 2023134005262,
 2023161006097,
 2022089000979,
 2023066011671,
 2022218008605,
 2022357010461,
 2022123014175,
 2022125013025,
 2022353012770,
 2023041009699,
 2022017009700,
 2022102009891,
 2023178012708,
 2023153010727,
 2022353012775,
 2022332008490,
 2023151011882,
 2023134005305,
 2022342002750,
 2023093012548,
 2023159007301,
 2023024003144,
 2022052005960,
 2022272010312,
 2023060015181,
 2023089014862,
 2022218008654,
 2022096013392,
 2022218008655,
 2023132006489,
 2023074007130,
 2022162008160,
 2022073010277,
 2022106007654,
 2023107004521,
 2022152013929,
 2023209011310,
 2023209011311,
 2023165003886,
 2023209011313,
 2023080003698,
 2022069012595,
 2023209011314,
 2023209011316,
 2023209011317,
 2023209011319,
 2023209011320,
 2023095011442,
 2023089014907,
 2022361008259,
 2023089014917,
 2022338005131,
 2022353012877,
 2023095011470,
 2022114003087,
 2022152013967,
 2022075009175,
 2023089014936,
 2023022004376,
 2022096013466,
 2023126010008,
 2023107004572,
 2023130007710,
 2022266013858,
 2022150015139,
 2023180011683,
 2022307006629,
 2023188007077,
 2023080003749,
 2022307006632,
 2023028000934,
 2022185011364,
 2023190005932,
 2022106007725,
 2022251006127,
 2022332008625,
 2022338005169,
 2023136004275,
 2022038014132,
 2023126010037,
 2022193006782,
 2022131009727,
 2023126010048,
 2022110005441,
 2022245009602,
 2022189009090,
 2023047006412,
 2022152014029,
 2023159007453,
 2022328010974,
 2022133008607,
 2022133008608,
 ...}

In [26]:
# Verificar se há test_ids na planilha final que não estão na planilha original
# deve retornar um set vazio
set_test_ids_final_df.difference(set_test_ids_raw_data)

set()

Verificando se todos os patógenos de um test_kit estão sendo testados para todos os test_id

In [27]:
PATHOGENS_TESTS = {
    'panel_21':{
        # PAINCOVI
        'FLUA_test_result',
        'FLUB_test_result',
        'VSR_test_result',
        'SC2_test_result',
        'META_test_result',
        'RINO_test_result',
        'PARA_test_result',
        'ADENO_test_result',
        'COVS_test_result',
        'BAC_test_result',
    },

    'panel_24':{
        # RESPIRA
        'FLUA_test_result',
        'FLUB_test_result',
        'VSR_test_result',
        'META_test_result',
        'RINO_test_result',
        'PARA_test_result',
        'ADENO_test_result',
        'BOCA_test_result',
        'COVS_test_result',
        'ENTERO_test_result',
        'BAC_test_result',
    },

    'panel_4':{
        # PCRESPSL & PCRVRESP
        'FLUA_test_result',
        'FLUB_test_result',
        'VSR_test_result',
        'SC2_test_result',
    },

    'covid_antigen':{
        'SC2_test_result',
    },

    'covid_pcr':{
        'SC2_test_result',
    },
}

In [28]:
# Mapeando Pos e Neg para Tes
df_combined_test_pathogen_non_nt_on_kit = (
    df_combined
    .replace(('Pos', 'Neg'),  'Tes')
)

In [29]:
for pathogen, test_columns in PATHOGENS_TESTS.items():
    print(pathogen)
    print(
        df_combined_test_pathogen_non_nt_on_kit
        .query("test_kit == @pathogen")
        [list(test_columns)]
        .drop_duplicates().T
        # Deve resultar em apenas uma linha completa por 'Tes'
    )

    print('\n\n')

panel_21
Empty DataFrame
Columns: []
Index: [FLUA_test_result, RINO_test_result, META_test_result, SC2_test_result, BAC_test_result, COVS_test_result, FLUB_test_result, PARA_test_result, ADENO_test_result, VSR_test_result]



panel_24
Empty DataFrame
Columns: []
Index: [FLUA_test_result, RINO_test_result, META_test_result, ENTERO_test_result, BAC_test_result, COVS_test_result, FLUB_test_result, PARA_test_result, ADENO_test_result, BOCA_test_result, VSR_test_result]



panel_4
Empty DataFrame
Columns: []
Index: [FLUA_test_result, VSR_test_result, FLUB_test_result, SC2_test_result]



covid_antigen
                  10
SC2_test_result  Tes



covid_pcr
                   0
SC2_test_result  Tes

Verificando resultados de alguns testes

In [30]:
import numpy as np

In [31]:
np.random.seed(214)

ids = np.random.choice(df_combined['test_id'], 100)
test_columns = [col for col in df_combined.columns if col.endswith('_result')]

In [32]:
current_id=50

In [33]:
current_id = current_id+1
id = ids[current_id]
id = 2023138006519
print( df_combined.query("test_id == @id")[['test_id', 'test_kit'] + test_columns].T )
print( df_paineis.query("ACCESSION == @id") [['ACCESSION', 'EXAME', 'DETALHE_EXAME', 'RESULTADO']].T )

                           630575         630576         630577  \
test_id             2023138006519  2023138006519  2023138006519
test_kit                   test_4         test_4         test_4
FLUA_test_result              Neg            Neg            Neg
FLUB_test_result              Neg            Neg            Neg
VSR_test_result               Neg            Neg            Neg
SC2_test_result               Neg            Neg            Neg
META_test_result               NT             NT             NT
RINO_test_result               NT             NT             NT
PARA_test_result               NT             NT             NT
ADENO_test_result              NT             NT             NT
BOCA_test_result               NT             NT             NT
COVS_test_result               NT             NT             NT
ENTERO_test_result             NT             NT             NT
BAC_test_result                NT             NT             NT

                           630578         630579
test_id             2023138006519  2023138006519
test_kit                   test_4         test_4
FLUA_test_result              Neg            Neg
FLUB_test_result              Neg            Neg
VSR_test_result               Neg            Neg
SC2_test_result               Neg            Neg
META_test_result               NT             NT
RINO_test_result               NT             NT
PARA_test_result               NT             NT
ADENO_test_result              NT             NT
BOCA_test_result               NT             NT
COVS_test_result               NT             NT
ENTERO_test_result             NT             NT
BAC_test_result                NT             NT
                                             13472   \
ACCESSION                             2023138006519
EXAME          PCR PAINEL DE PATOGENOS RESPIRATORIO
DETALHE_EXAME                                   NaN
RESULTADO                             Não Detectado

                                             467471  \
ACCESSION                             2023138006519
EXAME          PCR PAINEL DE PATOGENOS RESPIRATORIO
DETALHE_EXAME                       INF A H1N1 2009
RESULTADO                             NÃO DETECTADO

                                             467472  \
ACCESSION                             2023138006519
EXAME          PCR PAINEL DE PATOGENOS RESPIRATORIO
DETALHE_EXAME                          INFLUENZA  A
RESULTADO                             NÃO DETECTADO

                                             467473  \
ACCESSION                             2023138006519
EXAME          PCR PAINEL DE PATOGENOS RESPIRATORIO
DETALHE_EXAME                          INFLUENZA  B
RESULTADO                             NÃO DETECTADO

                                             686467
ACCESSION                             2023138006519
EXAME          PCR PAINEL DE PATOGENOS RESPIRATORIO
DETALHE_EXAME          VÍRUS SINCICIAL RESPIRATÓRIO
RESULTADO                             NÃO DETECTADO

Verificando resultados de alguns testes - Fltrando por test_kit

In [34]:
np.random.seed(214)

ids = np.random.choice(df_combined.query("test_kit not in ('covid_pcr', 'covid_antigen')")['test_id'], 100)
test_columns = [col for col in df_combined.columns if col.endswith('_result')]

In [35]:
current_id=0

In [36]:
current_id = current_id+1
id = ids[current_id]
print( df_combined.query("test_id == @id")[['test_id', 'test_kit'] + test_columns].T )
print( df_paineis.query("ACCESSION == @id") [['ACCESSION', 'EXAME', 'DETALHE_EXAME', 'RESULTADO']].T )

                            59886          59887
test_id             2022011004230  2022011004230
test_kit                   test_2         test_2
FLUA_test_result              Neg            Neg
FLUB_test_result              Neg            Neg
VSR_test_result                NT             NT
SC2_test_result                NT             NT
META_test_result               NT             NT
RINO_test_result               NT             NT
PARA_test_result               NT             NT
ADENO_test_result              NT             NT
BOCA_test_result               NT             NT
COVS_test_result               NT             NT
ENTERO_test_result             NT             NT
BAC_test_result                NT             NT
                                             661131  \
ACCESSION                             2022011004230
EXAME          PESQUISA RÁPIDA PARA INFLUENZA A E B
DETALHE_EXAME             INFLUENZA A, TESTE RÁPIDO
RESULTADO                             NÃO DETECTADO

                                             661132
ACCESSION                             2022011004230
EXAME          PESQUISA RÁPIDA PARA INFLUENZA A E B
DETALHE_EXAME            INFLUENZA B,  TESTE RÁPIDO
RESULTADO                             NÃO DETECTADO