python scripts/reformat_sabin.py --datadir data --rename data/rename_columns.xlsx --correction data/fix_values.xlsx --output combined_sabin.tsv

In [ ]:
python scripts/reformat_sabin.py --datadir data --rename data/rename_columns.xlsx --correction data/fix_values.xlsx --output combined_sabin.tsv --cache results/combined_db

In [1]:
import pandas as pd
import os
import re

def load_table(file, separator=None):
    df = ''
    if str(file).split('.')[-1] == 'tsv':
        separator = '\t' if separator is None else separator
        df = pd.read_csv(file, encoding='latin-1', sep=separator, dtype='str')
    elif str(file).split('.')[-1] == 'csv':
        separator = ',' if separator is None else separator
        df = pd.read_csv(file, encoding='latin-1', sep=separator, dtype='str')
    elif str(file).split('.')[-1] in ['xls', 'xlsx']:
        df = pd.read_excel(file, index_col=None, header=0, sheet_name=0, dtype='str')
        df.fillna('', inplace=True)
    else:
        print('Wrong file format. Compatible file formats: TSV, CSV, XLS, XLSX')
        exit()
    return df

In [5]:
df_sabin_covid = pd.read_excel(
    './../data/SABIN/20230823_SABIN_Covid_2023ateSE33.xlsx'
)

df_dict = pd.read_excel(
    './../data/SABIN/20230823_SABIN_Painel respiratorio 2023ateSE33.xlsx', 
    index_col=None, header=0, 
    sheet_name=None, 
)
df_paineis = pd.DataFrame()
for sheet in df_dict.keys():
    df_paineis = df_paineis.append(df_dict[sheet].assign(ExcelSheet=sheet))

/tmp/ipykernel_3232/1232156733.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_paineis = df_paineis.append(df_dict[sheet].assign(ExcelSheet=sheet))
/tmp/ipykernel_3232/1232156733.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_paineis = df_paineis.append(df_dict[sheet].assign(ExcelSheet=sheet))
/tmp/ipykernel_3232/1232156733.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_paineis = df_paineis.append(df_dict[sheet].assign(ExcelSheet=sheet))
/tmp/ipykernel_3232/1232156733.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_paineis = df_paineis.append(df_dict[sheet].assign(ExcelSheet=sheet))

In [141]:
df_full = pd.concat([df_sabin_covid, df_paineis], axis=0)
df_full.head()

,OS,Código Posto,Estado,Municipio,DataAtendimento,DataNascimento,Sexo,Descricao,Parametro,Resultado,DataAssinatura,ExcelSheet
0,321-66464-12445,321,DISTRITO FEDERAL,BRASÍLIA,21/12/2022,17/11/1980,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,2023-01-01 00:00:00,NaN
1,525-66472-8612,525,DISTRITO FEDERAL,BRASÍLIA,29/12/2022,26/11/1983,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,DETECTADO (Presença de RNA específico de SARS-...,2023-01-01 00:00:00,NaN
2,324-66472-9108,324,PARÁ,BELÉM,29/12/2022,21/09/1958,Masculino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,2023-01-01 00:00:00,NaN
3,891-66472-10158,891,GOIAS,ANAPOLIS,29/12/2022,17/11/2002,Masculino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,DETECTADO (Presença de RNA específico de SARS-...,2023-01-01 00:00:00,NaN
4,407-66472-10869,407,TOCANTINS,PALMAS,29/12/2022,17/09/1959,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,DETECTADO (Presença de RNA específico de SARS-...,2023-01-01 00:00:00,NaN

In [124]:
df_full.query("OS == '743-66605-21030'")

,OS,Código Posto,Estado,Municipio,DataAtendimento,DataNascimento,Sexo,Descricao,Parametro,Resultado,DataAssinatura,ExcelSheet,DataAtendimentoFixed
54789,743-66605-21030,743,DISTRITO FEDERAL,BRASÍLIA,2023-11-05 00:00:00,31/05/1979,Masculino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,DETECTADO (Presença de RNA específico de SARS-...,2023-12-05 00:00:00,NaN,2023-11-05 00:00:00

In [122]:
df_full.query("DataAtendimentoFixed > '2023-12'")

,OS,Código Posto,Estado,Municipio,DataAtendimento,DataNascimento,Sexo,Descricao,Parametro,Resultado,DataAssinatura,ExcelSheet,DataAtendimentoFixed
5795,743-66486-58,743,DISTRITO FEDERAL,BRASÍLIA,2023-12-01 00:00:00,2004-03-08 00:00:00,Feminino,DETECCAO QUALITATIVA DE ANTIGENOS DE SARS-CoV-2,COVIDECO,NÃO DETECTADO,2023-12-01 00:00:00,NaN,2023-12-01 00:00:00
5796,939-66486-135,939,DISTRITO FEDERAL,BRASÍLIA,2023-12-01 00:00:00,1994-03-05 00:00:00,Masculino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,2023-12-01 00:00:00,NaN,2023-12-01 00:00:00
5797,939-66486-150,939,DISTRITO FEDERAL,BRASÍLIA,2023-12-01 00:00:00,25/02/1962,Feminino,DETECCAO QUALITATIVA DE ANTIGENOS DE SARS-CoV-2,COVIDECO,NÃO DETECTADO,2023-12-01 00:00:00,NaN,2023-12-01 00:00:00
5798,1417-66486-158,1417,DISTRITO FEDERAL,BRASÍLIA,2023-12-01 00:00:00,22/06/1982,Feminino,TESTE MOLECULAR PARA SARS-CoV-2 (COVID 19) COM...,TMR19RES1,DETECTADO (Presença de RNA específico de SARS-...,2023-12-01 00:00:00,NaN,2023-12-01 00:00:00
5799,013-66486-691,13,DISTRITO FEDERAL,BRASÍLIA,2023-12-01 00:00:00,18/09/1971,Masculino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,2023-12-01 00:00:00,NaN,2023-12-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11390,791-66698-13475,791,MINAS GERAIS,UBERLANDIA,2023-12-08 00:00:00,25/06/2023,Masculino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",PCRVRESPBM4,NÃO DETECTADO (Ausência de RNA viral específico),16/08/2023,PCRVRESP,2023-12-08 00:00:00
11391,791-66698-13475,791,MINAS GERAIS,UBERLANDIA,2023-12-08 00:00:00,25/06/2023,Masculino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",PCRVRESP,NÃO DETECTADO (Ausência de RNA viral específico),16/08/2023,PCRVRESP,2023-12-08 00:00:00
11392,791-66698-13475,791,MINAS GERAIS,UBERLANDIA,2023-12-08 00:00:00,25/06/2023,Masculino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",GENES,NÃO DETECTADO,16/08/2023,PCRVRESP,2023-12-08 00:00:00
11393,791-66698-13475,791,MINAS GERAIS,UBERLANDIA,2023-12-08 00:00:00,25/06/2023,Masculino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",GENERDRP,NÃO DETECTADO,16/08/2023,PCRVRESP,2023-12-08 00:00:00
11394,791-66698-13475,791,MINAS GERAIS,UBERLANDIA,2023-12-08 00:00:00,25/06/2023,Masculino,"PAINEL PARA VÍRUS SARS-CoV-2, INFLUENZA A, B E...",GENEN,NÃO DETECTADO,16/08/2023,PCRVRESP,2023-12-08 00:00:00

Data Sabin

Análise do arquivo - 20230823_SABIN_Painel respiratorio 2023ateSE33.xlsx

se a gente considera xxxx-xx-xx como yyyy-mm-dd, então dá problema de data futura

se a gente considera xxxx-xx-xx como dd-mm-yyyy, então dá problema de 'shift' nos dados

In [78]:
import re

In [85]:
df_paineis.head()[['OS','DataAtendimento', 'ExcelSheet']]

               OS      DataAtendimento ExcelSheet
0  565-66476-5360  2023-02-01 00:00:00   PAINCOVI
1  565-66476-5360  2023-02-01 00:00:00   PAINCOVI
2  565-66476-5360  2023-02-01 00:00:00   PAINCOVI
3  565-66476-5360  2023-02-01 00:00:00   PAINCOVI
4  565-66476-5360  2023-02-01 00:00:00   PAINCOVI

In [13]:
# ajuste técinico
df_combined_sabin = pd.read_csv('../combined_sabin.tsv', sep='\t')
df_combined_sabin_snakemake = pd.read_csv('../results/combined_sabin.tsv', sep='\t')

/tmp/ipykernel_2942/3932633123.py:3: DtypeWarning: Columns (1,10,23) have mixed types. Specify dtype option on import or set low_memory=False.
  df_combined_sabin_snakemake = pd.read_csv('../results/combined_sabin.tsv', sep='\t')

## Duplicatas

In [3]:
df_duplicates = (
    df_combined
    .assign( one=1 )
    .groupby(['sample_id'])
    .agg(num_duplicates=('one', 'sum'))
    .query("num_duplicates > 1")
    .assign(num_duplicates=lambda x: x['num_duplicates']-1)
)


print( df_duplicates['num_duplicates'].sum(), df_duplicates['num_duplicates'].max(), df_duplicates['num_duplicates'].min() )
df_duplicates.sort_values('num_duplicates', ascending=False).head(10)

0 nan nan

Empty DataFrame
Columns: [num_duplicates]
Index: []

In [4]:
df_duplicates = (
    df_combined
    # .query("test_kit == 'unknown'")
    .assign( one=1 )
    .groupby(['test_id'])
    .agg(num_duplicates=('one', 'sum'))
    .query("num_duplicates > 1")
    .assign(num_duplicates=lambda x: x['num_duplicates']-1)
)


print( df_duplicates['num_duplicates'].sum(), df_duplicates['num_duplicates'].max(), df_duplicates['num_duplicates'].min() )
df_duplicates.sort_values('num_duplicates', ascending=False).head(10)

2378 1 1

                 num_duplicates
test_id
001-66156-14273               1
463-66562-17592               1
463-66667-16115               1
466-66434-18608               1
466-66434-18901               1
466-66639-18951               1
474-66173-8412                1
474-66268-14113               1
482-66154-19237               1
482-66549-15690               1

In [20]:
df_os_multiple_tests = (
    df_combined
    .groupby('test_id')
    .agg(kits=('test_kit',lambda x: ','.join(x.tolist())))
    .query("kits.str.contains(',')", engine='python') 
)

In [21]:
df_os_multiple_tests.head(10)

                                    kits
test_id
001-66156-14273  covid_antigen,covid_pcr
001-66156-14280  covid_antigen,covid_pcr
001-66156-14376  covid_antigen,covid_pcr
001-66166-12255  covid_antigen,covid_pcr
001-66266-18643  covid_antigen,covid_pcr
001-66270-16315  covid_antigen,covid_pcr
001-66272-1706   covid_antigen,covid_pcr
001-66276-5891   covid_antigen,covid_pcr
001-66289-7819   covid_antigen,covid_pcr
001-66294-20437  covid_antigen,covid_pcr

In [22]:
df_combined.columns

Index(['lab_id', 'test_id', 'test_kit', 'patient_id', 'sample_id', 'state',
       'location', 'date_testing', 'epiweek', 'age', 'sex', 'FLUA_test_result',
       'Ct_FluA', 'FLUB_test_result', 'Ct_FluB', 'VSR_test_result', 'Ct_VSR',
       'SC2_test_result', 'Ct_geneE', 'Ct_geneN', 'Ct_geneS', 'Ct_ORF1ab',
       'Ct_RDRP', 'geneS_detection', 'META_test_result', 'RINO_test_result',
       'PARA_test_result', 'ADENO_test_result', 'BOCA_test_result',
       'COVS_test_result', 'ENTERO_test_result', 'BAC_test_result'],
      dtype='object')

## Uniqueness

In [5]:
if 'unknown' in df_combined['test_kit'].unique():
    print('WARNING! unknown test kits found')

df_combined['test_kit'].unique()

array(['covid_pcr', 'covid_antigen', 'test_4', 'test_21', 'test_24'],
      dtype=object)

In [6]:
df_combined['state'].unique()

array(['Distrito Federal', 'Bahia', 'Goiás', 'São Paulo', 'Minas Gerais',
       'Paraná', 'Mato Grosso do Sul', 'Tocantins', 'Roraima', nan,
       'Amazonas', 'Santa Catarina', 'Pará', 'Mato Grosso'], dtype=object)

In [7]:
df_combined['location'].unique()

array(['BRASÍLIA', 'BARREIRAS', 'FORMOSA', 'RIBEIRÃO PRETO', 'UBERLANDIA',
       'MARINGA', 'RIO DE JANEIRO', 'UBERABA', 'DOURADOS', 'PALMAS',
       'BOA VISTA', 'LONDRINA', 'CAMPINAS', nan, 'SALVADOR', 'MANAUS',
       'FLORIANOPOLIS', 'ANAPOLIS', 'SAO CAETANO', 'BELÉM',
       'SÃO JOSE DOS CAMPOS', 'CUIABA', 'LUZIANIA', 'TANGARA DA SERRA',
       'VINHEDO', 'CRISTALINA', 'PLANALTINA', 'PADRE BERNARDO',
       'SANTO ANTÔNIO DO DESCOBERTO'], dtype=object)

In [8]:
df_combined['date_testing'].max(), df_combined['date_testing'].min()

('2023-08-20', '2020-01-11')

In [9]:
df_combined['age'].unique(), df_combined['age'].min(), df_combined['age'].max()

(array([ 64,   4,  39,  38,  41,  56,  25,  67,  36,  88,  47,  40,  26,
         44,   3,  62,  31,  32,  23,  42,  71,  37,  74,  51,  52,  35,
         77,  10,  50,  78,  34,  43,  80,  29,  18,   6,   1,  76,  85,
         14,  19,  48,  61,  17,  13,  24,  59,  55,  63,  73,  58,  27,
         72,  57,  30,  65,  33,  46,  28,  60,  16,  53,  45,   8,  22,
         49,  79,  15,  20,  54,  21,  66,  68,  90,  69,  83,   2,   5,
         12,  86,  11,   7,   9,  75,  87,  91,  70,   0,  82,  95,  97,
         84,  81,  93, 100,  89,  92,  94,  99,  96,  98, 102, 103, 101,
        106, 122, 123, 105, 104, 128,  -1, 136, 107]),
 -1,
 136)

In [10]:
df_combined['sex'].unique()

array(['M', 'F', 'N', 'I', nan], dtype=object)

In [11]:
for column in df_combined.columns:
    if column.endswith('_result'):
        print(column, df_combined[column].unique())

FLUA_test_result ['NT' 'Neg' 'Pos']
FLUB_test_result ['NT' 'Neg' 'Pos']
VSR_test_result ['NT' 'Neg' 'Pos']
SC2_test_result ['Neg' 'Pos' 'NT']
META_test_result ['NT' 'Neg' 'Pos']
RINO_test_result ['NT' 'Neg' 'Pos']
PARA_test_result ['NT' 'Neg' 'Pos']
ADENO_test_result ['NT' 'Neg' 'Pos']
BOCA_test_result ['NT' 'Neg' 'Pos']
COVS_test_result ['NT' 'Neg' 'Pos']
ENTERO_test_result ['NT' 'Neg' 'Pos']
BAC_test_result ['NT' 'Neg' 'Pos']

In [12]:
for col in df_combined.columns:
    if col.endswith('_result'):
        print(col)

FLUA_test_result
FLUB_test_result
VSR_test_result
SC2_test_result
META_test_result
RINO_test_result
PARA_test_result
ADENO_test_result
BOCA_test_result
COVS_test_result
ENTERO_test_result
BAC_test_result

## Inconsistencies

In [23]:
df_combined.columns

Index(['lab_id', 'test_id', 'test_kit', 'patient_id', 'sample_id', 'state',
       'location', 'date_testing', 'epiweek', 'age', 'sex', 'FLUA_test_result',
       'Ct_FluA', 'FLUB_test_result', 'Ct_FluB', 'VSR_test_result', 'Ct_VSR',
       'SC2_test_result', 'Ct_geneE', 'Ct_geneN', 'Ct_geneS', 'Ct_ORF1ab',
       'Ct_RDRP', 'geneS_detection', 'META_test_result', 'RINO_test_result',
       'PARA_test_result', 'ADENO_test_result', 'BOCA_test_result',
       'COVS_test_result', 'ENTERO_test_result', 'BAC_test_result'],
      dtype='object')

Verificando se um mesmo test_id + test_kit apresentam mais de um resultado para um mesmo patógeno

In [24]:
agg_test_rules = {
    col+'_kit': (col, lambda x: ','.join(x.tolist()))
    for col in df_combined.columns
    if col.endswith('_result')
}

df_os_non_contraditory_test_results = (
    df_combined
    .groupby(['test_id', 'test_kit'])
    .agg(**agg_test_rules)
)

In [25]:
for col in df_os_non_contraditory_test_results.columns:
    if col.endswith('_kit'):
        print(col, df_os_non_contraditory_test_results[col].unique())
        # Devem ser apenas ['NT' 'Neg' 'Pos']

FLUA_test_result_kit ['NT' 'Neg' 'Pos']
FLUB_test_result_kit ['NT' 'Neg' 'Pos']
VSR_test_result_kit ['NT' 'Neg' 'Pos']
SC2_test_result_kit ['Pos' 'Neg' 'NT']
META_test_result_kit ['NT' 'Neg' 'Pos']
RINO_test_result_kit ['NT' 'Neg' 'Pos']
PARA_test_result_kit ['NT' 'Neg' 'Pos']
ADENO_test_result_kit ['NT' 'Neg' 'Pos']
BOCA_test_result_kit ['NT' 'Neg' 'Pos']
COVS_test_result_kit ['NT' 'Neg' 'Pos']
ENTERO_test_result_kit ['NT' 'Neg' 'Pos']
BAC_test_result_kit ['NT' 'Neg' 'Pos']

In [26]:
df_os_non_contraditory_test_results.query("SC2_test_result_kit == 'Neg,Pos'")

Empty DataFrame
Columns: [FLUA_test_result_kit, FLUB_test_result_kit, VSR_test_result_kit, SC2_test_result_kit, META_test_result_kit, RINO_test_result_kit, PARA_test_result_kit, ADENO_test_result_kit, BOCA_test_result_kit, COVS_test_result_kit, ENTERO_test_result_kit, BAC_test_result_kit]
Index: []

In [27]:
df_os_non_contraditory_test_results.reset_index().query("test_kit == 'test_4'").query("FLUA_test_result_kit == 'Neg,Neg'")

Empty DataFrame
Columns: [test_id, test_kit, FLUA_test_result_kit, FLUB_test_result_kit, VSR_test_result_kit, SC2_test_result_kit, META_test_result_kit, RINO_test_result_kit, PARA_test_result_kit, ADENO_test_result_kit, BOCA_test_result_kit, COVS_test_result_kit, ENTERO_test_result_kit, BAC_test_result_kit]
Index: []

In [ ]:
gene_df.query("requisicao == '1002751831'")

,requisicao,data,data_de_nascimento,idade,sexo,teste,data_do_resultado,data_de_liberacao,resultado_original,cidade_norm,...,apoio_cidade,gliese_uf,dasa_uf,apoio_uf,cep_municipio,cep_uf,cep_municipio_dasa,cep_uf_dasa,cidade_tratado,uf_tratado
6158,1002751831,2022-07-13 10:33:46+00:00,1984-02-03,38,FEMININO,DETECCAO QUALITATIVA DE CORONAVIRUS (2019-NCOV),2022-07-14 00:37:50+00:00,2022-07-14 01:13:35+00:00,NDT,SAOPAULO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,1002751831,2022-10-24 10:02:24+00:00,1984-02-03,38,FEMININO,DETECCAO QUALITATIVA DE CORONAVIRUS (2019-NCOV),2022-10-25 07:43:50+00:00,NaN,NaN,SAOPAULO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_combined.query("test_id == '279800084151'")

,lab_id,test_id,test_kit,patient_id,sample_id,state,location,date_testing,epiweek,age,...,Ct_RDRP,geneS_detection,META_test_result,RINO_test_result,PARA_test_result,ADENO_test_result,BOCA_test_result,COVS_test_result,ENTERO_test_result,BAC_test_result
31584,DASA,279800084151,test_4,NaN,7b1859876e805cc6,Distrito Federal,NaN,2022-03-07,2022-03-12,43,...,NaN,NaN,NT,NT,NT,NT,NT,NT,NT,NT
31585,DASA,279800084151,test_4,NaN,dcb850bb21133ebf,Distrito Federal,BRASILIA,2022-03-07,2022-03-12,43,...,NaN,NaN,NT,NT,NT,NT,NT,NT,NT,NT

### Ids

Verificando se todos os Ids originais etão presentes no arquivo final

In [ ]:
set_test_ids_final_df = set(df_combined['test_id'])
set_test_ids_raw_data = set(df_full_raw['CODIGO REQUISICAO'])

NameError: name 'df_full_raw' is not defined

In [ ]:
# Testar se todos os test_ids da planilha original estão na planilha final
# deve retornar um set vazio
set_test_ids_raw_data.difference(set_test_ids_final_df)

{'1200085178_100',
 '1410231927_100',
 '1421499943_100',
 '1421512238_100',
 '1421512252_100',
 '1421524508_100',
 '1421542791_100',
 '1421567484_600',
 '1421573025_900',
 '1421574120_100',
 '1421580321_100',
 '1421580345_100',
 '1421580359_600',
 '1421580372_100',
 '1421580414_700',
 '1421590360_100',
 '1421608991_700',
 '1421618661_100',
 '1421623648_100',
 '1421627267_100',
 '1421641149_200',
 '1421661054_100',
 '1421747497_400',
 '1450064023_100',
 '1450064862_100',
 '1600683873_100',
 '1600708233_100',
 '1600709104_100',
 '1600712587_100',
 '1650441468_100',
 '1650447361_100',
 '1650451652_100',
 '1660378198_100',
 '1720397744_100',
 '1860281386_100',
 '1870163611_100',
 '2230148082_100',
 '2240159856_100',
 '2240169073_100',
 '2240170521_100',
 '2240193197_100',
 '2240197205_100',
 '2310036024_100',
 '2320523931_100',
 '2320536507_100',
 '2320542723_100',
 '2320550391_100',
 '2320551123_100',
 '2320551273_100',
 '2320562210_100',
 '2320582241_100',
 '2350037816_100',
 '2350041791_100',
 '2350042472_100',
 '2350042486_100',
 '2370310135_100',
 '2370310765_100',
 '2430081777_100',
 '2430088155_100',
 '2430102133_100',
 '2430120877_100',
 '2430123544_100',
 '2430124239_100',
 '2760242375_200',
 '2830609707_100',
 '2851154630_100',
 '2851166392_100',
 '2851220324_100',
 '2851224888_100',
 '2851236445_100',
 '2890312083_100',
 '2890315981_3600',
 '2890319311_200',
 '2890327807_100',
 '2900309937_100',
 '2900311009_100',
 '2900323810_100',
 '2930619195_100',
 '2930625551_100',
 '2930629278_100',
 '2930647860_600',
 '2930654008_100',
 '3020633514_100',
 '3020634205_100',
 '3020635555_100',
 '3020639228_100',
 '3020642206_100',
 '3020648144_100',
 '3020652178_100',
 '3020657759_100',
 '3020713657_100',
 '3020730850_100',
 '3020735048_100',
 '3020744911_100',
 '3020751012_100',
 '3020892203_100',
 '3120234796_100',
 '3120236393_300',
 '3120249271_100',
 '3120249294_100',
 '3120253404_100',
 '3120262999_100',
 '3120267497_100',
 '3120269571_100',
 '3120269718_100',
 '3120275446_100',
 '3120287553_100',
 '3120305921_100',
 '3120306242_100',
 '3120309006_100',
 '3120312221_100',
 '3120324261_100',
 '3120330342_100',
 '3120333296_100',
 '3120333870_100',
 '3120353982_100',
 '3140122724_100',
 '3420239077_100',
 '3420239451_100',
 '3450927609_100',
 '3450927682_100',
 '3450927746_100',
 '3450927814_100',
 '3450928008_100',
 '3450928018_100',
 '3450928040_100',
 '3450928045_100',
 '3450928060_100',
 '3450928067_100',
 '3450938440_100',
 '3450965169_100',
 '3450966391_100',
 '3451016291_100',
 '3451055816_100',
 '3551666203_100',
 '3551666391_100',
 '3551669439_100',
 '3551669755_100',
 '3551669781_100',
 '3551669806_100',
 '3551672137_100',
 '3551675124_100',
 '3551675628_100',
 '3551677558_100',
 '3551678828_200',
 '3551684415_100',
 '3551724743_100',
 '3551734902_100',
 '3551744927_100',
 '3551757812_100',
 '3551764654_100',
 '3551766367_100',
 '3551770794_100',
 '3551783953_100',
 '3560743860_100',
 '3560746668_100',
 '3560747808_200',
 '3560747881_200',
 '3560763576_100',
 '3560764783_100',
 '3560767732_100',
 '3560768845_100',
 '3560768905_100',
 '3560778283_100',
 '3560781278_100',
 '3560794148_100',
 '3560796365_100',
 '3560799508_100',
 '3560799609_100',
 '3560799622_600',
 '3560800603_100',
 '3560800789_100',
 '3560800998_100',
 '3560801669_100',
 '3560801698_100',
 '3560802417_100',
 '3560804028_100',
 '3560809850_100',
 '3560812869_100',
 '3560819778_1900',
 '3560821774_100',
 '3560838327_100',
 '3560838343_100',
 '3560838350_100',
 '3560838360_100',
 '3560838380_500',
 '3560845384_100',
 '3560846056_200',
 '3560853275_200',
 '3610226750_100',
 '3640278826_100',
 '3710302696_100',
 '3710302731_100',
 '3760101391_100',
 '3760136464_100',
 '3760152069_500',
 '3760182265_1300',
 '3801215969_100',
 '3801223729_300',
 '3801232880_100',
 '3801234463_100',
 '3801242480_100',
 '3801284805_1400',
 '3801292059_100',
 '3900169658_100',
 '3900226965_100',
 '3940060240_100',
 '3950015922_100',
 '3950015924_100',
 '3950017675_100',
 '3950018650_100',
 '3950018971_100',
 '3950020636_100',
 '3950021073_100',
 '3950023089_100',
 '4230003993_100',
 '4280000503_100',
 '4290009208_100',
 '4312728300_100',
 '4312731983_100',
 '4312734566_900',
 '4312743981_100',
 '4312746400_200',
 '4312761939_100',
 '4312764248_100',
 '4312773516_100',
 '4312793501_100',
 '4312798630_100',
 '4312817705_100',
 '4312820154_100',
 '4312828565_100',
 '4312830531_300',
 '4312831456_1000',
 '4312837452_100',
 '4312838457_100',
 '4312838929_100',
 '4312839006_300',
 '4312839607_1200',
 '4312841490_400',
 '4312841910_100',
 '4312842368_100',
 '4312847406_100',
 '4312848884_100',
 '4312850940_200',
 '4312855289_200',
 '4312855947_800',
 '4312875699_100',
 '4312906214_1000',
 '4312921358_600',
 '4312921600_100',
 '4322777578_100',
 '4332151713_100',
 '4332153159_200',
 '4332171032_100',
 '4332171115_1600',
 '4332213052_100',
 '4341047718_100',
 '4341091393_200',
 '4341092835_100',
 '4341097638_100',
 '4341099666_100',
 '4341107994_100',
 '4341110510_100',
 '4350469861_100',
 '4350504191_100',
 '4350505613_100',
 '4350510877_100',
 '4350537500_100',
 '4350542763_800',
 '4350542822_100',
 '4350543705_1600',
 '4350545285_100',
 '4350553385_200',
 '4350553989_100',
 '4350556119_100',
 '4350561616_100',
 '4350564374_100',
 '4350586975_400',
 '4350587033_100',
 '4350587058_100',
 '4350587088_200',
 '4350587108_100',
 '4350588252_100',
 '4370432105_200',
 '4370475578_300',
 '4370476775_100',
 '4370476975_1600',
 '4370491587_700',
 '4370524806_100',
 '4370530639_100',
 '4370530849_100',
 '4370544506_100',
 '4370552007_100',
 '4370552882_600',
 '4370557029_100',
 '4370560396_100',
 '4390119905_200',
 '4403479036_100',
 '4403489465_100',
 '4403492858_100',
 '4403494393_100',
 '4403538324_100',
 '4403543904_100',
 '4403582380_100',
 '4403588332_100',
 '4403631706_100',
 '4403650211_100',
 '4403650327_100',
 '4403702551_100',
 '4403747113_100',
 '4409842350_200',
 '4409846153_100',
 '4430175336_100',
 '4430178676_100',
 '4430198486_100',
 '4430198491_100',
 '4430198507_100',
 '4430198513_100',
 '4430219012_100',
 '4430219102_100',
 '4430219557_2400',
 '4451933194_100',
 '4451933543_100',
 '4451933817_100',
 '4451934497_100',
 '4451955873_100',
 '4451962911_100',
 '4451962980_300',
 '4451972520_100',
 '4451972650_100',
 '4451972740_100',
 '4451986562_100',
 '4451992862_300',
 '4452022047_400',
 '4452024088_100',
 '4452024972_100',
 '4452027340_100',
 '4452027446_100',
 '4452029098_100',
 '4452030716_100',
 '4452031246_100',
 '4452034498_900',
 '4452034550_100',
 '4452034555_100',
 '4452035426_200',
 '4452060122_100',
 '4452094724_100',
 '4452095127_900',
 '4452095202_500',
 '4452095237_500',
 '4452095251_1800',
 '4452095291_300',
 '4452095297_100',
 '4452095301_200',
 '4452095350_100',
 '4452102784_200',
 '4452145333_100',
 '4452193918_100',
 '4460063977_300',
 '4460065323_100',
 '4460077857_100',
 '4470022669_100',
 '4470027241_100',
 '4470029203_100',
 '4480015210_100',
 '4540680705_800',
 '4540680804_2300',
 '4540681869_100',
 '4540682501_1200',
 '4540683780_200',
 '4540684922_100',
 '4540685116_100',
 '4540685923_200',
 '4540685924_100',
 '4540685933_200',
 '4540687601_200',
 '4540691294_400',
 '4540691756_200',
 '4540695930_100',
 '4540707539_100',
 '4540735562_100',
 '4540741755_100',
 '4540833811_100',
 '4540834096_300',
 '4540837101_100',
 '4540839431_100',
 '4540842677_200',
 '4540854622_100',
 '4540858550_100',
 '4550542977_100',
 '4550544946_100',
 '4550546157_100',
 '4550556634_1000',
 '4550558678_100',
 '4550561940_200',
 '4550563090_1000',
 '4550563495_300',
 '4550569485_100',
 '4550570747_100',
 '4550570785_100',
 '4550573604_100',
 '4550584059_200',
 '4550591493_500',
 '4550611507_100',
 '4550616334_600',
 '4550618368_100',
 '4550619525_100',
 '4550620920_100',
 '4550621683_1100',
 '4550624617_100',
 '4550625498_100',
 '4550635975_100',
 '4550637070_100',
 '4550642655_100',
 '4550645857_1300',
 '4550655321_2600',
 '4550661576_200',
 '4550673391_500',
 '4550673399_100',
 '4550676919_600',
 '4550677341_900',
 '4550690124_100',
 '4550703397_100',
 '4550708641_100',
 '4561698147_100',
 '4561700682_100',
 '4561702220_100',
 '4561721569_100',
 '4561751549_100',
 '4561808484_100',
 '4561843731_100',
 '4561983084_100',
 '4562002169_100',
 '4562015340_100',
 '4562042158_100',
 '4562060114_300',
 '4562082241_100',
 '4562086585_100',
 '4562116375_100',
 '4562133698_700',
 '4562138006_500',
 '4562165233_100',
 '4562166308_100',
 '4562186942_100',
 '4562200739_100',
 '4562230339_100',
 '4562230436_100',
 '4562233683_100',
 '4562242096_100',
 '4570467427_100',
 '4570472223_100',
 '4570473856_100',
 '4570475094_100',
 '4570519006_100',
 '4570550474_100',
 '4570575284_100',
 '4580310873_100',
 '4580360525_100',
 '4580371950_500',
 '4602124751_100',
 '4650159640_100',
 '4780054693_100',
 '4780065327_100',
 '4780069950_200',
 '4790285529_100',
 '4790311248_100',
 '4790312869_100',
 '4790314252_100',
 '4790324558_100',
 '4830102580_100',
 '4830103697_100',
 '4830104251_100',
 '4830113556_100',
 '5100132471_100',
 '5100139203_100',
 '5310079266_100',
 '5350045507_100',
 '5400311452_100',
 '5400311800_400',
 '5400313402_100',
 '5400316985_100',
 '5420274780_100',
 '5620056458_100',
 '5670138346_100',
 '5670141540_100',
 '5690066259_100',
 '5730069645_200',
 '6140293992_100',
 '6200019815_100',
 '6300606727_100',
 '6320156296_100',
 '6350492375_100',
 '6350492404_100',
 '6350492504_100',
 '6350511676_100',
 '6550391412_100',
 '6550419044_100',
 '6550419383_100',
 '6580095664_100',
 '6600838756_100',
 '6670695785_100',
 '6670728320_100',
 '7000705595_100',
 '7000709012_100',
 '7000712576_100',
 '7000713062_100',
 '7040087590_100',
 '7060009863_100',
 '7090058512_100',
 '7101031250_100',
 '7140012397_100',
 '7170021821_100',
 '7170028066_100',
 '7180050112_100',
 '7200683512_100',
 '7240012997_100',
 '7250031293_100',
 '7270005578_100',
 '7270005583_100',
 '7270005589_100',
 '7400868173_100',
 '7400869083_100',
 '7400877601_100',
 '7600173238_100',
 '7600190134_100',
 '7770978786_100',
 '7801594351_100',
 '7801612108_100',
 '7900180714_100',
 '8020387770_100',
 '8020393763_400',
 '8050552414_100',
 '8060124422_100',
 '8120091572_700',
 '8200258696_100',
 '8705004072_100',
 '8705004156_200',
 '8705005379_100',
 '8705005551_100',
 '8705038182_100',
 '8705155067_100',
 '8705373262_100',
 '8709853151_1100',
 '8750150094_1200',
 '8750152667_100',
 '8750168177_100',
 '8750173631_100',
 '8830022805_100',
 '8860020564_100',
 '8860020608_100',
 '8860020894_100',
 '8860021917_100',
 '8860027893_100',
 '8900398703_100',
 '8900420302_100',
 '8920001987_100',
 '9010080155_100',
 '9010086149_100',
 '9240044835_100',
 '9240045022_100',
 '9240045240_100',
 '9240067830_100',
 '9240072525_100',
 'Total de resultados: 103477',
 'Total de resultados: 117368',
 'Total de resultados: 147991',
 'Total de resultados: 22007',
 'Total de resultados: 270279',
 'Total de resultados: 27655',
 'Total de resultados: 2817',
 'Total de resultados: 2841',
 'Total de resultados: 30036',
 'Total de resultados: 3022',
 'Total de resultados: 3255',
 'Total de resultados: 3704',
 'Total de resultados: 40644',
 'Total de resultados: 45536',
 'Total de resultados: 47795',
 'Total de resultados: 50386',
 'Total de resultados: 5131',
 'Total de resultados: 5147',
 'Total de resultados: 5418',
 'Total de resultados: 5680',
 'Total de resultados: 6153',
 'Total de resultados: 6493',
 'Total de resultados: 6613',
 'Total de resultados: 67177',
 'Total de resultados: 69844',
 'Total de resultados: 70798',
 'Total de resultados: 7146',
 'Total de resultados: 71849',
 'Total de resultados: 7787'}

In [ ]:
# Verificar se há test_ids na planilha final que não estão na planilha original
# deve retornar um set vazio
set_test_ids_final_df.difference(set_test_ids_raw_data)

set()

Verificando se todos os patógenos de um test_kit estão sendo testados para todos os test_id

In [ ]:
PATHOGENS_TESTS = {
    'panel_21':{
        # PAINCOVI
        'FLUA_test_result',
        'FLUB_test_result',
        'VSR_test_result',
        'SC2_test_result',
        'META_test_result',
        'RINO_test_result',
        'PARA_test_result',
        'ADENO_test_result',
        'COVS_test_result',
        'BAC_test_result',
    },

    'panel_24':{
        # RESPIRA
        'FLUA_test_result',
        'FLUB_test_result',
        'VSR_test_result',
        'META_test_result',
        'RINO_test_result',
        'PARA_test_result',
        'ADENO_test_result',
        'BOCA_test_result',
        'COVS_test_result',
        'ENTERO_test_result',
        'BAC_test_result',
    },

    'flu_antigen':{
        'FLUA_test_result',
        'FLUB_test_result',
    },

    'covid_antigen':{
        'SC2_test_result',
    },

    'covid_pcr':{
        'SC2_test_result',
    },
}

In [ ]:
# Mapeando Pos e Neg para Tes
df_combined_test_pathogen_non_nt_on_kit = (
    df_combined
    .replace(('Pos', 'Neg'),  'Tes')
)

In [ ]:
for pathogen, test_columns in PATHOGENS_TESTS.items():
    print(pathogen)
    print(
        df_combined_test_pathogen_non_nt_on_kit
        .query("test_kit == @pathogen")
        [list(test_columns)]
        .drop_duplicates().T
        # Deve resultar em apenas uma linha completa por 'Tes'
    )

    print('\n\n')

panel_21
Empty DataFrame
Columns: []
Index: [FLUB_test_result, PARA_test_result, BAC_test_result, COVS_test_result, META_test_result, VSR_test_result, ADENO_test_result, RINO_test_result, FLUA_test_result, SC2_test_result]



panel_24
Empty DataFrame
Columns: []
Index: [FLUB_test_result, PARA_test_result, ENTERO_test_result, BAC_test_result, COVS_test_result, META_test_result, VSR_test_result, ADENO_test_result, BOCA_test_result, RINO_test_result, FLUA_test_result]



flu_antigen
Empty DataFrame
Columns: []
Index: [FLUB_test_result, FLUA_test_result]



covid_antigen
Empty DataFrame
Columns: []
Index: [SC2_test_result]



covid_pcr
                1929
SC2_test_result  Tes

Verificando resultados de alguns testes

In [ ]:
import numpy as np

In [ ]:
np.random.seed(214)

ids = np.random.choice(df_combined['test_id'], 100)
test_columns = [col for col in df_combined.columns if col.endswith('_result')]

In [ ]:
current_id=50

In [ ]:
current_id = current_id+1
id = ids[current_id]
print( df_combined.query("test_id == @id")[['test_id', 'test_kit'] + test_columns].T )
print( df_hla_covid.query(f"Pedido == '{id}'") [['Pedido'] + [col for col in df_hla_covid.columns if col.startswith('Vírus')]].T )
print( df_hla_ctn.query(f"Pedido == '{id}'") [['Pedido', 'Resultado']].T )
print( df_hla_flu.query(f"Pedido == '{id}'") [['Pedido']+ [col for col in df_hla_flu.columns if col.startswith('VIRUS') or col.startswith('BAC')]].T )
print( df_hla_ph4.query(f"Pedido == '{id}'") [['Pedido']+ [col for col in df_hla_ph4.columns if col.startswith('VIRUS') or col.startswith('BAC')]].T )

                         7665
test_id               2262865
test_kit            covid_pcr
FLUA_test_result           NT
FLUB_test_result           NT
VSR_test_result            NT
SC2_test_result           Neg
META_test_result           NT
RINO_test_result           NT
PARA_test_result           NT
ADENO_test_result          NT
BOCA_test_result           NT
COVS_test_result           NT
ENTERO_test_result         NT
BAC_test_result            NT
Empty DataFrame
Columns: []
Index: [Pedido, Vírus Influenza A, Vírus Influenza B, Vírus Sincicial Respiratório A/B]
                   1912
Pedido          2262865
Resultado  Inconclusivo
Empty DataFrame
Columns: []
Index: [Pedido, VIRUS_Influenza A, VIRUS_Influenza H1N1, VIRUS_Influenza H3, VIRUS_Influenza B, VIRUS_Metapneumovírus, VIRUS_Sincicial A, VIRUS_Sincicial B, VIRUS_Rinovírus, VIRUS_Parainfluenza 1, VIRUS_Parainfluenza 2, VIRUS_Parainfluenza 3, VIRUS_Parainfluenza 4, VIRUS_Adenovirus, VIRUS_Bocavirus, VIRUS_CoV-229E, VIRUS_CoV-HKU, VIRUS_CoV-NL63, VIRUS_CoV-OC43, VIRUS_SARS_Like, VIRUS_SARS-CoV-2, VIRUS_Enterovírus, BACTE_Bordetella pertussis, BACTE_Bordetella parapertussis, BACTE_Mycoplasma pneumoniae]
Empty DataFrame
Columns: []
Index: [Pedido, VIRUS_IA, VIRUS_H1N1, VIRUS_AH3, VIRUS_B, VIRUS_MH, VIRUS_SA, VIRUS_SB, VIRUS_RH, VIRUS_PH, VIRUS_PH2, VIRUS_PH3, VIRUS_PH4, VIRUS_ADE, VIRUS_BOC, VIRUS_229E, VIRUS_HKU, VIRUS_NL63, VIRUS_OC43, VIRUS_SARS, VIRUS_COV2, VIRUS_EV, BACTE_BP, BACTE_BPAR, BACTE_MP]

Verificando resultados de alguns testes - Fltrando por test_kit

In [ ]:
np.random.seed(214)

ids = np.random.choice(df_combined.query("test_kit not in ('covid_pcr', 'covid_antigen')")['test_id'], 100)
test_columns = [col for col in df_combined.columns if col.endswith('_result')]

In [ ]:
current_id=50

In [ ]:
current_id = current_id+1
id = ids[current_id]
print( df_combined.query("test_id == @id")[['test_id', 'test_kit'] + test_columns].T )
print( df_hla_covid.query(f"Pedido == '{id}'") [['Pedido'] + [col for col in df_hla_covid.columns if col.startswith(('Vírus', 'Coron'))]].T )
print( df_hla_flu.query(f"Pedido == '{id}'") [['Pedido']+ [col for col in df_hla_flu.columns if col.startswith('VIRUS') or col.startswith('BAC')]].T )
print( df_hla_ph4.query(f"Pedido == '{id}'") [['Pedido']+ [col for col in df_hla_ph4.columns if col.startswith('VIRUS') or col.startswith('BAC')]].T )

                      50943
test_id             2354190
test_kit             test_4
FLUA_test_result        Neg
FLUB_test_result        Neg
VSR_test_result         Pos
SC2_test_result         Neg
META_test_result         NT
RINO_test_result         NT
PARA_test_result         NT
ADENO_test_result        NT
BOCA_test_result         NT
COVS_test_result         NT
ENTERO_test_result       NT
BAC_test_result          NT
                                             18
Pedido                                  2354190
Vírus Influenza A                 Não Detectado
Vírus Influenza B                 Não Detectado
Vírus Sincicial Respiratório A/B      Detectado
Coronavírus SARS-CoV-2            Não Detectado
Empty DataFrame
Columns: []
Index: [Pedido, VIRUS_Influenza A, VIRUS_Influenza H1N1, VIRUS_Influenza H3, VIRUS_Influenza B, VIRUS_Metapneumovírus, VIRUS_Sincicial A, VIRUS_Sincicial B, VIRUS_Rinovírus, VIRUS_Parainfluenza 1, VIRUS_Parainfluenza 2, VIRUS_Parainfluenza 3, VIRUS_Parainfluenza 4, VIRUS_Adenovirus, VIRUS_Bocavirus, VIRUS_CoV-229E, VIRUS_CoV-HKU, VIRUS_CoV-NL63, VIRUS_CoV-OC43, VIRUS_SARS_Like, VIRUS_SARS-CoV-2, VIRUS_Enterovírus, BACTE_Bordetella pertussis, BACTE_Bordetella parapertussis, BACTE_Mycoplasma pneumoniae]
Empty DataFrame
Columns: []
Index: [Pedido, VIRUS_IA, VIRUS_H1N1, VIRUS_AH3, VIRUS_B, VIRUS_MH, VIRUS_SA, VIRUS_SB, VIRUS_RH, VIRUS_PH, VIRUS_PH2, VIRUS_PH3, VIRUS_PH4, VIRUS_ADE, VIRUS_BOC, VIRUS_229E, VIRUS_HKU, VIRUS_NL63, VIRUS_OC43, VIRUS_SARS, VIRUS_COV2, VIRUS_EV, BACTE_BP, BACTE_BPAR, BACTE_MP]