## Importing Packages

python scripts/reformat_dasa.py --datadir data --rename data/rename_columns.xlsx --correction data/fix_values.xlsx --output combined_dasa.tsv

In [2]:
import pandas as pd
import os
import re

## Loading Data

In [3]:
def load_table(file, separator=None):
    df = ''
    if str(file).split('.')[-1] == 'tsv':
        separator = '\t' if separator is None else separator
        df = pd.read_csv(file, encoding='latin-1', sep=separator, dtype='str')
    elif str(file).split('.')[-1] == 'csv':
        separator = ',' if separator is None else separator
        df = pd.read_csv(file, encoding='latin-1', sep=separator, dtype='str')
    elif str(file).split('.')[-1] in ['xls', 'xlsx']:
        df = pd.read_excel(file, index_col=None, header=0, sheet_name=0, dtype='str')
        df.fillna('', inplace=True)
    else:
        print('Wrong file format. Compatible file formats: TSV, CSV, XLS, XLSX')
        exit()
    return df

In [4]:
BASE_PATH = '../data/DASA/'
dfs = []

for file in os.listdir(BASE_PATH):
    if file.endswith(('.xlsx', '.tsv')):
        print(file)
        df = load_table(BASE_PATH + file, separator='\t')
        dfs.append(df)

20220712_dados Dasa suspect_omicron_2022-07-03_2022-07-09-thermo para ITpS.xlsx
20230419_Dados Dasa patogenos_respiratorios_2023-04-09_2023-04-15 para ITpS_SE15.xlsx
20230713_Dados Dasa patogenos_respiratorios_2023-07-02_2023-07-08 para ITpS_SE27.xlsx
20220614_Dados Dasa patogenos_respiratorios_2022_06_05-2022_06_11 para ITpS.xlsx
20220621_Dados Dasa patogenos_respiratorios_2022-06-12_2022-06-18.xlsx
20221101_dados Dasa suspect_omicron_2022-10-09_2022-10-15-thermo para ITpS_SE41.xlsx
20220517_Dados Dasa patogenos_respiratorios_2022_05_08-2022_05_14 para ITpS.xlsx
20220722_Dados Dasa patogenos_respiratorios_2022-07-10_2022-07-16 para ITpS.xlsx
20220722_dados Dasa suspect_omicron_2022-07-10_2022-07-16-thermo para ITpS.xlsx
20221101_Dados Dasa suspect_omicron_2022-10-23_2022-10-29-thermo ITpS_SE43.xlsx
20220928_Dados Dasa patogenos_respiratorios_2022-09-18_2022-09-24 para ITpS.xlsx
20230529_Dados Dasa suspect_omicron_2023-05-14_2023-05-20-thermo para ITpS_SE20.xlsx
20221005_dados Dasa suspect_omicron_2022-09-25_2022-10-01-thermo para ITpS.xlsx
20221101_Dados Dasa patogenos_respiratorios_2022-10-16_2022-10-22 para ITpS_SE42.xlsx
20230111_dados Dasa patogenos_respiratorios_2023-01-01_2023-01-07 para ITpS_SE01.xlsx
20221005_Dados Dasa patogenos_respiratorios_2022-09-25_2022-10-01 para ITpS.xlsx
20220921_Dados Dasa patogenos_respiratorios_2022-09-04_2022-09-10 para ITpS.xlsx
20220712_Dados Dasa patogenos_respiratorios_2022-07-03_2022-07-09 para ITpS.xlsx
20230105_Dados dasa suspect_omicron_2022-12-18_2022-12-24-thermo para ITpS_SE51.xlsx
20220314_patogenos_respiratorios_24-02-2022_10-03-2022 para ITPS.xlsx
20230126_Dados dasa patogenos_respiratorios_2023-01-15_2023-01-21 para ITpS_SE03.xlsx
20221101_dados Dasa suspect_omicron_2022-10-16_2022-10-22-thermo para ITpS_SE42.xlsx
20221012_dados Dasa suspect_omicron_2022-10-02_2022-10-08-thermo para ITpS.xlsx
20230329_Dados Dasa suspect_omicron_2023-03-19_2023-03-25-thermo para ITpS_SE12.xlsx
20221110_Dados dasa patogenos_respiratorios_2022-10-30_2022-11-05 para ITpS_SE44.xlsx
20230208_Dados Dasa patogenos_respiratorios_2023-01-29_2023-02-04 para ITpS_SE05.xlsx
20230508_Dados Dasa patogenos_respiratorios_2023-04-23_2023-04-29 para ITpS_SE17.xlsx
20220404_Dados dasa suspect_omicron_20 3 a 2 4 2022 thermo para ITPs.xlsx
20220510_dados Dasa suspect_omicron_2022-05-01_2022-05-07-thermo para ITpS.xlsx
20230314_DADOS Dasa suspect_omicron_2023-03-05_2023-03-11-thermo para ITpS_SE10.xlsx
20221128_Dados Dasa patogenos_respiratorios_2022-11-20_2022-11-26 para ITpS_SE47.xlsx
20230411_Dados Dasa suspect_omicron_2023-04-02_2023-04-08-thermo para ITpS_SE14.xlsx
20220816_Dados patogenos_respiratorios_2022-08-07_2022-08-13 para ITpS.xlsx
20230201_Dados Dasa suspect_omicron_2023-01-22_2023-01-28-thermo para ITpS_SE04.xlsx
20230626_Dados Dasa patogenos_respiratorios_2023-06-11_2023-06-17 para ITpS_SE24.xlsx
20230201_Dados Dasa patogenos_respiratorios_2023-01-22_2023-01-28_SE04.xlsx
20220413_Dados Dasa patogenos_respiratorios_2022_04_03-2022_04_09 para ITPs.xlsx
20220606_Dados Dasa suspect_omicron_2022-05-29_2022-06-04-thermo para ITpS.xlsx
20220921_dados Dasa suspect_omicron_2022-09-11_2022-09-17-thermo para ITpS.xlsx
20220413_Dados Dasa suspect_omicron_2022-04-03_2022-04-09-thermo para ITPs.xlsx
20220504_dados Dasa patogenos_respiratorios_2022_04_24-2022_04_30 para ITpS.xlsx
20211223_suspect_omicron_01_12_20_12 21 S-DROPUTS thermo só multiplex DASA PARA ITPS.xlsx
20230427_Dados Dasa suspect_omicron_2023-04-16_2023-04-22-thermo para ITpS_SE16.xlsx
20230228_Dados Dasa patogenos_respiratorios_2023-02-19_2023-02-25 para ITpS_SE08.xlsx
20220921_Dados Dasa patogenos_respiratorios_2022-08-28_2022-09-03 para ITpS.xlsx
20221012_Dados Dasa patogenos_respiratorios_2022-10-02_2022-10-08 para ITpS.xlsx
20220704_Dados dasa suspect_omicron_2022-06-26_2022-07-02-thermo para ITpS.xlsx
20220322_patogenos_respiratorios_2022_03_06-2022_03_19 DASA para ITPS.xlsx
20230528_Dados Dasa patogenos_respiratorios_2023-05-07_2023-05-13 para ITpS_SE19.xlsx
20220823_Dados Dasa suspect_omicron_2022-08-14_2022-08-20-thermo para ITpS.xlsx
20230624_Dados Dasa suspect_omicron_2023-05-28_2023-06-03-thermo para ITpS_SE22.xlsx
20230404_Dados Dasa patogenos_respiratorios_2023-03-26_2023-04-01 para ITpS_SE13.xlsx
20220523_dados dasa suspect_omicron_2022-05-15_2022-05-21-thermo para ITpS.xlsx
20220921_Dados Dasa suspect_omicron_2022-09-04_2022-09-10-thermo para ITpS.xlsx
20230510_dados dasa suspect_omicron_2023-04-30_2023-05-06-thermo para ITpS_SE18.xlsx
20230323_Dados Dasa suspect_omicron_2023-03-12_2023-03-18-thermo para ITpS_SE11.xlsx
20220222_suspect_omicron_07_02_18_02-thermo PARA ITPS.xlsx
20220802_Dados patogenos_respiratorios_2022-07-24_2022-07-30 para ITpS.xlsx
20220921_Dados Dasa suspect_omicron_2022-08-28_2022-09-03-thermo para ITpS.xlsx
20220809_dados Dasa suspect_omicron_2022-07-31_2022-08-06-thermo para ITpS.xlsx
20220118_suspect_omicron_04_01_14_01-thermo DASA para ITPS.xlsx
20220510_Dados Dasa patogenos_respiratorios_2022_05_01-2022_05_07 para ITpS.xlsx
20230116_Dados Dasa patogenos_respiratorios_2023-01-08_2023-01-14 para ITpS_SE02.xlsx
20220601_Dados Dasa patogenos_respiratorios_2022_05_22-2022_05_28 para ITpS.xlsx
20220427_Dados Dasa suspect_omicron_2022-04-17_2022-04-23-thermo para ITpS.xlsx
20221207_Dados Dasa patogenos_respiratorios_2022-11-27_2022-12-03 para ITpS_SE48.xlsx
20220921_Dados Dasa patogenos_respiratorios_2022-09-11_2022-09-17 para ITpS.xlsx
20220823_Dados Dasa patogenos_respiratorios_2022-08-14_2022-08-20 para ITpS.xlsx
20221219_Dados dasa patogenos_respiratorios_2022-12-11_2022-12-18 para ITpS_SE49.xlsx
20230126_Dados Dasa suspect_omicron_2023-01-15_2023-01-21-thermo para ITpS_SE03.xlsx
20220517_dados dasa suspect_omicron_2022-05-08_2022-05-14-thermo para ITpS.xlsx
20220427_Dados Dasa patogenos_respiratorios_2022_04_17-2022_04_23 para ITpS.xlsx
20230624_Dados Dasa patogenos_respiratorios_2023-05-28_2023-06-03 para ITpS_SE22.xlsx
20230606_Dados Dasa patogenos_respiratorios_2023-05-21_2023-05-27 para ITpS_SE21.xlsx
20220601_Dados Dasa suspect_omicron_2022-05-22_2022-05-28-thermo para ITpS.xlsx
20230218_Dados Dasa patogenos_respiratorios_2023-02-05_2023-02-11 para ITpS_SE06.xlsx
20230510_Dados patogenos_respiratorios_2023-04-30_2023-05-06 para ITpS_SE18.xlsx
20230427_Dados dasa patogenos_respiratorios_2023-04-16_2023-04-22 para ITpS_SE16.xlsx
20221019_dados Dasa patogenos_respiratorios_2022-10-09_2022-10-15 para ITpS.xlsx
20230529_Dados Dasa patogenos_respiratorios_2023-05-14_2023-05-20 para ITpS_SE20.xlsx
20230419_Dados Dasa suspect_omicron_2023-04-09_2023-04-15-thermo para ITpS_SE15.xlsx
20230116_Dados Dasa suspect_omicron_2023-01-08_2023-01-14-thermo para ITpS_SE02.xlsx
20230625_Dados Dasa suspect_omicron_2023-06-04_2023-06-10-thermo para ITpS_SE23.xlsx
20220614_Dados Dasa suspect_omicron_2022-06-05_2022-06-11-thermo para ITpS.xlsx
20230626_Dados Dasa suspect_omicron_2023-06-11_2023-06-17-thermo para ITpS_SE24.xlsx
20220621_Dados Dasa suspect_omicron_2022-06-12_2022-06-18-thermo para ITpS.xlsx
20220627_Dados Dasa suspect_omicron_2022-06-19_2022-06-25-thermo para ITpS.xlsx
20220829_dados Dasa suspect_omicron_2022-08-21_2022-08-27-thermo para ITpS.xlsx
20230528_Dados Dasa suspect_omicron_2023-05-07_2023-05-13- thermo  para ITpS_SE19.xlsx
20220523_Dados Dasa patogenos_respiratorios_2022_05_15-2022_05_21 para ITpS.xlsx
20230627_Dados Dasa patogenos_respiratorios_2023-06-18_2023-06-24 para ITpS_SE25.xlsx
20230105_Dados Dasa patogenos_respiratorios_2022-12-25_2022-12-31 para ITpS_SE52.xlsx
20230105_Dados dasa suspect_omicron__2022-12-25_2022-12-31-thermo para ITpS_SE52.xlsx
20220704_Dados Dasa patogenos_respiratorios_2022-06-26_2022-07-02 para ITpS.xlsx
20230228_Dados Dasa patogenos_respiratorios_2023-02-12_2023-02-18 para ITpS_SE07.xlsx
20220110_suspect_omicron_21_12_03_01-thermo DASA PARA ITPS.xlsx
20220809_Dados patogenos_respiratorios_2022-07-31_2022-08-06 para ITpS.xlsx
20220802_Dados Dasa suspect_omicron_2022-07-24_2022-07-30-thermo para ITpS.xlsx
20230228_Dados Dasa suspect_omicron_2023-02-19_2023-02-25-thermo para ITpS_SE08.xlsx
20230323_Dados patogenos_respiratorios_2023-03-12_2023-03-18 para ITpS_SE11.xlsx
20230625_dados Dasa patogenos_respiratorios_2023-06-04_2023-06-10 para ITpS_SE23.xlsx
20221227_Dados Dasa patogenos_respiratorios_2022-12-18_2022-12-24 para ITpS_SE51.xlsx
20220210_suspect_omicron_26_01_06_02-thermo DASA PARA ITPS.xlsx
20220627_dados Dasa patogenos_respiratorios_2022-06-19_2022-06-25 para ITpS.xlsx
20230309_Dados Dasa patogenos_respiratorios_2023-02-26_2023-03-04 para ITpS_SE09.xlsx
20220614_Dados Dasa patogenos_respiratorios_2022_05_29-2022_06_04 para ITpS.xlsx
20220928_dados Dasa suspect_omicron_2022-09-18_2022-09-24-thermo para ITpS.xlsx
20230208_Dados Dasa suspect_omicron_2023-01-29_2023-02-04-thermo para ITpS_SE05.xlsx
20230508_dados dasa suspect_omicron_2023-04-23_2023-04-29-thermo para ITpS_SE17.xlsx
20230411_Dados Dasa patogenos_respiratorios_2023-04-02_2023-04-08 para ITpS_SE14.xlsx
20230329_Dados patogenos_respiratorios_2023-03-19_2023-03-25 para ITpS_SE12.xlsx
20230627_Dados dasa suspect_omicron_2023-06-18_2023-06-24-thermo para ITpS_SE25.xlsx
20221219_Dados Dasa patogenos_respiratorios_2022-12-04_2022-12-10 para ITpS_SE50.xlsx
20220308_suspect_omicron_19_02_05_03-thermo DASA para ITPS.xlsx
20220727_Dados Dasa patogenos_respiratorios_2022-07-17_2022-07-23 para ITpS.xlsx
20220323_suspect_omicron_06_03_19_03-thermo Dasa para ITPS.xlsx
20220829_Dados Dasa patogenos_respiratorios_2022-08-21_2022-08-27 para ITpS.xlsx
20230314_Dados Dasa patogenos_respiratorios_2023-03-05_2023-03-11 para ITpS_SE10.xlsx
20230111_Dados Dasa suspect_omicron_2023-01-01_2023-01-07-thermo para ITpS_SE01.xlsx
20221101_Dados Dasa patogenos_respiratorios_2022-10-23_2022-10-29 para ITpS_SE43.xlsx
20220419_Dados Dasa patogenos_respiratorios_2022_04_10-2022_04_16 para ITPs.xlsx
20221117_Dados Dasa patogenos_respiratorios_2022-11-06_2022-11-12 para ITpS_SE45.xlsx
20230404_Dados Dasa suspect_omicron_2023-03-26_2023-04-01-thermo para ITpS_SE13.xlsx
20220504_Dados Dasa suspect_omicron_2022-04-24_2022-04-30-thermo para ITpS.xlsx
20220816_dados Dasa suspect_omicron_2022-08-07_2022-08-13-thermo para ITpS.xlsx
20230705_Dados Dasa patogenos_respiratorios_2023-06-25_2023-07-01 para ITpS_SE26.xlsx
20220419_Dados Dasa suspect_omicron_2022-04-10_2022-04-16-thermo para ITPs.xlsx
20230228_Dados Dasa suspect_omicron_2023-02-12_2023-02-18-thermo para ITpS_SE07.xlsx
20230218_Dados Dasa suspect_omicron_2023-02-05_2023-02-11-thermo para ITpS_SE06.xlsx
20220127_suspect_omicron_15_01_25_01-thermo DASA para ITPS.xlsx
20220404_Dados Dasa patogenos_respiratorios_2022_03_20-2022_04_02 para ITPs.xlsx
20230309_Dados Dasa suspect_omicron_2023-02-26_2023-03-04-thermo para ITpS_SE09.xlsx
20220727_dados Dasa suspect_omicron_2022-07-17_2022-07-23-thermo para ITpS.xlsx
20230606_Dados dasa suspect_omicron_2023-05-21_2023-05-27-thermo para ITpS_SE21.xlsx

## Codigo

In [5]:
codigo_dfs = [ df for df in dfs if 'codigo' in df.columns.tolist() ]

In [6]:
TEST_NAME = "test_4"

In [7]:
codigo_df = pd.concat(codigo_dfs)
codigo_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 131680 entries, 0 to 2391
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   ano_mes           131680 non-null  object
 1   data_exame        131680 non-null  object
 2   nome_pac          3840 non-null    object
 3   sexo              131680 non-null  object
 4   idade             131680 non-null  object
 5   cidade            128648 non-null  object
 6   uf                131680 non-null  object
 7   telefone          3840 non-null    object
 8   email             3840 non-null    object
 9   codigorequisicao  131680 non-null  object
 10  codigo            131680 non-null  object
 11  positivo          131680 non-null  object
dtypes: object(12)
memory usage: 13.1+ MB

In [8]:
DROP_COLUMNS = ['email', 'telefone', 'nome_pac', 'ano_mes']
codigo_df = codigo_df.drop(columns=DROP_COLUMNS)

### Valores únicos

In [9]:
codigo_df['codigo'].unique()

array(['FLUA', 'FLUB', 'VSR', 'COVID'], dtype=object)

In [10]:
codigo_df['positivo'].unique()

array(['1', '0'], dtype=object)

In [11]:
codigo_df['codigorequisicao'].replace(re.compile('[0-9]'), 'x').unique()

array(['xxxxxxxxxxxx', ''], dtype=object)

In [12]:
(
    codigo_df
    .query("codigorequisicao != ''")
    
    # query where 'cidade' is not NaN
    .query("cidade == cidade")
    .assign(duplicated=lambda df: df.duplicated(subset=['codigorequisicao']))
    .groupby('codigorequisicao')
    .agg({'duplicated': 'sum'})
    .assign(duplicated=lambda df: df['duplicated'] + 1)
    .sort_values('duplicated', ascending=False)
    ['duplicated']
    .unique()
)

array([4])

In [34]:
codigo_df.query("codigorequisicao == '934401167060'")

     date_testing sex age   location state codigorequisicao codigo  result
736    2022-03-08   F  64        NaN    SP     934401167060   FLUA       0
737    2022-03-08   F  64        NaN    SP     934401167060   FLUB       0
738    2022-03-08   F  64        NaN    SP     934401167060    VSR       0
739    2022-03-08   F  64        NaN    SP     934401167060  COVID       0
151    2022-03-08   F  64  SAO PAULO    SP     934401167060   FLUA       0
833    2022-03-08   F  64  SAO PAULO    SP     934401167060   FLUB       0
1515   2022-03-08   F  64  SAO PAULO    SP     934401167060    VSR       0
2197   2022-03-08   F  64  SAO PAULO    SP     934401167060  COVID       0

Problema:
O campo codigorequisicao tem valores faltantes = ''

Solução:
Drop de linhas com valores faltantes

Problema:

O campo codigorequisicao se repete 4 ou 8 vezes nos arquivos.
A repetição de 4x é devido aos 4 tipos de patógenos capturados, enquanto a de 8x parece ser um erro de duplicação.

O erro de duplicação tem uma característica marcante: aparentemente, toda entrada possui o campo 'cidade' como NaN. Ou seja, uma possivel solução para remover as duplicatas é remover linhas que possuem NaN em 'cidade'.


Solução: 

drop_duplicates( subset = ['codigorequisicao', 'codigo'] )

.query("cidade == cidade")  # Um NaN não é igual a ele mesmo, então essa query remove NaNs

In [14]:
codigo_df['positivo'] = codigo_df['positivo'].astype(int)

codigo_df = (
    codigo_df
    .rename(
        columns={
            'data_exame': 'date_testing',
            'positivo': 'result',
            'sexo': 'sex',
            'idade': 'age',
            'cidade': 'location',
            'uf': 'state',
        }
    )
)

In [15]:
codigo_df

,date_testing,sex,age,location,state,codigorequisicao,codigo,result
0,2023-04-11 00:00:00,M,31,BRASILIA,DF,804301974351,FLUA,1
1,2023-04-13 00:00:00,M,53,CASCAVEL,PR,541619041404,FLUA,1
2,2023-04-12 00:00:00,M,3,CASCAVEL,PR,926027817672,FLUA,1
3,2023-04-12 00:00:00,F,52,SAO PAULO,SP,840501148123,FLUA,1
4,2023-04-12 00:00:00,F,77,RIO DE JANEIRO,RJ,952900082028,FLUA,1
...,...,...,...,...,...,...,...,...
2387,2022-03-25,F,58,BRASILIA,DF,802200132711,COVID,0
2388,2022-03-27,F,57,TAGUATINGA,DF,804400986712,COVID,0
2389,2022-03-23,F,2,BRASILIA,DF,882901146941,COVID,0
2390,2022-03-25,F,0,SAO PAULO,SP,899701314661,COVID,0
2391,2022-03-22,M,1,SAO PAULO,SP,890401923764,COVID,0

## Gene S

In [16]:
gene_s_dfs = []
for df in dfs:

    if 'Gene S' not in df.columns.tolist():
        continue

    rename_dict = {}
    df_columns = df.columns.tolist() 
    if 'resultado' not in df_columns:
        
        if 'resultado_norm' in df_columns:
            rename_dict['resultado_norm'] = 'resultado'
        elif 'resultado_original' in df_columns:
            # Nenhum caso encontrado
            rename_dict['resultado_original'] = 'resultado'

    if 'requisicao' not in df_columns:
        if 'codigo_externo_do_paciente' in df_columns:
            rename_dict['codigo_externo_do_paciente'] = 'requisicao'

    gene_s_dfs.append(df.rename(columns=rename_dict, errors='ignore'))

### Valores únicos

- Regra: Atribuir 'thermo' a test_kit
- Regra: Atribuir '' a cidade_norm, uf_norm caso o valor seja 'SEM CIDADE', 'MUDOU', 'NAO_INFORMADO' ou 'NAOINFORMADO'
- Regra: Atribuir NT a todos os patógenos que não sejam SC2
- Regra: Atribuir '' a Gene N, Gene ORF e GENE S caso o resultado seja Neg
- Regra: Transformar o valor de Gene N, Gene ORF e GENE S em string com 1 casa decimal

In [17]:
# DÚVIDA
# for idx, row in dfL.iterrows():
#     result = dfL.loc[idx, 'resultado']
#     if result == 'NAO DETECTADO':
#         dfL.loc[idx, 'Gene N'] = ''
#         dfL.loc[idx, 'Gene ORF'] = ''
#         dfL.loc[idx, 'Gene S'] = ''
#     else: # if not reported
#         result = 'NA'
#         dfL.loc[idx, 'Gene N'] = str(round(float(dfL.loc[idx, 'Gene N']), 1))
#         dfL.loc[idx, 'Gene ORF'] = str(round(float(dfL.loc[idx, 'Gene ORF']), 1))
#         dfL.loc[idx, 'Gene S'] = str(round(float(dfL.loc[idx, 'Gene S']), 1))

In [18]:
gene_df = pd.concat(gene_s_dfs)
gene_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 407665 entries, 0 to 1816
Data columns (total 62 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   requisicao                       310536 non-null  object
 1   data                             407665 non-null  object
 2   data_de_nascimento               364174 non-null  object
 3   idade                            404276 non-null  object
 4   sexo                             380901 non-null  object
 5   teste                            407665 non-null  object
 6   data_do_resultado                165884 non-null  object
 7   data_de_liberacao                204885 non-null  object
 8   resultado_original               118319 non-null  object
 9   cidade_norm                      407665 non-null  object
 10  uf_norm                          407665 non-null  object
 11  regiao_norm                      407665 non-null  object
 12  resultado                        407665 non-null  object
 13  regiao_norm2                     362168 non-null  object
 14  positivo                         362168 non-null  object
 15  Gene N                           407665 non-null  object
 16  Gene ORF                         407665 non-null  object
 17  Gene S                           407665 non-null  object
 18  s_dropout                        384290 non-null  object
 19  material                         341816 non-null  object
 20  resultado_norm                   293410 non-null  object
 21  plataforma                       102285 non-null  object
 22  executor                         7089 non-null    object
 23  data_prometida                   7089 non-null    object
 24  ponto_de_atendimento             27815 non-null   object
 25  bairro                           67944 non-null   object
 26  cep                              78919 non-null   object
 27  codigo_externo_do_paciente       11473 non-null   object
 28  codigo_externo_da_visita         4440 non-null    object
 29  divisao                          4440 non-null    object
 30  cod_hospitalar                   4440 non-null    object
 31  tipo_de_area                     4440 non-null    object
 32  localizacao                      4440 non-null    object
 33  paciente                         4440 non-null    object
 34  telefone                         4440 non-null    object
 35  cod_amostra                      4440 non-null    object
 36  posicao_no_container             4440 non-null    object
 37  nome_do_container                4440 non-null    object
 38  numero_do_container              4440 non-null    object
 39  status                           4440 non-null    object
 40  nivel_de_liberacao               9516 non-null    object
 41  responsavel_pela_liberacao       4440 non-null    object
 42  convenio                         4440 non-null    object
 43  numero_do_convenio               4440 non-null    object
 44  amostras_primarias               4440 non-null    object
 45  cliente_de_laboratorio_apoiador  4440 non-null    object
 46  liberado_em_atraso               4440 non-null    object
 47  chave                            4440 non-null    object
 48  unidade_medida                   4440 non-null    object
 49  cep_dasa                         4440 non-null    object
 50  gliese_cidade                    4440 non-null    object
 51  dasa_cidade                      4440 non-null    object
 52  apoio_cidade                     4440 non-null    object
 53  gliese_uf                        4440 non-null    object
 54  dasa_uf                          4440 non-null    object
 55  apoio_uf                         4440 non-null    object
 56  cep_municipio                    4440 non-null    object
 57  cep_uf                           4440 non-null    object
 58  cep_municipio_dasa               4440 non-null    object
 59  cep_uf_dasa                      4440 non-null    object
 60  cidade_tratado                   4440 non-null    object
 61  uf_tratado                       4440 non-null    object
dtypes: object(62)
memory usage: 195.9+ MB

In [19]:
gene_df.columns

Index(['requisicao', 'data', 'data_de_nascimento', 'idade', 'sexo', 'teste',
       'data_do_resultado', 'data_de_liberacao', 'resultado_original',
       'cidade_norm', 'uf_norm', 'regiao_norm', 'resultado', 'regiao_norm2',
       'positivo', 'Gene N', 'Gene ORF', 'Gene S', 's_dropout', 'material',
       'resultado_norm', 'plataforma', 'executor', 'data_prometida',
       'ponto_de_atendimento', 'bairro', 'cep', 'codigo_externo_do_paciente',
       'codigo_externo_da_visita', 'divisao', 'cod_hospitalar', 'tipo_de_area',
       'localizacao', 'paciente', 'telefone', 'cod_amostra',
       'posicao_no_container', 'nome_do_container', 'numero_do_container',
       'status', 'nivel_de_liberacao', 'responsavel_pela_liberacao',
       'convenio', 'numero_do_convenio', 'amostras_primarias',
       'cliente_de_laboratorio_apoiador', 'liberado_em_atraso', 'chave',
       'unidade_medida', 'cep_dasa', 'gliese_cidade', 'dasa_cidade',
       'apoio_cidade', 'gliese_uf', 'dasa_uf', 'apoio_uf', 'cep_municipio',
       'cep_uf', 'cep_municipio_dasa', 'cep_uf_dasa', 'cidade_tratado',
       'uf_tratado'],
      dtype='object')

In [20]:
[
    "requisicao",
    "data",
    "data_de_nascimento",
    "idade",
    "sexo",
    "resultado",
    "resultado_norm",
    "resultado_original",
    "cidade_norm",
    "uf_norm",
    "positivo",
    "Gene N",
    "Gene ORF",
    "Gene S",
]

['requisicao',
 'data',
 'data_de_nascimento',
 'idade',
 'sexo',
 'resultado',
 'resultado_norm',
 'resultado_original',
 'cidade_norm',
 'uf_norm',
 'positivo',
 'Gene N',
 'Gene ORF',
 'Gene S']

In [21]:
gene_df['positivo']

0        True
1       False
2        True
3       False
4       False
        ...
1812     True
1813     True
1814    False
1815    False
1816    False
Name: positivo, Length: 407665, dtype: object

In [22]:
{
    'POSITIVO (SEM CT)': 'Pos',
    'NEGATIVO': 'Neg',
    'DETECTADO': 'Pos',
    'NÃO DETECTADO': 'Neg',
}

gene_df['resultado'].unique()

array(['POSITIVO (SEM CT)', 'NEGATIVO', 'DETECTADO', 'NAO DETECTADO'],
      dtype=object)

In [23]:
gene_df['sexo'].unique()

array(['MASCULINO', 'FEMININO', 'INDETERMINADO', 'None', nan, ''],
      dtype=object)

In [24]:
gene_df['teste'].unique()

array(['DETECCAO QUALITATIVA DE CORONAVIRUS (2019-NCOV)'], dtype=object)

In [25]:
gene_df['requisicao'].replace(re.compile('[0-9]'), 'x').unique()

array(['xxxxxxxxxx', 'xxxxxxxxx', 'xxxxxxxx', 'xxxxx', 'xxxxxxx',
       'xxxxxx', 'xxxx.xxxx.xxxx', nan, 'xxxx', 'xxx'], dtype=object)

In [31]:
gene_df['idade'].fillna('-1').unique()

array(['32', '41', '25', '22', '45', '34', '30', '54', '88', '28', '33',
       '7', '1', '40', '46', '26', '59', '65', '73', '11', '27', '35',
       '42', '10', '38', '37', '58', '36', '21', '19', '29', '50', '83',
       '24', '39', '4', '8', '44', '79', '53', '20', '2', '66', '55',
       '16', '31', '62', '47', '48', '56', '64', '43', '52', '3', '0',
       '14', '23', '51', '49', '67', '9', '70', '6', '63', '86', '72',
       '12', '18', '60', '13', '17', '74', '5', '68', '75', '61', '57',
       '69', '71', '94', '96', '82', '81', '15', '91', '84', '85', '77',
       '92', '80', '76', '122', '89', '93', '78', '90', '87', '95', '98',
       '97', '102', '99', '103', '101', '1993', '100', '104', '120', '',
       '807', '2012', '107', '822', '1713', '123', '106', '105', '114',
       '945', '544', '170'], dtype=object)

In [26]:
(
    gene_df
    
    .assign(duplicated=lambda df: df.duplicated(subset=['requisicao']))
    .groupby('requisicao')
    .agg({'duplicated': 'sum'})
    .assign(duplicated=lambda df: df['duplicated'] + 1)
    .sort_values('duplicated', ascending=False)
    .query('duplicated > 1')
    # ['duplicated']
    # .unique()
)

            duplicated
requisicao
7662439349          24
7660500854          21
1223194821          15
6163693888          15
6180840616          12
...                ...
6173397367           2
7661248824           2
59010902             2
7662453654           2
10007835             2

[7677 rows x 1 columns]

In [ ]:
12222

In [27]:
gene_df['idade']

0        32
1        41
2        25
3        22
4        45
       ...
1812    NaN
1813    NaN
1814    NaN
1815    NaN
1816    NaN
Name: idade, Length: 407665, dtype: object

In [28]:
gene_df.query("requisicao == '7677105586'")

,requisicao,data,data_de_nascimento,idade,sexo,teste,data_do_resultado,data_de_liberacao,resultado_original,cidade_norm,...,apoio_cidade,gliese_uf,dasa_uf,apoio_uf,cep_municipio,cep_uf,cep_municipio_dasa,cep_uf_dasa,cidade_tratado,uf_tratado
1030,7677105586,2022-10-10 09:46:50+00:00,1974-10-14,47,MASCULINO,DETECCAO QUALITATIVA DE CORONAVIRUS (2019-NCOV),2022-10-11 19:55:37+00:00,NaN,NaN,SAOPAULO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2612,7677105586,2022-08-21 08:07:38+00:00,1974-10-14,47,MASCULINO,DETECCAO QUALITATIVA DE CORONAVIRUS (2019-NCOV),2022-08-22 19:02:51+00:00,NaN,NaN,SAOPAULO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Problema: Duplicatas de id requisicao

Solução: Remover duplicatas com drop duplicates