python scripts/reformat_sabin.py --datadir data --rename data/rename_columns.xlsx --correction data/fix_values.xlsx --output combined_test.tsv

In [37]:
import pandas as pd

In [38]:
df_combined = pd.read_csv('../combined_test_einstein.tsv', sep='\t')

In [39]:
df_sabin_covid = pd.read_excel(
    './../data/SABIN/20230711_SABIN_Covid_2023ateSE27.xlsx'
)

df_dict = pd.read_excel(
    './../data/SABIN/20230711_SABIN_paineis_2023ateSE27.xlsx', 
    index_col=None, header=0, 
    sheet_name=None, 
    dtype='str'
)

df_paineis = pd.DataFrame()
for sheet in df_dict.keys():
    if sheet.startswith('EXAME'):
        # einstein
        continue
    
    df_paineis = df_paineis.append(df_dict[sheet].assign(ExcelSheet=sheet))

In [40]:
df_full_raw = df_sabin_covid.append(df_paineis)

## Duplicatas

In [41]:
df_duplicates = (
    df_combined
    # .query("test_kit == 'unknown'")
    .assign( one=1 )
    .groupby(['test_id'])
    .agg(num_duplicates=('one', 'sum'))
    .query("num_duplicates > 1")
    .assign(num_duplicates=lambda x: x['num_duplicates']-1)
)


print( df_duplicates['num_duplicates'].sum(), df_duplicates['num_duplicates'].max(), df_duplicates['num_duplicates'].min() )
df_duplicates.sort_values('num_duplicates', ascending=False).head(10)

10587 2 1

               num_duplicates
test_id
2022020007232               2
2023199007171               2
2022027000933               2
2022020008542               2
2022127002379               2
2022274007730               2
2022013011347               2
2022017006199               2
2022025007903               2
2022102013848               2

In [42]:
df_os_multiple_tests = (
    df_combined
    .groupby('test_id')
    .agg(kits=('test_kit',lambda x: ','.join(x.tolist())))
    .query("kits.str.contains(',')", engine='python') 
)

In [43]:
df_os_multiple_tests.head(10)

                        kits
test_id
2022001001776  test_1,test_2
2022001002045  test_1,test_2
2022001002070  test_1,test_2
2022001002079  test_1,test_2
2022001002390  test_1,test_2
2022001002836  test_1,test_2
2022001002930  test_1,test_2
2022001002950  test_1,test_2
2022001003041  test_1,test_2
2022001003080  test_1,test_2

In [44]:
df_combined.columns

Index(['lab_id', 'test_id', 'test_kit', 'patient_id', 'sample_id', 'state',
       'location', 'date_testing', 'epiweek', 'age', 'sex', 'FLUA_test_result',
       'Ct_FluA', 'FLUB_test_result', 'Ct_FluB', 'VSR_test_result', 'Ct_VSR',
       'SC2_test_result', 'Ct_geneE', 'Ct_geneN', 'Ct_geneS', 'Ct_ORF1ab',
       'Ct_RDRP', 'geneS_detection', 'META_test_result', 'RINO_test_result',
       'PARA_test_result', 'ADENO_test_result', 'BOCA_test_result',
       'COVS_test_result', 'ENTERO_test_result', 'BAC_test_result'],
      dtype='object')

## Uniqueness

In [45]:
if 'unknown' in df_combined['test_kit'].unique():
    print('WARNING! unknown test kits found')

df_combined['test_kit'].unique()

array(['test_1', 'test_3', 'test_2', 'test_4'], dtype=object)

In [46]:
df_combined['state'].unique()

array(['SÃO PAULO', 'RIO DE JANEIRO', 'GOIÁS'], dtype=object)

In [47]:
df_combined['location'].unique()

array(['GUARULHOS', 'SÃO PAULO', 'RIO DE JANEIRO', 'ALPHAVILLE',
       'SOROCABA', 'GOIÂNIA'], dtype=object)

In [48]:
df_combined['date_testing'].max(), df_combined['date_testing'].min()

('2023-07-24', '2022-01-01')

In [49]:
df_combined['age'].unique(), df_combined['age'].min(), df_combined['age'].max()

(array([ 61,  53,  58,  49,  17,  56,  12,  16,  45,  26,  54,  14,  23,
         36,  48,  51,  50,  82,  59,  15,  55,  22,  35,  27,  60,  46,
          1,   3,  24,  37,  28,  42,  20,  41,  10,   8,  21,  40,   4,
         39,  34,  33,   6,  30,  87,  43,   7,  32,  38,  66,  67,  74,
         25,  79,  65,  19,  31,  29,  11,   9,  62,  44,   2,  47,  57,
         18,  52,  84,  64,   5,  69,  70,  75,  63,  71,  72,  77,  13,
         86,  73,  68,  93,  83,  80,  85,  76,  89,  94,  95,  81,  97,
         96,  88,  78,  91, 101, 100,  92,  99,  98,  90, 103, 102, 110,
        104, 107, 108, 105,   0, 106, 112]),
 0,
 112)

In [50]:
df_combined['sex'].unique()

array(['M', 'F', 'I'], dtype=object)

In [51]:
for column in df_combined.columns:
    if column.endswith('_result'):
        print(column, df_combined[column].unique())

FLUA_test_result ['NT' 'Neg' 'Pos']
FLUB_test_result ['NT' 'Neg' 'Pos']
VSR_test_result ['NT' 'Neg' 'Pos']
SC2_test_result ['Neg' 'Pos' 'NT']
META_test_result ['NT']
RINO_test_result ['NT']
PARA_test_result ['NT']
ADENO_test_result ['NT']
BOCA_test_result ['NT']
COVS_test_result ['NT']
ENTERO_test_result ['NT']
BAC_test_result ['NT']

In [52]:
for col in df_combined.columns:
    if col.endswith('_result'):
        print(col)

FLUA_test_result
FLUB_test_result
VSR_test_result
SC2_test_result
META_test_result
RINO_test_result
PARA_test_result
ADENO_test_result
BOCA_test_result
COVS_test_result
ENTERO_test_result
BAC_test_result

## Inconsistencies

In [53]:
df_combined.columns

Index(['lab_id', 'test_id', 'test_kit', 'patient_id', 'sample_id', 'state',
       'location', 'date_testing', 'epiweek', 'age', 'sex', 'FLUA_test_result',
       'Ct_FluA', 'FLUB_test_result', 'Ct_FluB', 'VSR_test_result', 'Ct_VSR',
       'SC2_test_result', 'Ct_geneE', 'Ct_geneN', 'Ct_geneS', 'Ct_ORF1ab',
       'Ct_RDRP', 'geneS_detection', 'META_test_result', 'RINO_test_result',
       'PARA_test_result', 'ADENO_test_result', 'BOCA_test_result',
       'COVS_test_result', 'ENTERO_test_result', 'BAC_test_result'],
      dtype='object')

Verificando se um mesmo test_id + test_kit apresentam mais de um resultado para um mesmo patógeno

In [54]:
agg_test_rules = {
    col+'_kit': (col, lambda x: ','.join(x.tolist()))
    for col in df_combined.columns
    if col.endswith('_result')
}

df_os_non_contraditory_test_results = (
    df_combined
    .groupby(['test_id', 'test_kit'])
    .agg(**agg_test_rules)
)

In [55]:
for col in df_os_non_contraditory_test_results.columns:
    if col.endswith('_kit'):
        print(col, df_os_non_contraditory_test_results[col].unique())
        # Devem ser apenas ['NT' 'Neg' 'Pos']

FLUA_test_result_kit ['NT' 'Neg' 'Pos']
FLUB_test_result_kit ['NT' 'Neg' 'Pos']
VSR_test_result_kit ['NT' 'Neg' 'Pos']
SC2_test_result_kit ['Neg' 'Pos' 'NT']
META_test_result_kit ['NT']
RINO_test_result_kit ['NT']
PARA_test_result_kit ['NT']
ADENO_test_result_kit ['NT']
BOCA_test_result_kit ['NT']
COVS_test_result_kit ['NT']
ENTERO_test_result_kit ['NT']
BAC_test_result_kit ['NT']

Verificando se todos os Ids originais etão presentes no arquivo final

In [56]:
set_test_ids_final_df = set(df_combined['test_id'])
set_test_ids_raw_data = set(df_full_raw['OS'])

In [57]:
# Testar se todos os test_ids da planilha original estão na planilha final
# deve retornar um set vazio
set_test_ids_raw_data.difference(set_test_ids_final_df)

{'830-66532-15798',
 '936-66593-16207',
 '223-66548-3453',
 '833-66631-6546',
 '1269-66494-7745',
 '054-66502-11870',
 '834-66478-16826',
 '960-66521-18899',
 '575-66557-18405',
 '589-66560-12090',
 '743-66597-15489',
 '562-66624-14484',
 '960-66528-12934',
 '237-66618-8854',
 '959-66647-12030',
 '586-66494-19404',
 '830-66659-17108',
 '772-66555-17600',
 '221-66643-2095',
 '1269-66625-66',
 '223-66475-569',
 '566-66656-6493',
 '570-66505-11529',
 '142-66604-11313',
 '138-66533-14150',
 '770-66562-20301',
 '589-66542-62',
 '466-66484-13542',
 '960-66613-15141',
 '960-66598-21848',
 '959-66640-4488',
 '221-66527-13358',
 '589-66530-15877',
 '025-66513-5855',
 '942-66648-8496',
 '584-66563-19902',
 '977-66659-18532',
 '223-66581-11409',
 '350-66513-10423',
 '844-66618-21328',
 '1858-66607-14839',
 '1041-66540-14831',
 '939-66566-2646',
 '844-66537-15537',
 '025-66640-15004',
 '772-66630-18855',
 '589-66610-22156',
 '1269-66510-2286',
 '901-66614-9370',
 '206-66591-17765',
 '936-66628-14932',
 '054-66523-11233',
 '054-66548-13180',
 '1858-66564-21747',
 '772-66519-17588',
 '206-66549-18673',
 '555-66508-18089',
 '650-66543-10107',
 '361-66592-10359',
 '221-66533-20935',
 '960-66531-1499',
 '565-66609-16714',
 '743-66631-10710',
 '1576-66484-17090',
 '1409-66617-6147',
 '053-66495-10831',
 '844-66538-1908',
 '413-66494-12983',
 '170-66610-17941',
 '959-66492-16437',
 '555-66529-18067',
 '1270-66476-6572',
 '960-66518-15318',
 '206-66590-19008',
 '948-66614-14088',
 '960-66569-21603',
 '570-66514-5555',
 '022-66627-14014',
 '122-66588-15767',
 '027-66619-14121',
 '206-66600-13038',
 '032-66511-18012',
 '242-66642-10287',
 '562-66561-5930',
 '324-66602-7731',
 '324-66568-8805',
 '833-66578-17501',
 '151-66542-19019',
 '743-66575-21309',
 '650-66630-12626',
 '939-66617-14519',
 '027-66579-898',
 '977-66561-1364',
 '053-66582-15806',
 '223-66659-9643',
 '151-66487-14432',
 '086-66532-7586',
 '1939-66542-19418',
 '1409-66555-20228',
 '523-66543-14802',
 '151-66589-16258',
 '001-66594-1588',
 '170-66586-8118',
 '221-66513-12420',
 '959-66570-5608',
 '972-66490-18444',
 '053-66479-11717',
 '960-66478-11541',
 '649-66598-20804',
 '221-66650-2180',
 '577-66534-18260',
 '044-66560-10757',
 '022-66610-1292',
 '1417-66538-2435',
 '397-66508-10015',
 '944-66647-19031',
 '1409-66516-83',
 '237-66508-183',
 '561-66520-16644',
 '1087-66507-18682',
 '586-66532-11804',
 '651-66547-13680',
 '001-66561-16198',
 '145-66569-15896',
 '221-66571-3392',
 '830-66648-5755',
 '242-66563-5681',
 '242-66588-10771',
 '074-66611-9529',
 '1491-66569-9401',
 '584-66477-12304',
 '651-66570-9725',
 '936-66632-20770',
 '865-66655-11266',
 '589-66532-15545',
 '946-66527-5579',
 '589-66560-13317',
 '960-66607-14816',
 '960-66552-2131',
 '833-66620-14467',
 '939-66576-17611',
 '742-66612-16885',
 '792-66483-2592',
 '1858-66483-18500',
 '698-66623-15463',
 '013-66581-12870',
 '1576-66561-15472',
 '960-66478-8345',
 '126-66554-7691',
 '223-66581-20700',
 '775-66502-1629',
 '1565-66576-9383',
 '1043-66604-14426',
 '122-66498-13373',
 '122-66476-2201',
 '770-66554-18229',
 '781-66592-14895',
 '1467-66494-12103',
 '936-66511-16389',
 '742-66569-20535',
 '589-66534-131',
 '170-66483-8070',
 '743-66567-11688',
 '977-66591-19801',
 '562-66575-12643',
 '770-66484-12562',
 '047-66584-20949',
 '589-66496-2039',
 '1473-66502-12462',
 '463-66532-14949',
 '108-66519-19794',
 '047-66641-14609',
 '589-66494-15044',
 '026-66623-10605',
 '561-66652-10606',
 '1619-66589-15965',
 '027-66591-8591',
 '977-66486-14505',
 '767-66602-17135',
 '939-66660-14654',
 '1562-66485-16621',
 '476-66556-17166',
 '145-66506-18833',
 '743-66508-20936',
 '044-66488-7828',
 '221-66589-17690',
 '960-66591-14276',
 '145-66542-15620',
 '830-66563-3069',
 '577-66499-20789',
 '743-66516-14893',
 '523-66528-15332',
 '032-66576-14086',
 '053-66484-16804',
 '899-66506-542',
 '1409-66522-18606',
 '491-66533-13200',
 '122-66582-2598',
 '049-66604-14801',
 '340-66557-17128',
 '1953-66605-14700',
 '054-66611-19946',
 '939-66630-19266',
 '001-66524-1280',
 '586-66621-15115',
 '1409-66578-21830',
 '1858-66614-14595',
 '844-66595-3823',
 '013-66570-7066',
 '977-66592-8932',
 '936-66579-16023',
 '321-66589-12242',
 '589-66661-98',
 '960-66512-19858',
 '959-66543-15236',
 '589-66643-2461',
 '397-66589-11062',
 '584-66560-19892',
 '025-66569-10665',
 '584-66516-7524',
 '772-66651-13366',
 '772-66486-18563',
 '237-66588-21337',
 '743-66481-8604',
 '570-66542-6425',
 '566-66479-5166',
 '566-66534-15087',
 '977-66568-15692',
 '145-66590-6056',
 '977-66590-15655',
 '566-66478-14580',
 '047-66549-16930',
 '770-66592-1906',
 '944-66626-5162',
 '242-66633-3450',
 '882-66497-13109',
 '242-66609-18307',
 '1469-66537-12842',
 '122-66616-15562',
 '1610-66633-3795',
 '221-66494-18379',
 '944-66609-3674',
 '565-66569-18976',
 '047-66496-1522',
 '044-66575-14882',
 '1576-66580-1544',
 '936-66537-18',
 '174-66651-14101',
 '1858-66651-15732',
 '223-66486-18361',
 '1858-66580-3282',
 '121-66539-14645',
 '031-66589-13695',
 '340-66487-15770',
 '371-66593-9753',
 '960-66645-20433',
 '772-66524-1066',
 '939-66659-14296',
 '050-66661-16022',
 '044-66625-14865',
 '942-66529-15550',
 '960-66483-6226',
 '174-66617-19291',
 '743-66554-21803',
 '960-66518-12908',
 '174-66518-13309',
 '991-66555-179',
 '939-66548-11395',
 '1408-66621-14555',
 '221-66580-2934',
 '053-66651-11276',
 '083-66491-16077',
 '589-66620-17730',
 '566-66569-17384',
 '121-66592-19431',
 '936-66603-23090',
 '525-66584-11836',
 '844-66587-2349',
 '772-66515-15704',
 '032-66486-9745',
 '572-66659-15420',
 '053-66509-11574',
 '449-66540-18060',
 '053-66511-11638',
 '122-66550-12092',
 '589-66606-7983',
 '742-66485-19554',
 '449-66500-11010',
 '939-66564-20602',
 '589-66629-1535',
 '616-66498-19434',
 '035-66512-13033',
 '223-66531-2584',
 '1409-66503-1276',
 '1588-66532-6428',
 '124-66529-9077',
 '237-66494-141',
 '944-66634-11655',
 '034-66582-16301',
 '001-66602-18317',
 '770-66554-16394',
 '200-66556-14805',
 '049-66563-16587',
 '1269-66598-8524',
 '960-66477-14243',
 '566-66528-12263',
 '221-66474-4119',
 '142-66544-11707',
 '237-66556-16408',
 '047-66596-11437',
 '944-66617-15774',
 '589-66552-2471',
 '047-66638-16817',
 '901-66529-14681',
 '743-66645-15832',
 '343-66519-16430',
 '206-66527-9711',
 '025-66541-15313',
 '772-66533-20916',
 '237-66628-14961',
 '833-66612-3343',
 '970-66661-16697',
 '045-66624-17650',
 '566-66626-11673',
 '237-66588-20490',
 '1953-66626-18022',
 '743-66563-12530',
 '844-66576-22396',
 '960-66582-188',
 '121-66658-1168',
 '616-66490-14443',
 '939-66569-15598',
 '321-66602-16870',
 '074-66600-6023',
 '466-66658-15743',
 '827-66564-20854',
 '1409-66553-14279',
 '027-66564-8699',
 '1953-66611-9196',
 '221-66652-20304',
 '119-66520-16828',
 '151-66519-11673',
 '221-66598-5506',
 '223-66540-14893',
 '102-66511-7569',
 '527-66578-3216',
 '565-66605-11987',
 '1858-66556-14054',
 '570-66553-18878',
 '936-66568-22832',
 '179-66479-6148',
 '018-66527-8360',
 '844-66632-11626',
 '1409-66564-19783',
 '124-66555-5913',
 '770-66561-6868',
 '027-66600-8833',
 '242-66535-4463',
 '584-66605-20343',
 '463-66589-7121',
 '033-66612-8842',
 '340-66612-10451',
 '1858-66615-2877',
 '049-66652-1420',
 '223-66514-18145',
 '844-66589-18743',
 '177-66603-9559',
 '944-66511-19839',
 '585-66515-19503',
 '083-66603-15623',
 '887-66512-16826',
 '223-66514-14961',
 '237-66602-20917',
 '755-66582-21951',
 '939-66560-15988',
 '086-66562-12595',
 '119-66652-18046',
 '001-66502-13502',
 '960-66560-14764',
 '027-66644-12752',
 '743-66502-13377',
 '108-66518-8186',
 '1953-66561-16502',
 '960-66553-11672',
 '1409-66572-1333',
 '1858-66589-22742',
 '221-66508-20556',
 '1409-66523-12239',
 '649-66596-10802',
 '589-66568-22363',
 '797-66542-6899',
 '939-66604-15272',
 '001-66568-21470',
 '830-66532-13193',
 '074-66606-6330',
 '1375-66621-10878',
 '221-66628-14741',
 '960-66516-15443',
 '768-66546-3776',
 '999-66549-20159',
 '048-66528-15422',
 '743-66546-7237',
 '743-66577-21430',
 '830-66661-16086',
 '237-66575-21085',
 '960-66602-21607',
 '221-66614-14156',
 '524-66478-12432',
 '1269-66641-5904',
 '026-66625-8860',
 '396-66569-15728',
 '960-66623-12911',
 '584-66597-18868',
 '142-66627-16775',
 '206-66480-11135',
 '026-66505-18419',
 '566-66548-11784',
 '1545-66484-11670',
 '844-66557-18041',
 '1858-66518-9406',
 '901-66614-2304',
 '943-66481-11554',
 '221-66590-9929',
 '050-66577-13970',
 '743-66499-12278',
 '086-66542-17755',
 '242-66566-1299',
 '223-66572-11798',
 '001-66507-16194',
 '1269-66557-24',
 '1939-66575-13470',
 '221-66542-20094',
 '031-66562-18986',
 '180-66520-16489',
 '1408-66541-14942',
 '589-66556-16692',
 '150-66555-1945',
 '566-66626-16337',
 '833-66515-14129',
 '939-66631-15602',
 '901-66574-14841',
 '466-66598-17086',
 '053-66480-11768',
 '575-66588-18980',
 '1270-66610-16952',
 '1409-66625-16120',
 '1831-66645-20758',
 '122-66550-13115',
 '030-66558-13304',
 '358-66586-11030',
 '049-66533-14030',
 '960-66654-5595',
 '936-66595-3965',
 '651-66529-14300',
 '770-66557-10240',
 '108-66577-18254',
 '953-66592-20169',
 '413-66605-8062',
 '177-66659-14100',
 '1027-66634-8274',
 '200-66478-12295',
 '566-66528-19513',
 '1953-66576-19983',
 '561-66479-8771',
 '354-66481-3554',
 '570-66519-17280',
 '221-66593-10629',
 '001-66541-21162',
 '047-66598-8792',
 '546-66506-11196',
 '939-66497-15526',
 '145-66484-13389',
 '998-66616-20379',
 '589-66661-8738',
 '242-66660-18444',
 '589-66622-152',
 '743-66598-3878',
 '122-66553-17786',
 '939-66623-18902',
 '959-66569-14440',
 '206-66504-11360',
 '939-66567-19744',
 '242-66549-17567',
 '1562-66582-3433',
 '221-66542-19973',
 '017-66613-17636',
 '321-66476-8627',
 '1953-66591-18133',
 '237-66602-1700',
 '237-66525-4738',
 '834-66609-17899',
 '743-66631-19999',
 '145-66612-14882',
 '939-66651-14513',
 '466-66582-19919',
 '237-66494-19375',
 '847-66479-16622',
 '103-66661-8888',
 '1656-66521-9547',
 '221-66580-2226',
 '417-66556-13166',
 '108-66579-10985',
 '1605-66631-16319',
 '565-66638-10552',
 '145-66490-14805',
 '1939-66563-18957',
 '650-66624-3658',
 '589-66557-21312',
 '770-66499-12436',
 '770-66631-15692',
 '074-66641-17803',
 '206-66618-18760',
 '1656-66578-6092',
 '830-66652-10829',
 '830-66533-13244',
 '575-66534-10530',
 '575-66539-14666',
 '026-66561-20309',
 '977-66547-15666',
 '744-66584-21563',
 '570-66480-16448',
 '944-66484-19842',
 '939-66575-15746',
 '035-66579-11003',
 '1858-66541-10227',
 '830-66483-8482',
 '1270-66638-11945',
 '1469-66544-13731',
 '797-66521-9162',
 '049-66589-19005',
 '763-66644-17008',
 '032-66592-18823',
 '844-66619-10563',
 '1269-66535-20512',
 '589-66508-165',
 '466-66536-16744',
 '561-66619-12620',
 '386-66515-9230',
 '242-66579-16316',
 '589-66597-3296',
 '037-66618-570',
 '031-66560-5912',
 '032-66586-11022',
 '086-66511-492',
 '531-66584-16234',
 '047-66601-334',
 '743-66490-16644',
 '053-66638-974',
 '121-66588-9676',
 '963-66476-7348',
 '051-66579-14612',
 '1409-66578-20553',
 '221-66479-9658',
 '970-66598-19802',
 '151-66617-15268',
 '408-66619-11059',
 '206-66535-16910',
 '589-66624-12953',
 '371-66533-14049',
 '321-66648-12511',
 '589-66603-17956',
 '959-66568-21789',
 '120-66548-18212',
 '589-66569-5210',
 '221-66583-22396',
 '122-66568-2059',
 '830-66540-6011',
 '086-66484-1721',
 '047-66596-13899',
 '237-66602-19373',
 '939-66642-13293',
 '1647-66557-12222',
 '527-66478-11226',
 '103-66512-17576',
 '743-66529-20998',
 '939-66551-15539',
 '589-66561-21760',
 '565-66616-14598',
 '589-66659-20134',
 '927-66550-20110',
 '027-66570-21318',
 '145-66578-17276',
 '054-66610-20000',
 '013-66527-9535',
 '397-66626-15332',
 '743-66543-3820',
 '242-66561-7561',
 '562-66563-8752',
 '1066-66570-8779',
 '495-66591-15269',
 '013-66640-11516',
 '1409-66610-22649',
 '562-66578-17974',
 '960-66620-19416',
 '767-66619-18368',
 '1556-66495-7646',
 '413-66596-7730',
 '944-66509-2443',
 '223-66561-17058',
 '844-66634-13875',
 '939-66511-16229',
 '742-66476-816',
 '1255-66556-11570',
 '237-66612-20850',
 '221-66587-1410',
 '1858-66611-17041',
 '960-66624-19857',
 '546-66506-11027',
 '1269-66625-12202',
 '045-66645-17034',
 '936-66582-21931',
 '145-66581-10089',
 '1398-66597-15062',
 '589-66532-14312',
 '960-66547-11749',
 '242-66555-12149',
 '237-66591-104',
 '150-66474-2422',
 '688-66588-16459',
 '145-66485-11500',
 '770-66575-16678',
 '001-66582-21508',
 '565-66564-17706',
 '044-66484-18320',
 '589-66619-19885',
 '939-66521-17961',
 '783-66547-5172',
 '960-66558-16155',
 '770-66583-12327',
 '1953-66661-15654',
 '847-66574-2083',
 '1374-66661-11808',
 '1939-66556-16125',
 '025-66609-2892',
 '122-66478-13108',
 '466-66515-12985',
 '1374-66515-15275',
 '844-66556-16756',
 '103-66582-20172',
 '844-66620-14899',
 '044-66549-9396',
 '145-66651-16066',
 '026-66529-3180',
 '121-66500-14810',
 '743-66474-4559',
 '584-66584-21813',
 '844-66588-16846',
 '035-66591-18531',
 '960-66505-20880',
 '120-66620-11760',
 '562-66646-10115',
 '1409-66660-14551',
 '025-66613-9348',
 '939-66599-46',
 '960-66629-2096',
 '960-66558-16022',
 '121-66562-16730',
 '763-66575-14958',
 '413-66619-14518',
 '1409-66552-1230',
 '1374-66548-10324',
 '150-66611-12968',
 '126-66522-13713',
 '206-66588-13509',
 '024-66638-16126',
 '589-66527-8343',
 '177-66515-17870',
 '119-66578-11672',
 '237-66560-11621',
 '122-66590-14569',
 '121-66618-16459',
 '586-66638-19044',
 '1858-66645-13556',
 '150-66562-10172',
 '589-66507-20418',
 '145-66528-17066',
 '1858-66562-21014',
 '397-66487-17009',
 '565-66535-19153',
 '221-66481-7626',
 '1576-66483-11390',
 '970-66637-11095',
 '1469-66660-14917',
 '589-66484-16013',
 '035-66532-17309',
 '833-66547-6724',
 '1858-66595-3865',
 '960-66577-19542',
 '772-66651-16171',
 '047-66494-6050',
 '1270-66609-7024',
 '237-66480-8377',
 '449-66597-15652',
 '122-66535-17439',
 '589-66540-21652',
 '145-66549-11423',
 '991-66587-2798',
 '960-66623-8547',
 '589-66619-4539',
 '047-66510-411',
 '466-66515-11022',
 '939-66618-11917',
 '844-66538-2563',
 '200-66567-10019',
 '589-66624-7877',
 '1364-66521-13746',
 '1269-66610-14253',
 '145-66547-13169',
 '206-66589-10157',
 '051-66563-14394',
 '170-66632-16560',
 '142-66575-8641',
 '237-66661-18362',
 '047-66611-14710',
 '960-66556-21149',
 '221-66487-18801',
 '960-66556-21720',
 '1576-66553-4818',
 '939-66573-2296',
 '001-66569-10267',
 '936-66530-16541',
 '944-66608-1668',
 '035-66625-14471',
 '1274-66536-19674',
 '136-66494-13404',
 '237-66485-19680',
 '142-66564-11680',
 '165-66564-12018',
 '590-66614-14110',
 '589-66574-15926',
 '742-66567-4514',
 '977-66602-2540',
 '049-66562-12254',
 '242-66479-958',
 '050-66564-19056',
 '589-66595-1013',
 '1953-66581-16750',
 '180-66540-17240',
 '242-66621-15116',
 '223-66542-19966',
 '1269-66552-3296',
 '960-66540-6251',
 '262-66632-16689',
 '944-66621-87',
 '901-66540-20551',
 '577-66621-13001',
 '589-66600-8784',
 '001-66551-15178',
 '1858-66576-11907',
 '121-66511-4677',
 '150-66624-15624',
 '589-66478-17352',
 '847-66617-18808',
 '570-66480-14442',
 '939-66514-5146',
 '743-66542-11726',
 '566-66556-9876',
 '103-66534-8199',
 '562-66479-14892',
 '747-66616-14916',
 '559-66609-14635',
 '022-66535-12372',
 '939-66649-11316',
 '466-66492-15749',
 '223-66517-2823',
 '027-66569-20836',
 '960-66611-7441',
 '340-66648-15981',
 '221-66572-11353',
 '960-66483-11668',
 '561-66609-17600',
 '830-66521-14873',
 '240-66586-14098',
 '939-66605-5956',
 '223-66488-13441',
 '844-66660-13361',
 '047-66576-15012',
 '397-66479-3774',
 '960-66501-17685',
 '1611-66540-13828',
 '026-66477-9590',
 '1270-66563-20660',
 '959-66530-2591',
 '022-66568-14061',
 '589-66608-670',
 '493-66609-16739',
 '223-66611-18802',
 '050-66651-6315',
 '901-66659-15135',
 '242-66520-20440',
 '844-66562-6907',
 '566-66509-7002',
 '589-66536-19950',
 '199-66515-12421',
 '151-66582-19997',
 '525-66478-9223',
 '991-66571-657',
 '174-66561-18276',
 '340-66540-11224',
 '413-66640-17808',
 '1576-66477-12352',
 '001-66572-11625',
 '550-66512-12854',
 '944-66655-14861',
 '1606-66478-11196',
 '001-66552-2093',
 '586-66572-11796',
 '944-66661-19074',
 '466-66619-12949',
 '570-66607-5151',
 '174-66651-14115',
 '237-66568-16994',
 '830-66478-15187',
 '053-66479-14521',
 '237-66524-1831',
 '371-66539-16541',
 '242-66585-3894',
 '960-66529-17787',
 '237-66566-2214',
 '833-66514-19600',
 '960-66658-11595',
 '221-66640-7594',
 '136-66536-5656',
 '896-66561-16080',
 '977-66582-17431',
 '033-66603-4456',
 '242-66556-9215',
 '743-66532-476',
 '1562-66576-13665',
 '237-66612-14899',
 '1545-66492-10847',
 '199-66505-15282',
 '960-66520-19637',
 '939-66575-18600',
 '121-66609-12301',
 '436-66614-6566',
 '053-66501-9029',
 '397-66618-14273',
 '032-66550-12388',
 '939-66530-15749',
 '589-66575-5655',
 '177-66660-15662',
 '200-66588-15366',
 '221-66628-14438',
 '199-66487-12904',
 '570-66582-16024',
 '033-66518-16847',
 '1409-66475-876',
 '760-66535-6970',
 '145-66588-7480',
 '527-66577-14736',
 '013-66616-16782',
 '936-66646-20456',
 '177-66557-9366',
 '001-66613-13342',
 '1562-66511-13375',
 '830-66485-11653',
 '1939-66627-10932',
 '589-66652-12169',
 '743-66605-12839',
 '026-66527-10224',
 '960-66575-14645',
 '830-66610-4844',
 '340-66630-5107',
 '584-66596-20959',
 '743-66492-20351',
 '1409-66650-2156',
 '1276-66651-12088',
 '466-66527-8787',
 '523-66533-18575',
 '242-66594-2034',
 '1572-66574-16281',
 '960-66519-20562',
 '649-66521-13707',
 '482-66549-15690',
 '901-66562-14776',
 '053-66605-14229',
 '1831-66529-16383',
 '013-66542-14846',
 '555-66561-12661',
 '493-66574-7531',
 '977-66575-16078',
 '413-66579-12761',
 '937-66581-21591',
 '001-66495-13333',
 '001-66506-536',
 '939-66581-10917',
 '1858-66607-12816',
 '027-66591-10405',
 '901-66612-10127',
 '1556-66530-11931',
 '589-66593-101',
 '237-66595-2270',
 '960-66511-19511',
 '970-66575-13567',
 '180-66486-15182',
 '1066-66522-14063',
 '944-66639-62',
 '1270-66483-12248',
 '221-66528-14696',
 '223-66494-19489',
 '772-66522-14003',
 '527-66588-15687',
 '053-66486-17621',
 '122-66550-6496',
 '122-66562-20148',
 '237-66616-19982',
 '944-66613-14864',
 '944-66639-17620',
 '221-66651-18490',
 '767-66599-11635',
 '032-66534-6131',
 '770-66557-16244',
 '031-66599-2541',
 '001-66609-18160',
 '223-66596-20993',
 '119-66596-7313',
 '1858-66548-21356',
 '027-66612-14900',
 '053-66513-17119',
 '151-66582-7395',
 '1656-66490-2346',
 '1610-66605-14071',
 '221-66653-19461',
 '145-66486-18019',
 '175-66490-5919',
 '145-66492-5944',
 '577-66539-17802',
 '1409-66516-15499',
 '492-66564-11986',
 '237-66598-12509',
 '885-66491-10267',
 '650-66514-15281',
 '025-66654-17191',
 '743-66542-13639',
 '354-66589-11264',
 '939-66585-3172',
 '049-66499-8508',
 '1858-66630-17468',
 '555-66548-17128',
 '1939-66476-7652',
 '122-66611-7617',
 '001-66542-12101',
 '927-66480-14024',
 '036-66616-12403',
 '321-66610-15208',
 '025-66493-19151',
 '936-66604-22081',
 '651-66513-13605',
 '939-66609-14299',
 '1408-66641-14346',
 '589-66593-16199',
 '492-66483-9965',
 '053-66494-15046',
 '449-66548-11024',
 '221-66488-6658',
 '589-66610-16448',
 '103-66553-16853',
 '001-66616-18668',
 '525-66562-7361',
 '206-66522-12256',
 '755-66504-18586',
 '936-66576-22604',
 '584-66639-12110',
 '001-66663-12623',
 '1409-66576-22512',
 '972-66493-16463',
 '830-66610-15264',
 '017-66639-10115',
 '177-66512-20487',
 '054-66595-2995',
 '1858-66484-20219',
 '242-66514-19687',
 '939-66553-21047',
 '844-66566-2995',
 '589-66575-22347',
 '001-66568-22365',
 '857-66481-9670',
 '043-66541-11933',
 '960-66589-19999',
 '032-66575-20844',
 '223-66610-22748',
 '049-66606-8839',
 '570-66618-19811',
 '848-66581-11918',
 '584-66540-18957',
 '221-66548-21461',
 '788-66620-7936',
 '526-66562-17588',
 '001-66476-9088',
 '972-66494-16111',
 '1565-66660-14955',
 '463-66535-1099',
 '830-66484-18966',
 '1066-66542-2703',
 '242-66596-19632',
 '1858-66641-19134',
 '017-66581-15701',
 '936-66618-21517',
 '053-66487-8425',
 ...}

In [58]:
# Verificar se há test_ids na planilha final que não estão na planilha original
# deve retornar um set vazio
set_test_ids_final_df.difference(set_test_ids_raw_data)

{2022032015360,
 2022032015362,
 2022032015363,
 2022032015364,
 2022032015365,
 2022075006981,
 2022183010308,
 2022032015370,
 2022334005265,
 2022032015378,
 2022334005266,
 2022075007000,
 2022032015386,
 2022075007003,
 2023068008485,
 2022032015398,
 2023068008486,
 2022032015402,
 2022032015403,
 2022032015407,
 2022032015409,
 2022183010355,
 2022183010356,
 2022334005302,
 2022334005304,
 2023068008504,
 2023068008506,
 2022032015420,
 2022075007041,
 2022032015427,
 2023068008516,
 2022334005318,
 2022032015433,
 2023068008524,
 2022032015451,
 2022032015452,
 2022183010400,
 2022226002046,
 2023068008574,
 2022226002053,
 2022183010448,
 2022334005395,
 2022334005396,
 2022334005398,
 2022226002075,
 2022183010470,
 2022226002092,
 2022183010487,
 2022183010492,
 2022075007166,
 2022183010505,
 2022183010508,
 2023068008653,
 2022183010514,
 2022183010521,
 2022075007200,
 2022075007212,
 2022334005484,
 2022226002168,
 2022334005499,
 2022075007244,
 2023068008723,
 2023068008724,
 2022334005525,
 2023068008726,
 2022075007256,
 2023068008741,
 2022334005543,
 2022075007280,
 2022334005571,
 2023068008776,
 2022334005582,
 2022334005596,
 2022334005607,
 2022226002280,
 2023068008815,
 2023068008816,
 2023068008817,
 2022075007346,
 2023068008818,
 2022075007348,
 2022075007349,
 2023068008826,
 2022075007367,
 2022334005639,
 2022334005648,
 2022334005651,
 2022075007387,
 2022075007388,
 2023068008864,
 2022226002338,
 2023068008877,
 2022075007408,
 2022075007409,
 2022075007412,
 2022075007417,
 2022334005691,
 2023068008899,
 2022226002375,
 2022226002379,
 2022226002380,
 2022226002397,
 2022334005728,
 2022075007480,
 2022334005756,
 2022334005760,
 2023068008969,
 2022075007498,
 2022075007499,
 2023068008975,
 2022075007513,
 2022266010737,
 2022075007517,
 2022266010739,
 2022075007527,
 2022075007528,
 2023068009014,
 2022075007548,
 2022075007563,
 2022075007565,
 2022075007567,
 2022334005841,
 2022075007576,
 2022075007581,
 2022334005864,
 2022334005866,
 2022334005867,
 2022075007607,
 2022075007608,
 2022075007616,
 2023068009092,
 2022075007641,
 2022334005921,
 2023068009126,
 2022075007661,
 2022226002620,
 2023068009151,
 2023068009152,
 2022075007691,
 2022075007692,
 2022334005967,
 2023068009178,
 2022075007712,
 2022075007713,
 2022334005989,
 2023068009206,
 2022226002681,
 2022334006014,
 2023068009215,
 2023068009219,
 2023068009222,
 2022226002698,
 2022075007760,
 2023068009237,
 2023068009239,
 2022226002713,
 2022334006043,
 2023068009245,
 2023068009246,
 2023068009252,
 2023068009257,
 2022075007786,
 2022075007790,
 2023068009269,
 2023068009270,
 2023111000886,
 2022226002757,
 2023111000901,
 2023068009290,
 2022334006092,
 2022075007826,
 2022075007828,
 2022075007835,
 2022226002798,
 2022226002799,
 2023068009326,
 2022075007857,
 2023068009327,
 2022075007859,
 2022334006132,
 2022075007866,
 2022334006147,
 2022226002822,
 2023068009352,
 2022226002836,
 2023068009374,
 2023068009375,
 2022075007908,
 2022226002853,
 2022334006182,
 2022226002857,
 2022226002862,
 2022334006200,
 2022226002873,
 2022075007935,
 2022226002884,
 2023068009417,
 2022075007947,
 2022075007948,
 2022226002891,
 2022226002894,
 2023068009422,
 2023068009426,
 2023068009432,
 2023068009434,
 2022075007975,
 2023068009453,
 2022075007985,
 2023068009461,
 2022334006266,
 2022075008004,
 2022075008013,
 2022075008014,
 2022226002963,
 2022226002964,
 2022075008022,
 2022075008034,
 2023068009525,
 2022226002999,
 2022226003003,
 2022075008070,
 2022075008073,
 2022226003027,
 2022075008085,
 2022334006362,
 2023068009562,
 2022226003037,
 2022226003038,
 2023068009568,
 2023068009571,
 2023068009574,
 2023153014970,
 2022266010855,
 2022075008132,
 2022334006410,
 2022226003083,
 2022075008140,
 2022226003086,
 2022226003087,
 2022226003088,
 2022226003095,
 2022226003097,
 2023068009628,
 2022075008164,
 2022075008165,
 2022226003116,
 2022075008175,
 2022075008179,
 2022075008185,
 2022226003133,
 2023111001278,
 2023068009670,
 2022226003150,
 2022075008207,
 2022334006492,
 2023068009692,
 2022226003168,
 2022334006499,
 2022334006500,
 2023068009700,
 2022226003175,
 2022266010880,
 2022266010881,
 2022334006518,
 2023068009723,
 2023068009724,
 2023068009730,
 2023068009744,
 2022075008274,
 2023068009751,
 2023068009752,
 2023068009758,
 2023068009762,
 2022226003241,
 2022075008298,
 2023068009769,
 2022334006574,
 2022075008306,
 2023068009782,
 2022075008311,
 2023068009783,
 2023068009788,
 2023068009793,
 2022226003268,
 2022226003274,
 2022075008336,
 2022226003280,
 2022075008338,
 2022226003282,
 2023111001428,
 2022226003287,
 2022075008348,
 2022226003299,
 2022226003306,
 2023133007410,
 2022226003314,
 2023068009847,
 2023068009848,
 2022075008378,
 2022075008396,
 2022334006675,
 2022075008404,
 2023068009876,
 2023068009879,
 2023068009882,
 2022226003357,
 2022334006690,
 2022334006702,
 2022226003376,
 2022075008438,
 2022226003401,
 2022075008461,
 2023068009934,
 2022075008474,
 2022226003425,
 2023068009955,
 2023068009957,
 2022334006763,
 2022226003444,
 2022226003445,
 2022075008503,
 2022226003448,
 2022226003455,
 2022226003456,
 2022075008517,
 2023068009992,
 2023068010001,
 2022226003488,
 2023068010019,
 2023068010021,
 2022226003508,
 2022075008569,
 2022334006843,
 2022226003522,
 2022075008581,
 2022075008582,
 2022226003533,
 2022075008590,
 2022226003535,
 2022334006874,
 2022075008610,
 2022075008611,
 2022226003559,
 2022334006887,
 2022226003561,
 2023068010089,
 2023111001713,
 2023133007463,
 2022075008635,
 2022334006909,
 2022075008644,
 2022075008663,
 2022075008664,
 2022075008665,
 2023068010135,
 2022075008673,
 2023111001771,
 2022226003628,
 2023068010157,
 2022075008686,
 2023111001772,
 2023111001784,
 2022226003651,
 2022075008708,
 2023068010180,
 2022075008710,
 2022334006982,
 2023068010181,
 2023111001795,
 2023068010188,
 2023068010198,
 2022075008734,
 2022334007006,
 2023068010214,
 2022075008744,
 2022118000370,
 2022118000371,
 2022118000372,
 2022118000376,
 2022334007032,
 2022075008766,
 2022118000383,
 2022118000384,
 2022226003710,
 2023068010243,
 2023068010245,
 2022118000390,
 2023111001869,
 2022075008782,
 2022075008783,
 2022075008784,
 2022075008785,
 2023068010264,
 2022334007084,
 2023068010307,
 2023068010313,
 2023068010314,
 2022075008847,
 2023068010320,
 2022226003800,
 2022334007134,
 2023068010339,
 2022226003815,
 2022118000490,
 2022334007148,
 2022226003824,
 2022075008884,
 2023068010357,
 2023111001980,
 2022118000509,
 2022118000511,
 2022118000512,
 2022226003849,
 2022118000522,
 2023068010385,
 2022118000534,
 2022075008920,
 2023068010394,
 2022118000541,
 2022226003871,
 2022118000547,
 2023068010404,
 2023068010405,
 2022334007216,
 2022118000566,
 2023068010436,
 2023068010439,
 2022118000594,
 2022118000595,
 2022118000596,
 2022118000597,
 2022118000598,
 2022226003922,
 2023068010455,
 2022118000603,
 2022118000604,
 2022118000605,
 2023068010472,
 2022075009002,
 2022226003948,
 2022075009005,
 2022334007290,
 2022334007295,
 2022075009028,
 2022334007312,
 2022334007325,
 2022226004000,
 2022334007339,
 2022075009069,
 2023068010543,
 2022226004017,
 2022075009077,
 2022334007350,
 2022075009080,
 2022334007353,
 2022334007354,
 2022226004028,
 2022118000705,
 2022118000707,
 2022118000708,
 2022118000709,
 2022118000710,
 2022226004037,
 2022226004039,
 2022226004038,
 2022226004043,
 2022226004044,
 2023111002187,
 2023111002194,
 2022118000724,
 2023034011563,
 2022075009126,
 2022226004073,
 2022075009130,
 2022118000747,
 2022118000748,
 2022118000749,
 2022226004075,
 2022334007403,
 2023068010605,
 2023068010608,
 2022334007414,
 2023068010624,
 2022226004105,
 2023068010638,
 2022075009167,
 2023034011575,
 2022334007448,
 2022334007455,
 2023068010657,
 2023068010674,
 2022075009207,
 2022075009208,
 2022334007486,
 2022226004164,
 2022075009224,
 2023068010696,
 2022226004171,
 2022334007502,
 2022334007503,
 2022226004178,
 2022226004180,
 2022226004181,
 2022075009239,
 2022226004186,
 2022334007515,
 2022334007519,
 2023068010720,
 2022334007524,
 2022075009255,
 2023068010729,
 2023068010730,
 2022334007531,
 2023068010732,
 2023068010734,
 2022075009264,
 2022075009272,
 2023068010745,
 2023068010746,
 2022334007547,
 2022226004231,
 2022334007566,
 2022075009295,
 2023068010766,
 2022075009301,
 2023068010773,
 2022226004249,
 2022334007577,
 2023068010781,
 2022075009312,
 2022226004261,
 2023068010795,
 2022075009329,
 2022226004274,
 2023068010803,
 2022075009332,
 2022075009338,
 2022334007613,
 2022075009347,
 2022075009348,
 2022226004292,
 2022226004302,
 2022075009362,
 2022075009376,
 2022075009377,
 2023068010850,
 2022075009386,
 2022334007658,
 2023068010864,
 2022075009395,
 2022075009399,
 2022334007676,
 2022075009407,
 2022334007679,
 2023068010885,
 2022075009425,
 2022075009445,
 2022226004390,
 2022075009454,
 2022075009455,
 2022118001073,
 2022075009458,
 2022334007730,
 2023068010932,
 2022075009465,
 2022226004415,
 2023068010950,
 2022226004428,
 2022075009487,
 2022118001103,
 2022075009489,
 2022075009494,
 2022075009495,
 2023068010973,
 2022075009511,
 2022075009516,
 2023068010991,
 2022075009520,
 2022075009521,
 2023068010994,
 2022334007795,
 2023068011004,
 2022334007805,
 2022075009538,
 2022075009539,
 2022226004484,
 2022226004492,
 2022334007820,
 2022075009555,
 2022075009559,
 2022075009560,
 2022075009565,
 2022118001191,
 2022118001195,
 2022334007860,
 2022334007861,
 2023068011061,
 2023068011063,
 2023068011065,
 2023068011066,
 2023068011070,
 2022334007875,
 2022118001232,
 2023068011089,
 2023068011090,
 2022118001248,
 2022075009633,
 2023068011105,
 2022118001252,
 2022226004584,
 2022226004588,
 2022118001264,
 2022226004593,
 2022226004598,
 2022226004608,
 2022118001289,
 2022118001290,
 2023068011148,
 2022118001295,
 2022226004626,
 2022334007956,
 2023068011159,
 2022118001306,
 2022118001307,
 2022075009704,
 2022334007976,
 2022334007979,
 2022075009715,
 2022226004661,
 2022266011178,
 2022075009734,
 2022075009748,
 2022334008021,
 2022334008022,
 2022226004704,
 2022334008042,
 2022118001389,
 2022075009774,
 2022334008047,
 2023068011247,
 2022334008053,
 2022075009782,
 2022118001398,
 2023068011255,
 2022118001403,
 2022226004733,
 2022075009792,
 2022226004741,
 2022226004747,
 2023068011279,
 2022334008081,
 2022226004754,
 2022118001432,
 2022075009824,
 2022334008098,
 2022075009828,
 2022334008109,
 2023152005845,
 2023068011319,
 2022075009852,
 2022075009853,
 2022118001468,
 2023014004099,
 2023014004100,
 2022334008130,
 2022334008132,
 2023068011332,
 2022075009865,
 2023068011337,
 2022075009872,
 2022118001489,
 2022118001492,
 2022118001494,
 2022118001495,
 2022226004823,
 2022075009882,
 2022334008154,
 2023068011355,
 2022226004830,
 2022226004831,
 2022226004832,
 2022226004835,
 2022226004844,
 2022226004845,
 2022226004846,
 2022334008173,
 2022226004851,
 2022334008179,
 2023068011383,
 2023014004111,
 2022226004866,
 2022118001541,
 2022226004872,
 2022334008202,
 2022334008204,
 2022226004880,
 2022334008213,
 2022118001559,
 2022118001560,
 2022334008215,
 2022118001562,
 2022334008216,
 2022075009952,
 2022334008226,
 2022226004904,
 2023068011434,
 2022226004909,
 2022334008241,
 2022075009973,
 2023068011453,
 2022075009983,
 2023068011455,
 2022075009985,
 2022075009986,
 2022075009987,
 2022075009988,
 2022226004932,
 2023068011456,
 2022226004941,
 2022334008274,
 2022075010007,
 2022226004951,
 2022118001635,
 2022075010021,
 2022226004968,
 2022226004969,
 2022226004973,
 2022075010030,
 2022334008304,
 2022075010034,
 2022075010035,
 2022226004978,
 2022334008309,
 2022226004986,
 2022075010043,
 2022118001660,
 2022226004989,
 2022075010049,
 2022334008327,
 2022075010057,
 2023068011530,
 2022075010059,
 2023068011532,
 2022226005010,
 2022075010068,
 2022075010071,
 2022075010072,
 2022334008346,
 2022226005019,
 2022334008347,
 2022075010077,
 2022226005026,
 2022075010084,
 2022075010085,
 2022334008359,
 2022334008361,
 2022075010091,
 2023111003182,
 2023068011567,
 2022334008369,
 2022334008372,
 2022075010105,
 2022334008381,
 2022118001727,
 2022075010113,
 2022075010115,
 2022334008387,
 2022334008388,
 2022075010123,
 2022226005068,
 2022118001748,
 2023111003223,
 2022118001758,
 2022334008414,
 2022334008422,
 2023111003239,
 2023111003242,
 2022075010169,
 2022118001786,
 2022334008443,
 2023111003258,
 2022334008445,
 2022334008446,
 2022226005119,
 2023111003264,
 2022334008451,
 2022075010183,
 2022075010184,
 2022075010189,
 2022075010190,
 2022226005135,
 2022226005137,
 2022075010196,
 2022334008470,
 2022075010199,
 2022075010206,
 2022118001828,
 2022334008487,
 2022334008488,
 2022226005161,
 2022075010225,
 2023068011700,
 2023068011702,
 2023068011705,
 2023068011710,
 2022075010247,
 2022118001865,
 2022118001867,
 2022075010252,
 2022075010253,
 2022075010258,
 2022226005205,
 2022334008546,
 2022226005222,
 2022334008552,
 2023068011758,
 2022118001904,
 2022075010289,
 2022334008560,
 2023068011762,
 2022075010299,
 2022075010302,
 2022075010303,
 2022334008579,
 2022226005255,
 2022075010312,
 2022334008603,
 2022075010339,
 2022075010340,
 2022075010341,
 2022075010344,
 2022334008617,
 2022334008618,
 2022226005294,
 2022075010360,
 2023111003449,
 2022075010364,
 2022226005309,
 2022075010370,
 2022226005317,
 2022226005321,
 2022075010389,
 2023068011870,
 2023068011878,
 2022226005352,
 2022334008683,
 2022118002028,
 2023068011888,
 2022118002036,
 2023068011892,
 2022075010423,
 2022118002039,
 2022118002043,
 2022075010430,
 2022075010431,
 2022118002046,
 2023068011916,
 2023068011918,
 2023111003535,
 2022075010451,
 2022118002069,
 2022118002072,
 2022334008731,
 2022075010464,
 2022226005421,
 2023068011950,
 2022118002095,
 2022334008751,
 2023068011951,
 2023133007831,
 2022118002102,
 2022075010498,
 2022334008772,
 2022334008773,
 2022075010504,
 2022226005453,
 2022075010510,
 2022118002131,
 2022226005460,
 2022118002133,
 2023068011990,
 2022226005463,
 2022334008795,
 2022118002142,
 2022334008800,
 2022118002150,
 2022075010537,
 2022075010547,
 2022334008822,
 2022334008823,
 2022226005499,
 2022118002172,
 2022334008832,
 2022075010567,
 2022075010568,
 2022226005529,
 2022334008859,
 2022075010591,
 2022075010593,
 2022075010594,
 2022075010595,
 2023068012067,
 2023111003681,
 2023111003690,
 2022075010618,
 2022334008892,
 2022075010623,
 2023111003714,
 2023111003717,
 2022075010639,
 2022226005583,
 2022075010669,
 2023068012153,
 2023068012156,
 2022334008960,
 2022226005633,
 2022075010696,
 2023068012169,
 2022226005642,
 2022118002323,
 2022075010712,
 2022075010715,
 2022075010717,
 2022118002333,
 2022075010720,
 2022075010725,
 2022118002342,
 2022334008998,
 2022334009000,
 2022075010730,
 2022118002350,
 2022334009007,
 2022075010737,
 2022226005681,
 2022226005689,
 2022334009017,
 2023068012219,
 2022075010749,
 2022075010750,
 2022075010762,
 2022075010764,
 2023068012237,
 2023068012240,
 2022118002385,
 2022118002390,
 2022075010779,
 2022118002395,
 2022334009051,
 2022334009052,
 2022334009055,
 2022118002400,
 2022334009057,
 2022334009058,
 2022118002404,
 2022118002406,
 2023068012266,
 2022118002415,
 2022075010800,
 2022075010801,
 2022118002422,
 2022118002423,
 2022118002428,
 2022334009090,
 2023111003908,
 2022075010821,
 2022118002437,
 2022118002439,
 2022118002447,
 2022118002450,
 2022118002452,
 2022334009108,
 2022118002457,
 2022075010842,
 2022075010847,
 2022118002463,
 2022118002464,
 2022118002467,
 2022334009127,
 2022118002473,
 2022118002475,
 2022118002477,
 2022118002481,
 2022075010867,
 2022075010868,
 2023111003960,
 2022334009145,
 2022118002497,
 2022118002498,
 2022075010889,
 2022075010890,
 2022334009162,
 2022118002515,
 2022075010900,
 2022334009172,
 2022118002518,
 2022118002522,
 2022075010908,
 2023068012381,
 2022118002529,
 2022118002530,
 ...}

Verificando se todos os patógenos de um test_kit estão sendo testados para todos os test_id

In [59]:
PATHOGENS_TESTS = {
    'panel_21':{
        # PAINCOVI
        'FLUA_test_result',
        'FLUB_test_result',
        'VSR_test_result',
        'SC2_test_result',
        'META_test_result',
        'RINO_test_result',
        'PARA_test_result',
        'ADENO_test_result',
        'COVS_test_result',
        'BAC_test_result',
    },

    'panel_24':{
        # RESPIRA
        'FLUA_test_result',
        'FLUB_test_result',
        'VSR_test_result',
        'META_test_result',
        'RINO_test_result',
        'PARA_test_result',
        'ADENO_test_result',
        'BOCA_test_result',
        'COVS_test_result',
        'ENTERO_test_result',
        'BAC_test_result',
    },

    'panel_4':{
        # PCRESPSL & PCRVRESP
        'FLUA_test_result',
        'FLUB_test_result',
        'VSR_test_result',
        'SC2_test_result',
    },

    'covid_antigen':{
        'SC2_test_result',
    },

    'covid_pcr':{
        'SC2_test_result',
    },
}

In [60]:
# Mapeando Pos e Neg para Tes
df_combined_test_pathogen_non_nt_on_kit = (
    df_combined
    .replace(('Pos', 'Neg'),  'Tes')
)

In [61]:
for pathogen, test_columns in PATHOGENS_TESTS.items():
    print(pathogen)
    print(
        df_combined_test_pathogen_non_nt_on_kit
        .query("test_kit == @pathogen")
        [list(test_columns)]
        .drop_duplicates().T
        # Deve resultar em apenas uma linha completa por 'Tes'
    )

    print('\n\n')

panel_21
Empty DataFrame
Columns: []
Index: [FLUB_test_result, FLUA_test_result, VSR_test_result, BAC_test_result, SC2_test_result, PARA_test_result, RINO_test_result, META_test_result, COVS_test_result, ADENO_test_result]



panel_24
Empty DataFrame
Columns: []
Index: [FLUB_test_result, FLUA_test_result, VSR_test_result, BAC_test_result, PARA_test_result, BOCA_test_result, RINO_test_result, META_test_result, COVS_test_result, ADENO_test_result, ENTERO_test_result]



panel_4
Empty DataFrame
Columns: []
Index: [FLUB_test_result, FLUA_test_result, SC2_test_result, VSR_test_result]



covid_antigen
Empty DataFrame
Columns: []
Index: [SC2_test_result]



covid_pcr
Empty DataFrame
Columns: []
Index: [SC2_test_result]

Verificando resultados de alguns testes

In [62]:
import numpy as np

In [63]:
np.random.seed(214)

ids = np.random.choice(df_combined['test_id'], 100)
test_columns = [col for col in df_combined.columns if col.endswith('_result')]

In [64]:
current_id=50

In [65]:
current_id = current_id+1
id = ids[current_id]
print( df_combined.query("test_id == @id")[['test_id', 'test_kit'] + test_columns].T )
print( df_full_raw.query("OS == @id") [['OS', 'Parametro', 'Resultado']].T )

                            50298
test_id             2022011003051
test_kit                   test_2
FLUA_test_result              Neg
FLUB_test_result              Neg
VSR_test_result                NT
SC2_test_result                NT
META_test_result               NT
RINO_test_result               NT
PARA_test_result               NT
ADENO_test_result              NT
BOCA_test_result               NT
COVS_test_result               NT
ENTERO_test_result             NT
BAC_test_result                NT
Empty DataFrame
Columns: []
Index: [OS, Parametro, Resultado]

Verificando resultados de alguns testes - Fltrando por test_kit

In [66]:
np.random.seed(214)

ids = np.random.choice(df_combined.query("test_kit not in ('covid_pcr', 'covid_antigen')")['test_id'], 100)
test_columns = [col for col in df_combined.columns if col.endswith('_result')]

In [67]:
current_id=0

In [68]:
current_id = current_id+1
id = ids[current_id]
print( df_combined.query("test_id == @id")[['test_id', 'test_kit'] + test_columns].T )
print( df_full_raw.query("OS == @id") [['OS', 'Parametro', 'Resultado']].T )

                            18113
test_id             2022005002687
test_kit                   test_2
FLUA_test_result              Neg
FLUB_test_result              Neg
VSR_test_result                NT
SC2_test_result                NT
META_test_result               NT
RINO_test_result               NT
PARA_test_result               NT
ADENO_test_result              NT
BOCA_test_result               NT
COVS_test_result               NT
ENTERO_test_result             NT
BAC_test_result                NT
Empty DataFrame
Columns: []
Index: [OS, Parametro, Resultado]