python scripts/reformat_sabin.py --datadir data --rename data/rename_columns.xlsx --correction data/fix_values.xlsx --output combined_sabin.tsv

In [1]:
import pandas as pd
import re

In [2]:
df_sabin_covid = pd.read_excel(
    './../data/SABIN/20230801_SABIN_Covid_2023ateSE30.xlsx'
)
df_sabin_covid.head()

,OS,Código Posto,Estado,Municipio,DataAtendimento,DataNascimento,Sexo,Descricao,Parametro,Resultado,DataAssinatura
0,321-66464-12445,321,DISTRITO FEDERAL,BRASÍLIA,21/12/2022,17/11/1980,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,2023-01-01 00:00:00
1,525-66472-8612,525,DISTRITO FEDERAL,BRASÍLIA,29/12/2022,26/11/1983,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,DETECTADO (Presença de RNA específico de SARS-...,2023-01-01 00:00:00
2,324-66472-9108,324,PARÁ,BELÉM,29/12/2022,21/09/1958,Masculino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,2023-01-01 00:00:00
3,891-66472-10158,891,GOIAS,ANAPOLIS,29/12/2022,17/11/2002,Masculino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,DETECTADO (Presença de RNA específico de SARS-...,2023-01-01 00:00:00
4,407-66472-10869,407,TOCANTINS,PALMAS,29/12/2022,17/09/1959,Feminino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,DETECTADO (Presença de RNA específico de SARS-...,2023-01-01 00:00:00

SABIN Covid 2022

In [3]:
df_sabin_covid = pd.read_excel(
    './../data/SABIN/SABIN_Covid_2022.xlsx'
)
df_sabin_covid.head()

,OS,Código Posto,Estado,Municipio,DataAtendimento,DataNascimento,Sexo,Descricao,Parametro,Resultado,DataAssinatura
0,577-66100-15803,577,DISTRITO FEDERAL,BRASÍLIA,2021-12-22 00:00:00,1964-07-16 00:00:00,Masculino,TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS S...,NALVO,NÃO DETECTADO (Ausência de RNA específico de S...,2022-01-01 00:00:00
1,1460-66101-7662,1460,DISTRITO FEDERAL,BRASÍLIA,2021-12-23 00:00:00,1978-10-01 00:00:00,Masculino,TESTE MOLECULAR PARA SARS-CoV-2 (COVID 19) COM...,TMR19RES1,NÃO DETECTADO (Ausência de RNA específico de S...,2022-01-01 00:00:00
2,1460-66101-7663,1460,DISTRITO FEDERAL,BRASÍLIA,2021-12-23 00:00:00,1985-10-29 00:00:00,Feminino,TESTE MOLECULAR PARA SARS-CoV-2 (COVID 19) COM...,TMR19RES1,NÃO DETECTADO (Ausência de RNA específico de S...,2022-01-01 00:00:00
3,1460-66101-7665,1460,DISTRITO FEDERAL,BRASÍLIA,2021-12-23 00:00:00,2012-03-06 00:00:00,Feminino,TESTE MOLECULAR PARA SARS-CoV-2 (COVID 19) COM...,TMR19RES1,NÃO DETECTADO (Ausência de RNA específico de S...,2022-01-01 00:00:00
4,1460-66101-7672,1460,DISTRITO FEDERAL,BRASÍLIA,2021-12-23 00:00:00,2015-06-07 00:00:00,Masculino,TESTE MOLECULAR PARA SARS-CoV-2 (COVID 19) COM...,TMR19RES1,NÃO DETECTADO (Ausência de RNA específico de S...,2022-01-01 00:00:00

In [4]:
df_sabin_covid['Resultado'].unique()

array(['NÃO DETECTADO (Ausência de RNA específico de SARS-CoV-2)',
       'DETECTADO (Presença de RNA específico de SARS-CoV-2)',
       'NÃO DETECTADO', 'DETECTADO', 'DETECTADO (Pres',
       'NÃO DETECTADO (Ausência de RNA específico de Sars-CoV-2)',
       'INDETERMINADO (Presença de RNA específico aos Sarbecovírus)',
       'REAGENTE', ' NÃO DETECTADO', 'Detectado'], dtype=object)

In [4]:
df_sabin_covid['Parametro'].unique()

array(['NALVO', 'TMR19RES1', 'PCRSALIV', 'COVIDECO', 'NALVOSSA', 'RDRPCI',
       'NALVOCTL', 'RDRPALVOCTL', 'RDRPALVO', 'NALVOCI', 'NALVOCQ'],
      dtype=object)

In [4]:
df_sabin_covid['DataAtendimento'].replace( re.compile("[0-9]"), 'x' ).unique()

array(['xx/xx/xxxx', datetime.datetime(2023, 1, 1, 0, 0),
       datetime.datetime(2023, 2, 1, 0, 0),
       datetime.datetime(2023, 3, 1, 0, 0),
       datetime.datetime(2022, 1, 12, 0, 0),
       datetime.datetime(2022, 3, 12, 0, 0),
       datetime.datetime(2022, 5, 12, 0, 0),
       datetime.datetime(2022, 9, 12, 0, 0),
       datetime.datetime(2023, 4, 1, 0, 0),
       datetime.datetime(2023, 5, 1, 0, 0),
       datetime.datetime(2023, 6, 1, 0, 0),
       datetime.datetime(2023, 7, 1, 0, 0),
       datetime.datetime(2023, 8, 1, 0, 0),
       datetime.datetime(2023, 9, 1, 0, 0),
       datetime.datetime(2023, 10, 1, 0, 0),
       datetime.datetime(2023, 11, 1, 0, 0),
       datetime.datetime(2023, 12, 1, 0, 0),
       datetime.datetime(2023, 1, 2, 0, 0),
       datetime.datetime(2023, 2, 2, 0, 0),
       datetime.datetime(2023, 3, 2, 0, 0),
       datetime.datetime(2023, 4, 2, 0, 0),
       datetime.datetime(2023, 5, 2, 0, 0),
       datetime.datetime(2023, 6, 2, 0, 0),
       datetime.datetime(2023, 7, 2, 0, 0),
       datetime.datetime(2023, 8, 2, 0, 0),
       datetime.datetime(2023, 9, 2, 0, 0),
       datetime.datetime(2023, 10, 2, 0, 0),
       datetime.datetime(2022, 10, 2, 0, 0),
       datetime.datetime(2023, 11, 2, 0, 0),
       datetime.datetime(2023, 12, 2, 0, 0),
       datetime.datetime(2023, 1, 3, 0, 0),
       datetime.datetime(2023, 2, 3, 0, 0),
       datetime.datetime(2023, 3, 3, 0, 0),
       datetime.datetime(2023, 4, 3, 0, 0),
       datetime.datetime(2023, 5, 3, 0, 0),
       datetime.datetime(2023, 6, 3, 0, 0),
       datetime.datetime(2023, 7, 3, 0, 0),
       datetime.datetime(2023, 8, 3, 0, 0),
       datetime.datetime(2023, 9, 3, 0, 0),
       datetime.datetime(2023, 10, 3, 0, 0),
       datetime.datetime(2023, 11, 3, 0, 0),
       datetime.datetime(2023, 12, 3, 0, 0),
       datetime.datetime(2022, 11, 2, 0, 0),
       datetime.datetime(2023, 1, 4, 0, 0),
       datetime.datetime(2023, 2, 4, 0, 0),
       datetime.datetime(2023, 3, 4, 0, 0),
       datetime.datetime(2023, 4, 4, 0, 0),
       datetime.datetime(2023, 5, 4, 0, 0),
       datetime.datetime(2023, 6, 4, 0, 0),
       datetime.datetime(2023, 7, 4, 0, 0),
       datetime.datetime(2023, 8, 4, 0, 0),
       datetime.datetime(2023, 9, 4, 0, 0),
       datetime.datetime(2023, 10, 4, 0, 0),
       datetime.datetime(2023, 11, 4, 0, 0),
       datetime.datetime(2023, 12, 4, 0, 0),
       datetime.datetime(2023, 1, 5, 0, 0),
       datetime.datetime(2023, 2, 5, 0, 0),
       datetime.datetime(2023, 3, 5, 0, 0),
       datetime.datetime(2023, 4, 5, 0, 0),
       datetime.datetime(2023, 5, 5, 0, 0),
       datetime.datetime(2023, 6, 5, 0, 0),
       datetime.datetime(2023, 7, 5, 0, 0),
       datetime.datetime(2023, 8, 5, 0, 0),
       datetime.datetime(2023, 9, 5, 0, 0),
       datetime.datetime(2023, 10, 5, 0, 0),
       datetime.datetime(2023, 11, 5, 0, 0),
       datetime.datetime(2023, 12, 5, 0, 0),
       datetime.datetime(2023, 1, 6, 0, 0),
       datetime.datetime(2023, 2, 6, 0, 0),
       datetime.datetime(2023, 3, 6, 0, 0),
       datetime.datetime(2023, 4, 6, 0, 0),
       datetime.datetime(2023, 5, 6, 0, 0),
       datetime.datetime(2023, 6, 6, 0, 0),
       datetime.datetime(2023, 7, 6, 0, 0),
       datetime.datetime(2023, 8, 6, 0, 0),
       datetime.datetime(2023, 9, 6, 0, 0),
       datetime.datetime(2023, 10, 6, 0, 0),
       datetime.datetime(2023, 11, 6, 0, 0),
       datetime.datetime(2023, 12, 6, 0, 0),
       datetime.datetime(2023, 1, 7, 0, 0),
       datetime.datetime(2023, 2, 7, 0, 0),
       datetime.datetime(2023, 3, 7, 0, 0),
       datetime.datetime(2023, 4, 7, 0, 0),
       datetime.datetime(2023, 5, 7, 0, 0),
       datetime.datetime(2023, 6, 7, 0, 0),
       datetime.datetime(2023, 7, 7, 0, 0),
       datetime.datetime(2023, 8, 7, 0, 0),
       datetime.datetime(2023, 9, 7, 0, 0),
       datetime.datetime(2023, 10, 7, 0, 0),
       datetime.datetime(2023, 11, 7, 0, 0),
       datetime.datetime(2023, 12, 7, 0, 0)], dtype=object)

In [ ]:
df_sabin_covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72784 entries, 0 to 72783
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OS               72784 non-null  object
 1   Código Posto     72784 non-null  int64
 2   Estado           72784 non-null  object
 3   Municipio        72784 non-null  object
 4   DataAtendimento  72784 non-null  object
 5   DataNascimento   72784 non-null  object
 6   Sexo             72784 non-null  object
 7   Descricao        72784 non-null  object
 8   Parametro        72784 non-null  object
 9   Resultado        72784 non-null  object
 10  DataAssinatura   72784 non-null  object
dtypes: int64(1), object(10)
memory usage: 6.1+ MB

In [32]:
df_sabin_covid['Descricao'].unique()

array(['TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS SARS-CoV2',
       'TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS SARS-CoV-2 SALIVA',
       'DETECCAO QUALITATIVA DE ANTIGENOS DE SARS-CoV-2',
       'TESTE MOLECULAR PARA SARS-CoV-2 (COVID 19) COM AMPLIFICAÇÃO ISOTÉRMICA'],
      dtype=object)

- **Identificador Único** -  OS
- **Data da coleta** - DataAtendimento
- **Estado** - Estado
- **Municipio** - Municipio
- **Sexo** - Sexo
- **Idade** - DataNascimento
- **Tipo de Exame** - Descricao ?
- **Patógeno** - Descricao ?

---

In [33]:
df_sabin = pd.read_excel(
    './../data/SABIN/20230711_SABIN_paineis_2023ateSE27.xlsx'
)
df_sabin.head()

,OS,Código Posto,Estado,Municipio,DataAtendimento,DataNascimento,Sexo,Descricao,Parametro,Resultado,DataAssinatura
0,565-66476-5360,565,DISTRITO FEDERAL,BRASÍLIA,2023-02-01 00:00:00,2022-06-05 00:00:00,Masculino,PAINEL MOLECULAR RAPIDO PARA INFECÇOES RESPIRA...,PARA1,NÃO DETECTADO,2023-03-01 00:00:00
1,565-66476-5360,565,DISTRITO FEDERAL,BRASÍLIA,2023-02-01 00:00:00,2022-06-05 00:00:00,Masculino,PAINEL MOLECULAR RAPIDO PARA INFECÇOES RESPIRA...,PARA2,NÃO DETECTADO,2023-03-01 00:00:00
2,565-66476-5360,565,DISTRITO FEDERAL,BRASÍLIA,2023-02-01 00:00:00,2022-06-05 00:00:00,Masculino,PAINEL MOLECULAR RAPIDO PARA INFECÇOES RESPIRA...,PARA3,NÃO DETECTADO,2023-03-01 00:00:00
3,565-66476-5360,565,DISTRITO FEDERAL,BRASÍLIA,2023-02-01 00:00:00,2022-06-05 00:00:00,Masculino,PAINEL MOLECULAR RAPIDO PARA INFECÇOES RESPIRA...,PARA4,NÃO DETECTADO,2023-03-01 00:00:00
4,565-66476-5360,565,DISTRITO FEDERAL,BRASÍLIA,2023-02-01 00:00:00,2022-06-05 00:00:00,Masculino,PAINEL MOLECULAR RAPIDO PARA INFECÇOES RESPIRA...,BORDETELLAP,NÃO DETECTADO,2023-03-01 00:00:00

Campos
- **Identificador Único** -  OS
- **Data da coleta** - DataAtendimento
- **Estado** - Estado
- **Municipio** - Municipio
- **Sexo** - Sexo
- **Idade** - DataNascimento
- **Tipo de Exame** - Descricao ?
- **Patógeno** - Descricao ?

In [34]:
df_sabin['Descricao'].unique()

array(['PAINEL MOLECULAR RAPIDO PARA INFECÇOES RESPIRATORIAS COM SARSCOV2'],
      dtype=object)

In [35]:
df_sabin_ = pd.concat([df_sabin_covid, df_sabin])
df_sabin_['Descricao'].unique()

array(['TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS SARS-CoV2',
       'TESTE MOLECULAR PARA DETECÇÃO DO CORONAVÍRUS SARS-CoV-2 SALIVA',
       'DETECCAO QUALITATIVA DE ANTIGENOS DE SARS-CoV-2',
       'TESTE MOLECULAR PARA SARS-CoV-2 (COVID 19) COM AMPLIFICAÇÃO ISOTÉRMICA',
       'PAINEL MOLECULAR RAPIDO PARA INFECÇOES RESPIRATORIAS COM SARSCOV2'],
      dtype=object)

## Reescrita do ETL

python scripts/reformat_sabin.py --datadir data --rename data/rename_columns.xlsx --correction data/fix_values.xlsx --output combined_hla.tsv

In [36]:
df_rename_cols = pd.read_excel('./../data/rename_columns.xlsx')
df_fix_values = pd.read_excel('./../data/fix_values.xlsx')

In [37]:
df_rename_cols.query('lab_id == "SABIN"')

   lab_id      column_name         new_name other
68  SABIN        Resultado  SC2_test_result   NaN
69  SABIN            Idade              age   NaN
70  SABIN           Estado            state   NaN
71  SABIN   DataNascimento        birthdate   NaN
72  SABIN  DataAtendimento     date_testing   NaN
73  SABIN             Sexo              sex   NaN
74  SABIN               OS          test_id   NaN
75  SABIN        Municipio         location   NaN

In [57]:
df_fix_values.query('lab_id == "SABIN" and column_name == "SC2_test_result"')['old_data'].to_list()

[' NÃO DETECTADO',
 'DETECTADO',
 'DETECTADO (Presença de RNA específico de SARS-CoV-2)',
 'INDETERMINADO (Presença de RNA específico aos Sarbecovírus)',
 'NÃO DETECTADO',
 'Não detectado ',
 'NÃO DETECTADO (Ausência de RNA específico de SARS-CoV-2)',
 'REAGENTE']

In [38]:
df_fix_values.query('lab_id == "SABIN"')

,lab_id,column_name,old_data,new_data,Unnamed: 4
0,SABIN,SC2_test_result,NÃO DETECTADO,Neg,Negative
1,SABIN,SC2_test_result,DETECTADO,Pos,Positive
2,SABIN,SC2_test_result,DETECTADO (Presença de RNA específico de SARS-...,Pos,Positive
3,SABIN,SC2_test_result,INDETERMINADO (Presença de RNA específico aos ...,Neg,Negative
4,SABIN,SC2_test_result,NÃO DETECTADO,Neg,Negative
5,SABIN,SC2_test_result,Não detectado,Neg,Negative
6,SABIN,SC2_test_result,NÃO DETECTADO (Ausência de RNA específico de S...,Neg,Negative
7,SABIN,SC2_test_result,REAGENTE,Pos,Positive

In [39]:
df_fix_values['lab_id'].unique()

array(['SABIN', 'HILAB', 'HLAGyn', 'DB Mol', 'DASA', 'any'], dtype=object)

### **Creating renaming Dicts**

In [40]:
## import reduce function
from functools import reduce

rename_cols_dict = (
    df_rename_cols
    .query('lab_id == "SABIN"')
    .assign( mapping=lambda df: df.apply(lambda row: {row['column_name']: row['new_name']}, axis=1) )
    .groupby('lab_id')
    .agg({'mapping': lambda x: reduce(lambda a,b: {**a,**b}, x)})
    .to_dict()
    ['mapping']
)

rename_cols_dict

{'SABIN': {'Resultado': 'SC2_test_result',
  'Idade': 'age',
  'Estado': 'state',
  'DataNascimento': 'birthdate',
  'DataAtendimento': 'date_testing',
  'Sexo': 'sex',
  'OS': 'test_id',
  'Municipio': 'location'}}

### **Fixing Columns**

In [41]:
df_sabin_covid = pd.read_excel(
    './../data/SABIN/20230711_SABIN_Covid_2023ateSE27.xlsx'
)

**Fixing Column Types**

In [42]:
df_sabin_covid["OS"] = df_sabin_covid["OS"].astype('str')
df_sabin_covid["Código Posto"] = df_sabin_covid["Código Posto"].astype('int16')
df_sabin_covid["Estado"] = df_sabin_covid["Estado"].astype('str')
df_sabin_covid["Municipio"] = df_sabin_covid["Municipio"].astype('str')
df_sabin_covid["DataAtendimento"] = pd.to_datetime(df_sabin_covid["DataAtendimento"])
df_sabin_covid["DataNascimento"] = pd.to_datetime(df_sabin_covid["DataNascimento"])
df_sabin_covid["Sexo"] = df_sabin_covid["Sexo"].astype('str')
df_sabin_covid["Descricao"] = df_sabin_covid["Descricao"].astype('str')
df_sabin_covid["Parametro"] = df_sabin_covid["Parametro"].astype('str')
df_sabin_covid["Resultado"] = df_sabin_covid["Resultado"].astype('str')
df_sabin_covid["DataAssinatura"] = pd.to_datetime(df_sabin_covid["DataAssinatura"])

**Adding Sample ID and Test Kit information**

In [43]:
df_sabin_covid.insert(1, 'sample_id', '')
df_sabin_covid.insert(1, 'test_kit', '')
df_sabin_covid["test_kit"] = df_sabin_covid["Parametro"].apply(lambda x: "covid_antigen" if x == "COVIDECO" else "covid_pcr") # separate by rows in column test_kit
df_sabin_covid.fillna('', inplace=True)

**Handling ID Columns**

In [44]:
id_columns = [
    'OS',
    'Estado',
    'Municipio',
    'DataAtendimento',
    'Sexo',
    'Descricao',
    'Resultado',
]

for column in id_columns:
    if column not in df_sabin_covid.columns.tolist():
        df_sabin_covid[column] = ''
        print('\t\t\t - No \'%s\' column found. Please check for inconsistencies. Meanwhile, an empty \'%s\' column was added.' % (column, column))

In [45]:
if 'DataNascimento' not in df_sabin_covid.columns.tolist():
    df_sabin_covid['birthdate'] = ''
df_sabin_covid['Ct_FluA'] = ''
df_sabin_covid['Ct_FluB'] = ''
df_sabin_covid['Ct_VSR'] = ''
df_sabin_covid['Ct_RDRP'] = ''
df_sabin_covid['Ct_geneE'] = ''
df_sabin_covid['Ct_geneN'] = ''
df_sabin_covid['Ct_geneS'] = ''
df_sabin_covid['Ct_ORF1ab'] = ''
df_sabin_covid['geneS_detection'] = ''

**Adding pathogens information**

In [46]:
pathogens = [
    'SC2',
    'FLUA',
    'FLUB', 
    'VSR', 
    'META', 
    'RINO',
    'PARA', 
    'ADENO', 
    'BOCA', 
    'COVS', 
    'ENTERO', 
    'BAC'
]

for p in pathogens:
    if p != 'SC2':
        df_sabin_covid[p + '_test_result'] = 'NT' # 'Not tested'

In [47]:
df_sabin_covid.insert(0, 'lab_id', 'SABIN')

In [48]:
df_sabin_covid = df_sabin_covid.rename(columns=rename_cols_dict['SABIN'])

## Fix values

In [49]:
df_sabin_covid.head(2)

,lab_id,test_id,test_kit,sample_id,Código Posto,state,location,date_testing,birthdate,sex,...,FLUB_test_result,VSR_test_result,META_test_result,RINO_test_result,PARA_test_result,ADENO_test_result,BOCA_test_result,COVS_test_result,ENTERO_test_result,BAC_test_result
0,SABIN,321-66464-12445,covid_pcr,,321,DISTRITO FEDERAL,BRASÍLIA,2022-12-21,1980-11-17,Feminino,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
1,SABIN,525-66472-8612,covid_pcr,,525,DISTRITO FEDERAL,BRASÍLIA,2022-12-29,1983-11-26,Feminino,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT

In [50]:
from functools import reduce

In [51]:
rename_cols_dict = (
    df_fix_values
    .query('lab_id == "SABIN" or lab_id == "any"')
    .assign( mapping_data=lambda df: df.apply(lambda row: {row['old_data']: row['new_data']}, axis=1) )
    .groupby(['lab_id', 'column_name'])
    .agg({'mapping_data': lambda x: reduce(lambda a,b: {**a,**b}, x)})
    .reset_index()
    .assign( mapping=lambda df: df.apply(lambda row: {row['column_name']: row['mapping_data']}, axis=1) )
    .drop(columns=['mapping_data'])
    [['mapping']]
    .agg(lambda x: reduce(lambda a,b: {**a,**b}, x))
    .to_dict()
    ['mapping']
)

rename_cols_dict

{'SC2_test_result': {' NÃO DETECTADO': 'Neg',
  'DETECTADO': 'Pos',
  'DETECTADO (Presença de RNA específico de SARS-CoV-2)': 'Pos',
  'INDETERMINADO (Presença de RNA específico aos Sarbecovírus)': 'Neg',
  'NÃO DETECTADO': 'Neg',
  'Não detectado ': 'Neg',
  'NÃO DETECTADO (Ausência de RNA específico de SARS-CoV-2)': 'Neg',
  'REAGENTE': 'Pos'},
 'location': {'A': nan,
  'ABARRACAMENTORIODASFL': 'RIO DAS FLORES',
  'ABARRACAMENTORIODASFLORES': 'RIO DAS FLORES',
  'ABRANTESCAMACARI': 'CAMACARI',
  'ABREUELIMA': 'ABREU E LIMA',
  'AGUABOA': 'AGUA BOA',
  'AGUAS LINDAS ': 'PLANALTINA',
  'AGUASCLARAS': 'BRASILIA',
  'AGUASDAPRATA': 'AGUAS DA PRATA',
  'AGUASDELINDOIA': 'AGUAS DE LINDOIA',
  'AGUASDESAOPEDRO': 'AGUAS DE SAO PEDRO',
  'AGUASLINDAS': 'PLANALTINA',
  'AGUASLINDASDEGOIAS': 'AGUAS LINDAS DE GOIAS',
  'ALCANTARA': 'RIO DE JANEIRO',
  'ALCANTARASAOGONCALO': 'SAO GONCALO',
  'ALDEIA DA SERRA ': 'BARUERI',
  'ALDEIADASERRA': 'BARUERI',
  'ALEMPARAIBA': 'ALEM PARAIBA',
  'ALMIRANTETAMANDARE': 'ALMIRANTE TAMANDARE',
  'ALPHAVILLE': nan,
  'ALTAFLORESTA': 'ALTA FLORESTA',
  'ALTOHORIZONTE': 'ALTO HORIZONTE',
  'AMADORBUENO': 'ITAPEVI',
  'ANGENTINA': nan,
  'ANGRA DOS REIS ': 'ANGRA DOS REIS',
  'ANGRADOSREIS': 'ANGRA DOS REIS',
  'ANTONIOPRADO': 'ANTONIO PRADO',
  'AP': 'MOGI DAS CRUZES',
  'APARECID ADE GOIANIA': 'APARECIDA DE GOIANIA',
  'APARECIDADEGOIANIA': 'APARECIDA DE GOIANIA',
  'APRT': nan,
  'ARACOIABADASERRA': 'ARACOIABA DA SERRA',
  'ARAUJO': 'BELO HORIZONTE',
  'AREIABRANCA': 'AREIA BRANCA',
  'AREMBEPECAMACARI': 'CAMACARI',
  'ARGENTINA': nan,
  'ARIQUEMES': 'VARZEA GRANDE',
  'ARIQUENES': 'ARIQUEMES',
  'ARMACAODOSBUZIOS': 'ARMACAO DOS BUZIOS',
  'ARPOADOR': 'SAO PAULO',
  "ARRAIALD'AJUDAPORTOSEGURO": 'PORTO SEGURO',
  'ARRAIALDOCABO': 'ARRAIAL DO CABO',
  'ARTURNOGUEIRA': 'ARTUR NOGUEIRA',
  'ARUJ': nan,
  'ASSU': 'ACU',
  'BACAXASAQUAREMA': 'SAQUAREMA',
  'BADYBASSITT': 'BADY BASSITT',
  'BAHIA': nan,
  'Bahia': nan,
  'BAIXOGUANDU': 'BAIXO GUANDU',
  'BALNEARIOCAMBORIU': 'BALNEARIO CAMBORIU',
  'BARAO DE JUPARANA VALENCA': 'VALENCA',
  'BARAO DE JUPARANA VALENCA ': 'VALENCA',
  'BARAODEJUPARANAVALENCA': 'VALENCA',
  'BARRA': 'PINHEIRAL',
  'BARRADESAOFRANCIS': 'BARRA DE SAO FRANCISCO',
  'BARRADESAOJOAOCASIMIRODEABREU': 'CASIMIRO DE ABREU',
  'BARRADOJACUIPECAMACARI': 'CAMACARI',
  'BARRADOPIRAI': 'BARRA DO PIRAI',
  'BARRADOTURVO': 'BARRA DO TURVO',
  'BARRAMANSA': 'BARRA MANSA',
  'BELAVISTADEMINAS': 'BELA VISTA DE MINAS',
  'BELAVISTADOPARAISO': 'BELA VISTA DO PARAISO',
  'BELFORDROXO': 'BELFORD ROXO',
  'BELFOROXO': 'BELFORD ROXO',
  'BELFORTROXO': 'BELFORD ROXO',
  'BELGICA': 'RIO DE JANEIRO',
  'BELO HORIZONTE ': 'BELO HORIZONTE',
  'BELOHORIZONTE': 'BELO HORIZONTE',
  'BELOJARDIM': 'BELO JARDIM',
  'BIRITIBAMIRIM': 'BIRITIBA MIRIM',
  'BIRITIBAUSSU': 'MOGI DAS CRUZES',
  'BIRITINAMIRIM': 'BIRITIBA MIRIM',
  'BLAP': nan,
  'BLOCOAPTO': nan,
  'BLUMENAU ': 'BLUMENAU',
  'BOACU': 'SAO GONCALO',
  'BOAESPERANCA': 'BOA ESPERANCA',
  'BOAVIAGEM': 'BOA VIAGEM',
  'BOLFORDROXO': 'BELFORD ROXO',
  'BOMJARDIM': 'BOM JARDIM',
  'BOMJESUSDOITABAPOANA': 'BOM JESUS DO ITABAPOANA',
  'BOMJESUSDOSPERDOES': 'BOM JESUS DOS PERDOES',
  'BONFIMPAULISTARIBEIRAOPRETO': 'RIBEIRAO PRETO',
  'BOTAFOGO': 'RIO DE JANEIRO',
  'BRAGANCAPAULISTA': 'BRAGANCA PAULISTA',
  'BRASCUBAS': 'MOGI DAS CRUZES',
  'BRASILÂNDIA': 'BRASILANDIA',
  'BRASILIA ': 'BRASILIA',
  'BRASILIADEMINAS': 'BRASILIA DE MINAS',
  'BRAZ CUBAS': 'MOGI DAS CRUZES',
  'BRAZCUBAS': 'MOGI DAS CRUZES',
  'Brazil': nan,
  'BREJODAMADREDEDEUS': 'BREJO DA MADRE DE DEUS',
  'BROXO': 'BELFORD ROXO',
  'BRUMENAL': 'BLUMENAU',
  'BRUMENAU': 'BLUMENAU',
  'BUENOBRANDAO': 'BUENO BRANDAO',
  'BUENOSAIRES': 'BUENOS AIRES',
  'BURARAMACACHOEIRODEITAPEMIRIM': 'CACHOEIRO DE ITAPEMIRIM',
  'BURITIALEGRE': 'BURITI ALEGRE',
  'BUZIOS': 'ARMACAO DE BUZIOS',
  'CABO': 'CABO DE SANTO AGOSTINHO',
  'CABO DE SANTO AGOSTINHO ': 'CABO DE SANTO AGOSTINHO',
  'CABODESANTOAGOSTINHO': 'CABO DE SANTO AGOSTINHO',
  'CABODESANTOGOSTINHO': 'CABO DE SANTO AGOSTINHO',
  'CABOFRIO': 'CABO FRIO',
  'CABOSTOAGOSTINHO': 'CABO SANTO AGOSTINHO',
  'CACAPVA': 'CACAPAVA',
  'CACHOEIRAALTA': 'CACHOEIRA ALTA',
  'CACHOEIRAPAULISTA': 'CACHOEIRA PAULISTA',
  'CACHOEIRASDEMACACU': 'CACHOEIRAS DE MACACU',
  'CACHOEIRODEITAPEMIRIM': 'CACHOEIRO DE ITAPEMIRIM',
  'CAETE': 'CUIABA',
  'CAETE ': 'CAETE',
  'CAIERAS': 'CAIEIRAS',
  'CAIERIAS ': 'CAIEIRAS',
  'Caité': 'CAETE',
  'CALDAS NOVAS GOIAS': 'CALDAS NOVAS',
  'CALDAS NOVAS GOIAS ': 'CALDAS NOVAS',
  'CALDASNOVAS': 'CALDAS NOVAS',
  'CALDASNOVASGOIAS': 'CALDAS NOVAS GOIAS',
  'CALIFORNIA': nan,
  'CAMBORIÚ': 'CAMBORIU',
  'CAMBUÍ': 'CAMBUI',
  'CAMOCIMDESAOFELIX': 'CAMOCIM DE SAO FELIX',
  'CAMPESTRE': 'CARANDAI',
  'CAMPINAGRANDE': 'CAMPINA GRANDE',
  'CAMPOBELO': 'CAMPO BELO',
  'CAMPOGRANDE': 'CAMPO GRANDE',
  'CAMPOLARGO': 'CAMPO LARGO',
  'CAMPOLIMPOPAULISTA': 'CAMPO LIMPO PAULISTA',
  'CAMPOMAIOR': 'CAMPO MAIOR',
  'CAMPOMOURAO': 'CAMPO MOURAO',
  'CAMPONOVODOPARECIS': 'CAMPO NOVO DO PARECIS',
  'CAMPOSDOJORDAO': 'CAMPOS DO JORDAO',
  'CAMPOSDOSGOYTACAZE': 'CAMPOS DOS GOYTACAZES',
  'CAMPOSDOSGOYTACAZES': 'CAMPOS DOS GOYTACAZES',
  'CAMPOSGOYTACAZES': 'CAMPOS DOS GOYTACAZES',
  'CAPAOBONITO': 'CAPAO BONITO',
  'CAPELANOVA': 'CAPELA NOVA',
  'CAPIMGROSSO': 'CAPIM GROSSO',
  'CAPIMGROSSO ': 'CAPIM GROSSO',
  'CARAMUJO': 'NITEROI',
  'CARAPOCUIBA': 'CARAPICUIBA',
  'CARLÓPOLIS': 'CARLOPOLIS',
  'CARMODACACHOEIRA': 'CARMO DA CACHOEIRA',
  'CARMODORIOCLARO': 'CARMO DO RIO CLARO',
  'CASA': 'MAGE',
  'CASABRANCA': 'CASA BRANCA',
  'CASIMIRODEABREU': 'CASIMIRO DE ABREU',
  'CÁSSIA': 'CASSIA',
  'CATUDEABRANTESCAMACAR': 'LAURO DE FREITAS',
  'CATUDEABRANTESCAMACARI': 'LAURO DE FREITAS',
  'CAUCAIA DO ALTO ': 'COTIA',
  'CAUCAIADOALTO': 'COTIA',
  'CAXIASDOSUL': 'CAXIAS DO SUL',
  'CBA': 'CUIABA',
  'Ceará': nan,
  'CEILANDIA': 'BRASILIA',
  'CENTRALDOMARANHAO': 'Central do Maranhão',
  'CENTRO': 'RIO DE JANEIRO',
  'CENTRO-ITU': 'ITU',
  'CERQUEIRACESAR': 'CERQUEIRA CESAR',
  'CERROLARGO': 'CERRO LARGO',
  'CESÁRIO LANGE': 'CESARIO LANGE',
  'CESARIOLANGE': 'CESARIO LANGE',
  'CÉU AZUL': 'CEU AZUL',
  'CHAVESLANDIASANTAVITORIA': 'SANTA VITORIA',
  'CHILE': nan,
  'CICERODANTAS': 'CICERO DANTAS',
  'CIDADE NOVA': nan,
  'CIDADENOVA': nan,
  'CIDADEOCIDENTAL': 'CIDADE OCIDENTAL',
  'CIPOGUACU': 'EMBU GUACU',
  'CITOCENTER  LABORATORIO  MEDICO': nan,
  'COCHABAMBABOLIVIA': nan,
  'COMENDADORVENANCIOITAPERUNA': 'ITAPERUNA',
  'CONCEICAODEJACAREIMANGARATIBA': 'MANGARATIBA',
  'CONCEICAODEMACABU': 'CONCEICAO DE MACABU',
  'CONCEICAODOMATODENTRO': 'CONCEICAO DO MATO DENTRO',
  'CONDSTOANTONIO': nan,
  'CONRADOMIGUELPEREIRA': 'MIGUEL PEREIRA',
  'CONSELHEIROLAFAIETE': 'CONSELHEIRO LAFAIETE',
  'CONSELHEIROPENA': 'CONSELHEIRO PENA',
  'CONTROL LAB': nan,
  'COPACAB': 'RIO DE JANEIRO',
  'COQUEIROSDOSUL': 'COQUEIROS DO SUL',
  'CORNELIOPROCOPIO': 'CORNELIO PROCOPIO',
  'CORONELFABRICIANO': 'CORONEL FABRICIANO',
  'CRUZALTA': 'CRUZ ALTA',
  'CRUZDASALMAS': 'CRUZ DAS ALMAS',
  'CRUZEIRO': 'BRASILIA',
  'CRUZEIRODOSUL': 'CRUZEIRO DO SUL',
  'DCAXIAS': 'DUQUE DE CAXIAS',
  'DCX': 'DUQUE DE CAXIAS',
  'DDECAXIAS': 'DUQUE DE CAXIAS',
  'DEMARCHI': 'SAO BERNARDO DO CAMPO',
  "DIASD'AVILA": "DIAS D'AVILA",
  'DISTRITO FEDERAL': nan,
  'Distrito Federal': nan,
  'DISTRITO INDUSTRIAL DIPER': 'CABO DE SANTO AGOSTINHO',
  'DISTRITO INDUSTRIAL DIPER ': 'CABO DE SANTO AGOSTINHO',
  'DISTRITOFEDERAL': 'BRASILIA',
  'DISTRITOINDUSTRIALDIPER': 'CABO DE SANTO AGOSTINHO',
  'DOISCORREGOS': 'DOIS CORREGOS',
  'DOISVIZINHOS': 'DOIS VIZINHOS',
  'DORESDORIOPRETO': 'DORES DO RIO PRETO',
  'DQDECAXIAS': 'DUQUE DE CAXIAS',
  'DUASBARRAS': 'DUAS BARRAS',
  'DUBAI': nan,
  'DUQDECAXIAS': 'DUQUE DE CAXIAS',
  'DUQEDECAXIAS': 'DUQUE DE CAXIAS',
  'DUQUEDECAXIAS': 'DUQUE DE CAXIAS',
  'ECUADOR': nan,
  'EDEM': 'SAO JOAO DE MERETI',
  'EIODEJANEIRO': 'RIO DE JANEIRO',
  'ELIASFAUSTO': 'ELIAS FAUSTO',
  'ELOIMENDES': 'ELOI MENDES',
  'EMBU': 'EMBU DAS ARTES',
  'EMBUDASARTES': 'EMBU DAS ARTES',
  'EMBUGUACU': 'EMBU GUACU',
  'EMUDASAR': nan,
  'ENBUGUACU': 'EMBU GUACU',
  'ENGENHEIRO PEDREIRA': 'JAPERI',
  'ENGENHEIRO PEDREIRA ': 'RIO DE JANEIRO',
  'ENGENHEIROCOELHO': 'ENGENHEIRO COELHO',
  'ENGENHEIROPAULODEFRON': 'ENGENHEIRO PAULO DE FRONTIN',
  'ENGENHEIROPAULODEFRONTIN': 'ENGENHEIRO PAULO DE FRONTIN',
  'ENGENHEIROPEDREIRA': 'JAPERI',
  'ENGENHO DO ROCADO ': 'SAO GONCALO',
  'ENGENHODOROCADO': 'SAO GONCALO',
  'ENTRERIOSDOOESTE': 'ENTRE RIOS DO OESTE',
  'ESPANHA': 'RIO DE JANEIRO',
  'ESPERAFELIZ': 'ESPERA FELIZ',
  'ESPÍRITO SANTO DO PINHAL': 'ESPIRITO SANTO DO PINHAL',
  'ESPIRITO SANTO DO PINHAL ': 'ESPIRITO SANTO DO PINHAL',
  'ESPIRITOSANTO': 'ESPIRITO SANTO DO PINHAL',
  'ESPIRITOSANTODOPINHAL': 'ESPIRITO SANTO DO PINHAL',
  'EUCLIDESDACUNHA': 'EUCLIDES DA CUNHA',
  'F-V': nan,
  'FAZENDARIOGRANDE': 'FAZENDA RIO GRANDE',
  'FAZENDINHA': nan,
  'FCODAROCHA': 'FRANCO DA ROCHA',
  'FEIRADESANTANA': 'FEIRA DE SANTANA',
  'FERNANDOPRESTES': 'FERNANDO PRESTES',
  'FERRAZ': 'FERRAZ DE VASCONCELOS',
  'FERRAZDEVASCONCELOS': 'FERRAZ DE VASCONCELOS',
  'FLORESDACUNHA': 'FLORES DA CUNHA',
  'FLORESTAAZUL': 'FLORESTA AZUL',
  'FLORIANOPOLES': 'FLORIANOPOLIS',
  'FLORIANÓPOLIS': 'FLORIANOPOLIS',
  'FLORIDAPAULISTA': 'FLORIDA PAULISTA',
  'FORTALEZADOSVALOS': 'FORTALEZA DOS VALOS',
  'FOZDOIGUACU': 'FOZ DO IGUACU',
  'FPOLIS': 'FLORIANOPOLIS',
  'FRANCA': 'RIO DE JANEIRO',
  'FRANCISCOBELTRAO': 'FRANCISCO BELTRAO',
  'FRANCISCOMORATO': 'FRANCISCO MORATO',
  'FRANCODAROCHA': 'FRANCO DA ROCHA',
  'FRDAROCHA': 'FRANCO DA ROCHA',
  'FRMORATO': 'FRANCISCO MORATO',
  'FX': nan,
  'GAMA': 'BRASILIA',
  'GARULHOS': 'GUARULHOS',
  'GARULHOS ': 'GUARULHOS',
  'GENERALSALGADO': 'GENERAL SALGADO',
  'GIRAUDOPONCIANO': 'GIRAU DO PONCIANO',
  'GLICERIO MACAE': 'MACAE',
  'GLICERIO MACAE ': 'GLICERIO MACAE',
  'GLICERIOMACAE': 'GLICERIO MACAE',
  'Goiás': nan,
  'GOITACAZESCAMPOSDOSGOYTACAZES': 'CAMPOS DOS GOYTACAZES',
  'GONCALVESDIAS': 'GONCALVES DIAS',
  'GOVERNADORPORTELAMIGUELPEREIRA': 'MIGUEL PEREIRA',
  'GOVERNADORVALADARES': 'GOVERNADOR VALADARES',
  'GUAIANASES': 'SAO PAULO',
  'GUAÍBA': 'GUAIBA',
  'GUANASES': 'GUAIANASES',
  'GUARA': 'BRASILIA',
  'GUARÁ': 'BRASILIA',
  'GUARANTADONORTE': 'GUARANTA DO NORTE',
  'GUAURLHOS': 'GUARULHOS',
  'GUAURLHOS ': 'GUARULHOS',
  'GURULHOS': 'GUARULHOS',
  'HEMOLABOR': 'GOIANIA',
  'HIDROLANDIA': 'UIBAI',
  'HIDROLANDIA ': 'UIBAI',
  'IATGUAI': 'ITAGUAI',
  'IGARASUU': 'IGARASSU',
  'IGUAPIMIRIN': nan,
  'IJUI ': 'SAO PAULO',
  'ILHA BELA ': 'ILHA BELA',
  'ILHA GRANDE ': 'ANGRA DOS REIS',
  'ILHADOGOVERNADOR': 'RIO DE JANEIRO',
  'ILHAGRANDE': 'ILHA GRANDE',
  'ILHAGRANDEANGRADOSREIS': 'ANGRA DOS REIS',
  'ILHASOLTEIRA': 'ILHA SOLTEIRA',
  'INGA': 'NITEROI',
  'IPUIÚNA': 'IPUIUNA',
  'ITABUNA ': 'ITABUNA',
  'ITACURUSSAMANGARATIBA': 'MANGARATIBA',
  'ITAGAUI': 'ITAGUAI',
  'ITAIPU': 'NITEROI',
  'ITAIPUACU': 'SAO GONCALO',
  'ITAIPUACUMARICA': 'MARICA',
  'ITAMBÉ': 'ITAMBE',
  'ITANHANGA': 'RIO DE JANEIRO',
  'ITAPECERICADASERRA': 'ITAPECERICA DA SERRA',
  'ITAPECIRICA DA SERRA ': 'ITAPECIRICA DA SERRA',
  'ITAPECIRICADASERRA': 'ITAPECIRICA DA SERRA',
  'ITAPECURUMIRIM': 'ITAPECURU MIRIM',
  'ITAPEMA': 'SEROPEDICA',
  'ITAPEMBASANTACATARINA': 'ITAPEMA',
  'ITAPICIRICA DA SERRA': 'ITAPECERICA DA SERRA',
  'ITAPICIRICA DA SERRA ': 'ITAPECIRICA DA SERRA',
  'ITAPICIRICADASERRA': 'ITAPICIRICA DA SERRA',
  'ITAPOÃ': 'ITAPOA',
  'ITAPUNA': 'ITABUNA',
  'ITAQUA': 'ITAQUAQUECETUBA',
  'ITAQUERI DA SERRA ': 'ITIRAPINA',
  'ITAQUERIDASERRA': 'ITIRAPINA',
  'ITAQUERIDASERRAITIRAP': 'ITAQUERI DA SERRA',
  'ITAQUERIDASERRAITIRAPINA': 'ITAQUERI DA SERRA',
  'ITAUDEMINAS': 'ITAU DE MINAS',
  'ITQUAQUECETUBA': 'ITAQUAQUECETUBA',
  'ITU-CIDADENOVA': 'ITU',
  'ITU-JDNOVOMUNDO': 'ITU',
  'ITU-VILAROMA': 'ITU',
  'ITUBAIRROALTO': 'ITU',
  'ITUFLORIDAS': 'ITU',
  'ITUJDDASROSAS': 'ITU',
  'ITUJDMUNIAO': 'ITU',
  'ITUPORTAL': 'ITU',
  'ITUPOTIGUARA': 'ITU',
  'ITUSLUIS': 'ITU',
  'ITUSLUIS ': 'ITU',
  'JABOATAƑODOSGUARARAPES': 'JABOATAO GUARARAPES',
  'JABOATAO': 'JABOATAO DOS GUARARAPES',
  'JABOATAODOSGUARARAPES': 'JABOATAO DOS GUARARAPES',
  'JABOATAOGUARARAPES': 'JABOATAO GUARARAPES',
  'JABPATAƑODOSGUARARAPES': 'JABOATAO GUARARAPES',
  'JACARECABREUVA': 'CABREUVA',
  'JACAREI ': 'JACAREI',
  'JACAREPAGUA': 'RIO DE JANEIRO',
  'JACINTOMACHADO': 'JACINTO MACHADO',
  'JACREI': 'JACAREI',
  'JAPUIBACACHOEIRASDEMA': 'CACHOEIRAS DE MACACU',
  'JAPUIBACACHOEIRASDEMACACU': 'CACHOEIRAS DE MACACU',
  'JARAGUADOSUL': 'JARAGUA DO SUL',
  'JARDIM ABC DE GOIÁS': 'CIDADE OCIDENTAL',
  'JARDIMVARGEMGRANDEPAULISTA': 'VARGEM GRANDE PAULISTA',
  'JDABREUJS': nan,
  'JDAEROPORTO': nan,
  'JDAGARUSSIITU': 'ITU',
  'JDDASROSAS-ITU': 'ITU',
  'JDNOVOITU': 'ITU',
  'JDPARAISOITU': 'ITU',
  'JDPAULISTA': 'SAO PAULO',
  'JOAƑOPESSOA': 'JOAO PESSOA',
  'JOÃO NEIVA': 'JOAO NEIVA',
  'JOAOPESSOA': 'JOAO PESSOA',
  'JOAQUIMTAVORA': 'JOAQUIM TAVORA',
  'JOSE BONIFACIO ': 'JOSE BONIFACIO',
  'JOSEBONIFACIO': 'SAO PAULO',
  'JSL': 'ITAQUAQUECETUBA',
  'JUAZEIRODONORTE': 'JUAZEIRO DO NORTE',
  'JUIZ DEFORA': 'JUIZ DE FORA',
  'JUIZDEFORA': 'JUIZ DE FORA',
  'KM': nan,
  'KY': nan,
  'LAGO SUL': 'BRASILIA',
  'LAGOASANTA': 'LAGOA SANTA',
  'LAPA': 'BOM JESUS DA LAPA',
  'LARANJADATERRA': 'LARANJA DA TERRA',
  'LARANJALPAULISTA': 'LARANJAL PAULISTA',
  'LARANJEIRAS': 'COLOMBIA',
  'LAURODEFREITAS': 'LAURO DE FREITAS',
  'LAURODEFRITAS': 'LAURO DE FREITAS',
  'LEHAMON-FRANCA': 'FRANCA',
  'LENCOISPAULISTA': 'LENCOIS PAULISTA',
  'LISBOA': 'RIO DE JANEIRO',
  'LUCAS DO RIOVERDE': 'LUCAS DO RIO VERDE',
  'LUCASDORIOVERDE': 'LUCAS DO RIO VERDE',
  'MACABU': 'CONCEICAO DE MACABU',
  'MACE': nan,
  'MACHALI': nan,
  'MADHYAPRADESH': nan,
  'MAIRIPORAN': 'MAIRIPORA',
  'MANILHA': 'ITABORAI',
  'MARAU ': 'MARAU',
  'MARESIAS SAO SEBASTIAO ': 'SAO SEBASTIAO',
  'MARESIASSAOSEBASTIAO': 'SAO SEBASTIAO',
  'MARIA FARINHA ': 'PAULISTA',
  'MARIAFARINHA': 'PAULISTA',
  'MARICÁ': 'MARICA',
  'MARICCA': 'MARICA',
  'MATADESAOJOAO': 'MATA DE SAO JOAO',
  'Mato Grosso': nan,
  'MATOGROSSO': 'MATO GROSSO',
  'MAUÁ': 'MAUA',
  'MIGUELPEREIRA': 'MIGUEL PEREIRA',
  'MINAGERAIS': nan,
  'MINASGERAIS': nan,
  'MIRASSOL DO OESTE ': 'MIRASSOL DO OESTE',
  'MIRASSOLDOOESTE': 'MIRASSOL DO OESTE',
  'MOGI': 'MOGI DAS CRUZES',
  'MOGI DAS CRUZES ': 'MOGI DAS CRUZES',
  'MOGIDACRUZES': 'MOGI DAS CRUZES',
  'MOGIDASCRUES': 'MOGI DAS CRUZES',
  'MOGIDASCRUZES': 'MOGI DAS CRUZES',
  'MOGIGUACU': 'MOGI GUACU',
  'MOGIIDASCRUZES': 'MOGI DAS CRUZES',
  'MOGIMIRIM': 'MOGI MIRIM',
  'MOGIS DAS CRUZES': 'MOGI DAS CRUZES',
  'MOGIS DAS CRUZES ': 'MOGI DAS CRUZES',
  'MOGISDASCRUZES': 'MOGIS DAS CRUZES',
  'MOJIDASCRUZES': 'MOGI DAS CRUZES',
  'MONTEALTO': 'MONTE ALTO',
  'MONTEAPRAZIVEL': 'MONTE APRAZIVEL',
  'MONTEAZULPAULISTA': 'MONTE AZUL PAULISTA',
  'MONTEIROLOBATO': 'MONTEIRO LOBATO',
  'MONTEMOR': 'MONTE MOR',
  'MONTESANTODEMINAS': 'MONTE SANTO DE MINAS',
  'MONTESCLAROS': 'MONTES CLAROS',
  'MONTEVERDECAMANDUCAIA': 'CAMANDUCAIA',
  'MORATO': 'PIRACICABA',
  'MOVA IGUACU': 'NOVA IGUACU',
  'MOVA IGUACU ': 'NOVA IGUACU',
  'MOVAIGUACU': 'NOVA IGUACU',
  nan: nan,
  'NAOINFORMADO': 'NAO INFORMADO',
  'NATÉRCIA': 'NATERCIA',
  'NAZAREPAULISTA': 'NAZARE PAULISTA',
  'ND': 'RECIFE',
  'NI': 'NOVA IGUACU',
  'NIEROI': 'NITEROI',
  'NIETROI': 'NITEROI',
  'NIGUACU': 'NOVA IGUACU',
  'NITEOI': 'NITEROI',
  'NITEORI': 'NITEROI',
  'NITERIO': 'NITEROI',
  'NITEROIRJ': 'NITEROI',
  'NITEROIRJ ': 'NITEROI',
  'NITNITEROI': 'NITEROI',
  'NITOROI': 'NITEROI',
  'NIYEROI': 'NITEROI',
  'None': nan,
  'NOSSASENHORADAAPARECIDASAPUCAIA': 'SAPUCAIA',
  'NOVA OLÍMPIA': 'NOVA OLIMPIA',
  'NOVAANDRADINA': 'NOVA ANDRADINA',
  'NOVACRIXAS': 'NOVA CRIXAS',
  'NOVAFRIBURGO': 'NOVA FRIBURGO',
  'NOVAGRANADA': 'NOVA GRANADA',
  'NOVAIGAUCU': 'NOVA IGUACU',
  'NOVAIGUA': 'NOVA IGUACU',
  'NOVAIGUAC': 'NOVA IGUACU',
  'NOVAIGUACU': 'NOVA IGUACU',
  'NOVALACERDA': 'NOVA LACERDA',
  'NOVALIMA': 'NOVA LIMA',
  'NOVAMUTUM': 'NOVA MUTUM',
  'NOVAODESSA': 'NOVA ODESSA',
  'NOVAPRATA': 'NOVA PRATA',
  'NOVASANTAROSA': 'NOVA SANTA ROSA',
  'NOVAVENECIA': 'NOVA VENECIA',
  'NOVAVICOSA': 'NOVA VICOSA',
  'NOVO GAMA ': 'NOVO GAMA',
  'NOVO HAMBURGO ': 'NOVO HAMBURGO',
  'NOVOAMBURGO': 'NOVO HAMBURGO',
  'NOVOGAMA': 'NOVO GAMA',
  'NOVOHAMBURGO': 'NOVO HAMBURGO',
  'NOVOHORIZONTE': 'NOVO HORIZONTE',
  'NTEROI': 'NITEROI',
  'NÚCLEO DE ANÁLISES CLÍNICAS': nan,
  'NY': nan,
  'OSASACO': 'OSASCO',
  'OSASCOSP': 'OSASCO',
  'OTACÍLIO COSTA': 'OTACILIO COSTA',
  'OUROFINO': 'OURO FINO',
  'OUROPRETO': 'OURO PRETO',
  'PALMEIRAS DE GÓIAS': 'PALMEIRAS DE GOIAS',
  'PAPUCAIACACHOEIRASDEMACACU': 'CACHOEIRAS DE MACACU',
  'PARA': 'BELEM',
  'PARADEMINAS': 'PARA DE MINAS',
  'PARAGUACUPAULISTA': 'PARAGUACU PAULISTA',
  'PARANA': 'LONDRINA',
  'Paraná': nan,
  'PARELHEIROS': 'SAO PAULO',
  'PARELHEIROS ': 'PARELHEIROS',
  'PASSAQUATRO': 'PASSA QUATRO',
  'PASSOFUNDO': 'PASSO FUNDO',
  'PATOSDEMINAS': 'PATOS DE MINAS',
  'PATOSDOPIAUI': 'PATOS DO PIAUI',
  'PATROCÍNIO PAULISTA': 'PATROCINIO PAULISTA',
  'PATYDOALFERES': 'PATY DO ALFERES',
  'PAUDOSFERROS': 'PAU DOS FERROS',
  'PEDROCANARIO': 'PEDRO CANARIO',
  'PEIXOTO DE AZEVEDO ': 'PEIXOTO DE AZEVEDO',
  'PELADACARUARU': 'CARUARU',
  'PENDOTIBA': 'NITEROI',
  'Pernambuco': nan,
  'PERUS': 'SAO PAULO',
  'PETROPLIS': 'PETROPOLIS',
  'PETROPOLISVALEDOCUIAB': 'PETROPOLIS VALE DO CUIABA',
  'PETROPOLISVALEDOCUIABA': 'PETROPOLIS',
  'PF': nan,
  'PF-CENTRO': nan,
  'PICADACAFE': 'PICADA CAFE',
  'PICINGUABAUBATUBA': 'UBATUBA',
  'PINDA': 'ILHA BELA',
  'PIRAÍ': 'PIRAI',
  'PIRAPORADOBOMJESUS': 'PIRAPORA DO BOM JESUS',
  'PIRATININGA ': 'PIRATININGA',
  'PIRATININGUA': 'NITEROI',
  'PLANALTINA DE GOIÁS': 'PLANALTINA',
  'POCOSDECALDAS': 'POCOS DE CALDAS',
  'POLVILHO': 'CAJAMAR',
  'POLVILHOCAJAMAR': 'CAJAMAR',
  'PONTA NEGRA ': 'MARICA',
  'PONTAGROSSA': 'PONTA GROSSA',
  'PONTAL DO PARANÁ': 'PONTAL DO PARANA',
  'PONTALDOPARANA': 'PONTAL DO PARANA',
  'PONTANEGRA': 'PONTA NEGRA',
  'PONTAPORA': 'PONTA PORA',
  'PORTALDASALAMEDAS': 'FRANCO DA ROCHA',
  'PORTALMORUMBI': 'SAO PAULO',
  'PORTOALEGRE': 'PORTO ALEGRE',
  'PORTODEPEDRAS': 'PORTO DE PEDRAS',
  'PORTOFELIZ': 'PORTO FELIZ',
  'PORTONACIONAL': 'PORTO NACIONAL',
  'PORTOREAL': nan,
  'PORTOSEGURO': 'PORTO SEGURO',
  'PORTOVELHO': 'PORTO VELHO',
  'PORTOXAVIER': 'PORTO XAVIER',
  'PORTUGAL': nan,
  'POSTO DA MATA': 'NOVA VICOSA',
  'POSTO TESTE': nan,
  'POTIGUARAITU': 'ITU',
  'POUSOALEGRE': 'POUSO ALEGRE',
  'POUSOALTO': 'POUSO ALTO',
  'PRAIAGRANDE': 'PRAIA GRANDE',
  'PRAIASECAARARUAMA': 'ARARUAMA',
  'PRESIDENTEEPITACIO': 'PRESIDENTE EPITACIO',
  'PRESIDENTEPRUDENTE': 'PRESIDENTE PRUDENTE',
  'PRESMEDICEITU': 'ITU',
  'QUATIGUÁ': 'QUATIGUA',
  'RANCHO FUNDO ': 'NOVA IGUACU',
  'RANCHOFUNDO': 'RANCHO FUNDO',
  'RANCHOGRANDE': 'ITU',
  'REDENCAODASERRA': 'REDENCAO DA SERRA',
  'REGIAOMETROPOLITANA': nan,
  'REIODEJANEIRO': 'RIO DE JANEIRO',
  'RESSAOCAMILO': nan,
  'RIACHO FUNDO ': 'RIACHO FUNDO',
  'RIACHOFUNDO': 'BRASILIA',
  'RIBEIRAOBRANCO': 'RIBEIRAO BRANCO',
  'RIBEIRAODASNEVES': 'RIBEIRAO DAS NEVES',
  'RIBEIRAODOSUL': 'RIBEIRAO DO SUL',
  'RIBEIRAOPIRES': 'RIBEIRAO PIRES',
  'RIBEIRAOPRETO': 'RIBEIRAO PRETO',
  'RIDEJANEIRO': 'RIO DE JANEIRO',
  'RIIODEJANEIRO': 'RIO DE JANEIRO',
  'RIO DE JANERIRO': 'RIO DE JANEIRO',
  'RIO DE JANERIRO ': 'RIO DE JANEIRO',
  'RIO DO OURO ': 'NITEROI',
  'RIO GERAL ': 'RIO DE JANEIRO',
  'RIO PEQUENO ': 'SAO PAULO',
  'RIOBONITO': 'RIO BONITO',
  'RIOBRANCO': 'RIO BRANCO',
  'RIOCASCA': 'RIO CASCA',
  'RIOCLARO': 'RIO CLARO',
  'RIOCOMPRIDO': 'RIO DE JANEIRO',
  'RIODASFLORES': 'RIO DAS FLORES',
  'RIODASOSTARS': 'RIO DAS OSTRAS',
  'RIODASOSTRAS': 'RIO DAS OSTRAS',
  'RIODASPEDRAS': 'RIO DAS PEDRAS',
  'RIODEAJNEIRO': 'RIO DE JANEIRO',
  'RIODEAPTO': nan,
  'RIODEBJANEIRO': 'RIO DE JANEIRO',
  'RIODEJ': 'RIO DE JANEIRO',

In [52]:
df_sabin_covid.replace(rename_cols_dict)['SC2_test_result']

0        Neg
1        Pos
2        Neg
3        Pos
4        Pos
        ...
72779    Neg
72780    Neg
72781    Neg
72782    Neg
72783    Neg
Name: SC2_test_result, Length: 72784, dtype: object

In [53]:
df_sabin_covid

,lab_id,test_id,test_kit,sample_id,Código Posto,state,location,date_testing,birthdate,sex,...,FLUB_test_result,VSR_test_result,META_test_result,RINO_test_result,PARA_test_result,ADENO_test_result,BOCA_test_result,COVS_test_result,ENTERO_test_result,BAC_test_result
0,SABIN,321-66464-12445,covid_pcr,,321,DISTRITO FEDERAL,BRASÍLIA,2022-12-21,1980-11-17,Feminino,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
1,SABIN,525-66472-8612,covid_pcr,,525,DISTRITO FEDERAL,BRASÍLIA,2022-12-29,1983-11-26,Feminino,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
2,SABIN,324-66472-9108,covid_pcr,,324,PARÁ,BELÉM,2022-12-29,1958-09-21,Masculino,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
3,SABIN,891-66472-10158,covid_pcr,,891,GOIAS,ANAPOLIS,2022-12-29,2002-11-17,Masculino,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
4,SABIN,407-66472-10869,covid_pcr,,407,TOCANTINS,PALMAS,2022-12-29,1959-09-17,Feminino,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72779,SABIN,1858-66664-2197,covid_antigen,,1858,MATO GROSSO,CUIABA,2023-09-07,1995-04-13,Masculino,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
72780,SABIN,1858-66664-2211,covid_antigen,,1858,MATO GROSSO,CUIABA,2023-09-07,1961-09-01,Masculino,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
72781,SABIN,1409-66664-2220,covid_antigen,,1409,MATO GROSSO,CUIABA,2023-09-07,2022-12-11,Feminino,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
72782,SABIN,1858-66664-2250,covid_antigen,,1858,MATO GROSSO,CUIABA,2023-09-07,1997-02-08,Feminino,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT
72783,SABIN,1409-66664-2379,covid_antigen,,1409,MATO GROSSO,CUIABA,2023-09-07,2021-05-10,Masculino,...,NT,NT,NT,NT,NT,NT,NT,NT,NT,NT